---
settings:
  name: Element Software
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: 12.5 and 12.7
    url: "/element-software"
  - version-number: '12.3'
    url: "/element-software-123"
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione software SolidFire ed Element
    url: "/index.html"
  - title: Note di rilascio
    url: "/concepts/concept_rn_relatedrn_element.html"
    entries:
    - title: Novità
      url: "/concepts/concept_rn_whats_new_element.html"
  - section: concepts
  - title: Requisiti
    url: "/setup/concept_requirements_overview.html"
    entries:
    - title: Requisiti di rete
      url: "/storage/concept_prereq_networking.html"
    - title: Configurazione dello switch per i cluster che eseguono il software Element
      url: "/storage/concept_prereq_switch_configuration_for_solidfire_clusters.html"
    - title: Requisiti delle porte di rete
      url: "/storage/reference_prereq_network_port_requirements.html"
  - section: try
  - section: hardware
  - section: setup
  - section: storage
  - section: hccstorage
  - section: api
  - title: Gestione dello storage con il plug-in Element per vCenter Server
    url: "/element-plug-in-index.html"
  - title: Monitorare lo storage con NetApp SolidFire Active IQ
    url: "/monitor-storage-active-iq.html"
  - section: mnode
  - section: upgrade
  - title: Versioni precedenti
    url: "/element-earlierversions.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Panoramica del prodotto
      url: "/concepts/concept_intro_product_overview.html"
    - title: Note di rilascio
      url: "/concepts/concept_rn_relatedrn_element.html"
    - title: Novità
      url: "/concepts/concept_rn_whats_new_element.html"
    - title: Requisiti
      url: "/setup/concept_requirements_overview.html"
    - title: Panoramica dell'installazione
      url: "/setup/concept_setup_overview.html"
  - title: Installazione e manutenzione dell'hardware
    links:
    - title: Informazioni sull'hardware H410S e H610S
      url: "/hardware/concept_h410s_h610s_info.html"
    - title: Informazioni sull'hardware della serie SF
      url: "/hardware/concept_sfseries_info.html"
    - title: Tornare alle informazioni immagine di fabbrica
      url: "/hardware/concept_rtfi_configure.html"
    - title: Revisioni del firmware supportate per i nodi di storage NetApp H-Series
      url: "/hardware/fw_storage_nodes.html"
  - title: Gestire lo storage
    links:
    - title: Utilizzare l'interfaccia utente del software Element
      url: "/storage/index.html"
    - title: Utilizza NetApp Hybrid Cloud Control
      url: "/hccstorage/index.html"
    - title: USA API software Element
      url: "/api/index.html"
    - title: USA plug-in Element per vCenter Server
      url: https://docs.netapp.com/us-en/vcp/
    - title: Utilizza NetApp SolidFire Active IQ
      url: https://docs.netapp.com/us-en/solidfire-active-iq/
    - title: Lavorare con il nodo di gestione
      url: "/mnode/task_mnode_work_overview.html"
  - title: Utilizzare gli strumenti di integrazione (accesso richiesto)
    links:
    - title: Elemento CLI
      url: https://mysupport.netapp.com/site/tools/tool-eula/elem-cli
    - title: Tool PowerShell Element
      url: https://mysupport.netapp.com/site/tools/tool-eula/elem-powershell-tools
    - title: SDK di elementi (Java, .NET, Python)
      url: https://mysupport.netapp.com/site/products/all/details/netapphci-solidfire-elementsoftware/tools-tab
    - title: Suite di test API Postman di SolidFire
      url: https://github.com/solidfire/postman
    - title: Adattatore per la replica dello storage SolidFire
      url: https://mysupport.netapp.com/site/products/all/details/elementsra/downloads-tab
    - title: SolidFire Vro
      url: https://mysupport.netapp.com/site/products/all/details/solidfire-vro/downloads-tab
    - title: Provider VSS di SolidFire
      url: https://mysupport.netapp.com/site/products/all/details/solidfire-vss-provider/downloads-tab
  - title: Soluzioni
    links:
    - title: Pagina delle risorse SolidFire
      url: https://www.netapp.com/data-storage/solidfire/documentation/
    - title: Soluzioni NetApp
      url: https://docs.netapp.com/us-en/netapp-solutions/index.html
  - title: Demo e tutorial
    links:
    - title: Training NetApp University SolidFire (accesso obbligatorio)
      url: https://netapp.sabacloud.com/Saba/Web_spf/NA1PRD0047/common/searchresults/solidfire/LEARNINGEVENT%2COFFERINGTEMPLATE%2CCERTIFICATION%2CCURRICULUM%2COFFERING%2CPACKAGE
    - title: Come installare e scalare il tuo cluster NetApp SolidFire (video)
      url: http://tv.netapp.com/detail/video/5778540099001?autoStart=true&page=1&q=solidfire
    - title: Installazione di NetApp SolidFire (video)
      url: https://youtu.be/YKGK5nNSL68
  - title: Blog e community
    links:
    - title: Community di NetApp
      url: https://community.netapp.com/t5/AFF-NVMe-EF-Series-and-SolidFire-Discussions/bd-p/flash-storage-systems-discussions
    - title: Dove ottenere aiuto
      url: https://mysupport.netapp.com/site/products/all/details/element-software/guideme-tab
  - title: Versioni precedenti
    links:
    - title: Documentazione di Element 12,3.x
      url: https://docs.netapp.com/us-en/element-software-123/index.html
    - title: Documentazione di Element 12.2.1
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63945&language=en-US
    - title: Documentazione di Element 12.2
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63593&language=en-US
    - title: Documentazione di Element 12.0.1
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63946&language=en-US
    - title: Documentazione di Element 12,0
      url: https://mysupport.netapp.com/documentation/docweb/index.html?productID=63368&language=en-US
    - title: Element 11.8.2 e documentazione precedente
      url: "/element-earlierversions.html"
