---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: 'Puoi mantenere aggiornato il tuo sistema storage SolidFire Element dopo l"implementazione aggiornando tutti i componenti dello storage NetApp.' 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Panoramica della sequenza di aggiornamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: solidfire, cloud, onprem, documentation, help


[role="lead"]
Puoi mantenere aggiornato il tuo sistema storage SolidFire Element dopo l'implementazione aggiornando in sequenza tutti i componenti dello storage NetApp.

Questi componenti includono servizi di gestione, controllo del cloud ibrido NetApp, software Element, nodo di gestione e (a seconda dell'installazione) il plug-in Element per vCenter Server.

[NOTE]
====
* A partire da Element 12,7, i nodi storage SF2405 e SF9608 e i nodi FC FC0025 e SF-FCN-01 non sono supportati. Se si tenta di aggiornare uno di questi nodi all'elemento 12,7, viene visualizzato un errore che indica che questo nodo non è supportato dall'elemento 12,7.
* A partire da Element 12.5, NetApp HealthTools non è più supportato per gli aggiornamenti del software Element. Se si esegue Element 11.0 o 11.1, è necessario prima https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Eseguire l'aggiornamento a Element 12.3 utilizzando HealthTools"^] E quindi eseguire l'aggiornamento a Element 12.5 o versioni successive utilizzando NetApp Hybrid Cloud Control.


====
Il <<sys_upgrade,sequenza di aggiornamento del sistema>> Il contenuto descrive le attività necessarie per completare un aggiornamento del sistema storage all-flash SolidFire. Idealmente, queste procedure vengono eseguite come parte di una sequenza di aggiornamento più ampia e non in maniera isolata. Se è necessario un aggiornamento o un aggiornamento basato su componenti, consultare i prerequisiti della procedura per assicurarsi che vengano risolte ulteriori complessità.

Il link:task_sf_upgrade_all_vsphere.html["Sequenza di aggiornamento di vSphere"] L'inclusione del contenuto di Element Plug-in per vCenter Server descrive le fasi aggiuntive di pre e post-aggiornamento necessarie per reinstallare Element Plug-in per vCenter Server.

.Di cosa hai bisogno
* Si sta eseguendo il nodo di gestione 11.3 o versione successiva. Le versioni più recenti del nodo di gestione dispongono di un'architettura modulare che fornisce servizi individuali.
+

TIP: Per controllare la versione, accedere al nodo di gestione e visualizzare il numero di versione dell'elemento nel banner di accesso. Se non si dispone di 11.3, vedere link:task_hcc_upgrade_management_node.html["Aggiorna il nodo di gestione"].

* I servizi di gestione sono stati aggiornati almeno alla versione 2.1.326.
+
Gli aggiornamenti che utilizzano NetApp Hybrid Cloud Control non sono disponibili nelle versioni precedenti del service bundle.

* Hai garantito che l'ora di sistema su tutti i nodi sia sincronizzata e che NTP sia configurato correttamente per il cluster di storage e i nodi. Ciascun nodo deve essere configurato con un server dei nomi DNS nell'interfaccia utente Web per nodo (`https://[IP address]:442`) senza errori del cluster irrisolti correlati all'inclinazione temporale.
* È stato pianificato un tempo sufficiente per il link:task_hcc_upgrade_element_software.html#element-upgrade-time["Software Element"] e. link:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["firmware dello storage"] aggiornamenti. Quando si esegue l'aggiornamento al software Element 12.5 o versione successiva, il tempo di aggiornamento varia in base alla versione del software Element e agli aggiornamenti del firmware.




== [[sys_upgrade]]sequenza di aggiornamento del sistema

Puoi utilizzare la seguente sequenza per aggiornare il sistema storage all-flash NetApp SolidFire per Element 12,5 o versione successiva.

.Fasi
. link:task_hcc_update_management_services.html["Servizi di gestione degli aggiornamenti da Hybrid Cloud Control"].
+

IMPORTANT: Se si aggiornano i servizi di gestione alla versione 2.16 o successiva e si esegue un nodo di gestione da 11.3 a 11.8, sarà necessario aumentare la RAM della VM del nodo di gestione prima di aggiornare i servizi di gestione.

+

IMPORTANT: Prima di aggiornare il software Element, è necessario eseguire l'aggiornamento al bundle di servizi di gestione più recente.

. link:task_hcc_upgrade_element_prechecks.html["Eseguire i controlli dello stato dello storage Element prima di aggiornare lo storage"].
. link:task_hcc_upgrade_element_software.html["Aggiorna il software Element e il firmware dello storage"].
. link:task_hcc_upgrade_storage_firmware.html["(Opzionale) aggiornare solo il firmware dello storage Element"].
+

NOTE: È possibile eseguire questa operazione quando un nuovo aggiornamento del firmware dello storage diventa disponibile al di fuori di una release principale.

. link:task_hcc_upgrade_management_node.html["(Facoltativo) Aggiorna il nodo di gestione"].
+

NOTE: L'aggiornamento del sistema operativo del nodo di gestione non è più necessario per aggiornare il software Element sul cluster di storage. Se il nodo di gestione è la versione 11.3 o superiore, è sufficiente aggiornare i servizi di gestione alla versione più recente per eseguire gli aggiornamenti degli elementi utilizzando NetApp Hybrid Cloud Control. Se si desidera aggiornare il sistema operativo del nodo di gestione per altri motivi, ad esempio la risoluzione dei problemi di protezione, seguire la procedura di aggiornamento del nodo di gestione per lo scenario in uso.

. link:task_vcp_upgrade_plugin.html["Aggiorna il plug-in Element per vCenter Server"].


[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]

