---
sidebar: sidebar 
permalink: mnode/task_mnode_add_assets.html 
summary: 'È possibile aggiungere una risorsa controller alla configurazione del nodo di gestione utilizzando l"interfaccia utente REST API.' 
keywords: netapp, mnode, management node, rest api, Element 
---
= Aggiungere una risorsa controller al nodo di gestione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere una risorsa controller alla configurazione del nodo di gestione utilizzando l'interfaccia utente REST API.

Potrebbe essere necessario aggiungere una risorsa se l'installazione è stata scalata di recente e le nuove risorse non sono state aggiunte automaticamente alla configurazione. Utilizza queste API per aggiungere risorse aggiunte di recente all'installazione.

.Di cosa hai bisogno
* La versione del cluster in uso esegue il software NetApp Element 11.3 o versione successiva.
* È stato implementato un nodo di gestione con versione 11.3 o successiva.
* Hai creato un nuovo ruolo NetApp HCC in vCenter per limitare la vista dei servizi del nodo di gestione alle risorse solo NetApp. Vedere link:task_mnode_create_netapp_hcc_role_vcenter.html["Creare un ruolo NetApp HCC in vCenter"]


.Fasi
. Ottenere l'ID risorsa di base per l'installazione:
+
.. Aprire l'interfaccia utente REST API del servizio di inventario sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Selezionare *autorizzare* e completare le seguenti operazioni:
+
... Inserire il nome utente e la password del cluster.
... Immettere l'ID client come `mnode-client`.
... Selezionare *autorizzare* per avviare una sessione.
... Chiudere la finestra.


.. Dall'interfaccia utente API REST, selezionare *GET ​/Installations*.
.. Selezionare *Provalo*.
.. Selezionare *Esegui*.
.. Dal corpo della risposta del codice 200, copiare il `id` per l'installazione.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: L'installazione dispone di una configurazione delle risorse di base creata durante l'installazione o l'aggiornamento.

.. Dall'interfaccia utente API REST, selezionare *GET /Installations/{id}*.
.. Selezionare *Provalo*.
.. Incollare l'ID della risorsa di installazione nel campo *id*.
.. Selezionare *Esegui*.
.. Dalla risposta, copiare e salvare l'ID del controller del cluster (`"controllerId"`) da utilizzare in un passaggio successivo.


. Per aggiungere una sottorisorsa del controller a una risorsa di base esistente, selezionare:
+
[listing]
----
POST /assets/{asset_id}/controllers
----
+
.. Aprire l'interfaccia utente dell'API REST del servizio mNode sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Selezionare *autorizzare* e completare le seguenti operazioni:
+
... Inserire il nome utente e la password del cluster.
... Immettere l'ID client come `mnode-client`.
... Selezionare *autorizzare* per avviare una sessione.
... Chiudere la finestra.


.. Selezionare *POST /assets/{asset_id}/controller*.
.. Selezionare *Provalo*.
.. Inserire l'ID risorsa di base principale nel campo *asset_id*.
.. Aggiungere i valori richiesti al payload.
.. Selezionare *Esegui*.




[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]

