---
sidebar: sidebar 
permalink: mnode/task_mnode_configure_proxy_server.html 
summary: Se il cluster si trova dietro un server proxy, è necessario configurare le impostazioni del proxy per raggiungere una rete pubblica. 
keywords: netapp, Element, mnode, api, management node, add proxy, proxy server 
---
= Configurare un server proxy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se il cluster si trova dietro un server proxy, è necessario configurare le impostazioni del proxy in modo da poter accedere a una rete pubblica.

Un server proxy viene utilizzato per i servizi di raccolta di telemetria e le connessioni di reverse tunnel. È possibile attivare e configurare un server proxy utilizzando l'interfaccia utente API REST se non è già stato configurato un server proxy durante l'installazione o l'aggiornamento. È inoltre possibile modificare le impostazioni del server proxy esistente o disattivare un server proxy.

Il comando per configurare un server proxy viene aggiornato e restituisce le impostazioni proxy correnti per il nodo di gestione. Le impostazioni proxy vengono utilizzate da Active IQ, dal servizio di monitoraggio NetApp e da altre utility software Element installate nel nodo di gestione, incluso il tunnel di supporto inverso per il supporto NetApp.

.Prima di iniziare
* È necessario conoscere le informazioni relative all'host e alle credenziali per il server proxy che si sta configurando.
* Assicurarsi che la versione del cluster in uso utilizzi il software NetApp Element 11.3 o versione successiva.
* Assicurarsi di aver implementato un nodo di gestione con versione 11.3 o successiva.
* (Nodo di gestione 12.0 e versioni successive) hai aggiornato NetApp Hybrid Cloud Control alla versione 2.16 dei servizi di gestione prima di configurare un server proxy.


.Fasi
. Accedere all'interfaccia utente API REST sul nodo di gestione immettendo l'indirizzo IP del nodo di gestione seguito da `/mnode`:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. Selezionare *autorizzare* o qualsiasi icona a forma di lucchetto e completare le seguenti operazioni:
+
.. Inserire il nome utente e la password del cluster.
.. Immettere l'ID client come `mnode-client`.
.. Selezionare *autorizzare* per avviare una sessione.
.. Chiudere la finestra.


. Selezionare *PUT /settings*.
. Selezionare *Provalo*.
. Per attivare un server proxy, è necessario impostare `use_proxy` a vero. Immettere l'IP o il nome host e le destinazioni della porta proxy.
+
Il nome utente del proxy, la password del proxy e la porta SSH sono opzionali e devono essere omessi se non utilizzati.

+
[listing]
----
{
"proxy_ip_or_hostname": "[IP or name]",
"use_proxy": [true/false],
"proxy_username": "[username]",
"proxy_password": "[password]",
"proxy_port": [port value],
"proxy_ssh_port": [port value: default is 443]
}
----
. Selezionare *Esegui*.



NOTE: Potrebbe essere necessario riavviare il nodo di gestione a seconda dell'ambiente in uso.

[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]

