---
permalink: concepts/concept_rn_whats_new_element.html 
sidebar: sidebar 
keywords: netapp, solidfire, element, storage, solidfire enterprise sds 
summary: NetApp aggiorna periodicamente SolidFire e il software Element per offrire nuove funzionalità, miglioramenti e correzioni di bug. 
---
= Novità del software Element
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp aggiorna periodicamente i software SolidFire ed Element per offrirti nuove funzionalità, miglioramenti e correzioni di bug. Element 12.9 è la versione più recente e include aggiornamenti dei componenti di sistema e di sicurezza, miglioramenti operativi e problemi risolti.


NOTE: Gli aggiornamenti cumulativi di software e firmware vengono installati come parte di un aggiornamento di Element 12.9 basato sulla versione corrente di Element in esecuzione su un cluster di storage. Ad esempio, se un cluster esegue attualmente Element 12.5, è possibile eseguire l'aggiornamento direttamente a Element 12.9 per ottenere gli aggiornamenti cumulativi da Element 12.7, 12.8 e 12.9. Per i percorsi di aggiornamento supportati, consultare l'articolo della Knowledge Base https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software["Qual è la matrice di aggiornamento per i cluster storage che eseguono il software NetApp Element"^] .



== Elemento 12.9

Scopri le novità di Element 12.9.



=== Supporto per FQDN in "SetRemoteLoggingHosts"

A partire dall'elemento 12.9, è possibile utilizzare `SetRemoteLoggingHosts` Metodo per configurare un nome di dominio completo (FQDN) o un indirizzo IP come valore host di registrazione per un cluster di archiviazione.  È possibile visualizzare il valore host FQDN nella risposta per `GetRemoteLoggingHosts` metodo.  Per Element 12.8 e versioni precedenti, è possibile configurare solo un indirizzo IP come valore host di registrazione.

https://docs.netapp.com/us-en/element-software/api/reference_element_api_loggingserver.html["Scopri di più sulla registrazione della configurazione dell'host"]



== Elemento 12,8

Scopri le novità di Element 12.8.



=== Bilanciamento del carico dei volumi

L'elemento 12,8 introduce la funzione di bilanciamento del carico del volume. È possibile utilizzare questa funzionalità per bilanciare i volumi nei nodi in base al livello di IOPS effettivo di ciascun volume, anziché agli IOPS minimi configurati nel policy di QoS. È possibile utilizzare la funzione bilanciamento del carico volume solo per bilanciare i volumi. Non è possibile utilizzarlo per bilanciare i volumi virtuali. La funzione bilanciamento del carico volume è disattivata per impostazione predefinita. È possibile attivarlo e disattivarlo utilizzando il `VolumeLoadBalanceOnActualIOPS` parametro API con i link:../api/reference_element_api_enablefeature.html["EnableFeature"]metodi e link:../api/reference_element_api_disablefeature.html["DisableFeature"] API o utilizzando l'link:../storage/task_system_manage_cluster_volume_load_balancing.html["Bilanciamento del carico dei volumi"]opzione nell'interfaccia utente di Element.



=== Visualizzare le informazioni sull'utilizzo dei nodi

Con Element 12,8, è possibile visualizzare le informazioni sull'utilizzo dei nodi come `nodeHeat` utilizzando i `GetNodeStats` metodi e `ListNodeStats` API. L' `nodeHeat`oggetto è un membro dell' `nodeStats`oggetto e visualizza le informazioni sull'utilizzo dei nodi sulla base del rapporto tra IOPS totali primari o IOPS totali e gli IOPS configurati, mediati nel tempo.

Inoltre, è possibile visualizzare l'utilizzo dei nodi come percentuale di `recentPrimaryTotalHeat` nella visualizzazione Dettagli vista per un nodo nell'interfaccia utente dell'elemento.



=== Visualizzare le statistiche di i/o di un volume

Con Element 12,8, è possibile visualizzare le statistiche di utilizzo i/o di un volume come `sliceIopsStats` utilizzando i `GetVolumeStats` metodi e `ListVolumeStatsByVolume` API. Le statistiche i/o sono calcolate utilizzando le informazioni IOPS in lettura e scrittura per il volume, misurate in due periodi, le ultime 24 ore e l'ultima ora. link:../api/reference_element_api_volumestats.html#object-members["Scopri di più"].



=== Algoritmo CHAP per sessione iSCSI

Un iniziatore iSCSI host richiede un elenco di algoritmi CHAP (Challenge-Handshake Authentication Protocol) da utilizzare quando si crea una sessione iSCSI con una destinazione iSCSI Element. A partire dall'elemento 12,8, è possibile visualizzare l'algoritmo CHAP supportato che la destinazione iSCSI dell'elemento sceglie di utilizzare per una sessione iSCSI.



=== Aggiornare la versione hardware della VM

Se si sta eseguendo un aggiornamento sul posto di un nodo di gestione esistente all'elemento 12,8, prima di eseguire l'aggiornamento, è necessario assicurarsi che la versione hardware della VM sul nodo di gestione sia compatibile con ESXi 6,7 (VM hardware versione 14) o successiva, a seconda dell'ambiente in uso. link:../upgrade/task_hcc_upgrade_management_node.html#step-1-upgrade-vm-hardware-version-on-a-management-node["Scopri di più"].



== Elemento 12,7

Scopri le novità di Element 12.7.



=== Algoritmi CHAP sicuri

Element 12,7 include il supporto per algoritmi SHA1, SHA-256 e SHA3-256 sicuri e conformi FIPS Challenge-Handshake Authentication Protocol (CHAP). link:../storage/task_data_manage_accounts_work_with_accounts_task.html["Scopri di più"].



=== Velocità di sincronizzazione dei blocchi dinamici (bin)

Operazioni del cluster come aggiunte, upgrade o manutenzione di nodi, o aggiunta di dischi e così via. Attivano la sincronizzazione del blocco (bin) per distribuire i dati del blocco ai nodi nuovi o aggiornati del layout di un cluster. L'utilizzo di una singola velocità lenta come velocità di sincronizzazione predefinita fa sì che queste operazioni richiedano molto tempo e non sfrutti la maggiore potenza di elaborazione dei nodi più grandi. A partire dall'elemento 12,7, il tasso di sincronizzazione viene ottimizzato dinamicamente in base al numero di core presenti nel nodo storage, consentendo operazioni molto più veloci.

Ad esempio, quando si aggiungono a un cluster esistente nodi storage 28-core di grandi dimensioni (H610S, SF19210 e SF38410) che eseguono Element 12,7, la velocità di sincronizzazione per i dati viene automaticamente sintonizzata su 110Mbps invece che su 60Mbps. Inoltre, quando si portano questi grandi nodi storage fuori dalla modalità di manutenzione dei nodi, ad esempio durante un upgrade da Element 12,3.x o versione successiva a Element 12,7 utilizzando il controllo cloud ibrido NetApp, il tasso di sincronizzazione per il tasso di dati dei blocchi modificati si sintonizza automaticamente su 110Mbps invece che su 20Mbps.

Aggiungendo i nodi storage 16-core medi (H410S) e i nodi storage 12-core piccoli (SF4805) a un cluster Element 12,7, la velocità di sincronizzazione dei dati resterà di 60Mbps; tuttavia, per sincronizzare i blocchi modificati quando li si porta fuori dalla modalità di manutenzione dei nodi durante gli aggiornamenti da Element 12,3.x a Element 12,7, la velocità di sincronizzazione si sintonizza automaticamente da 20Mbps a 60Mbps per i nodi di storage medi e da 40Mbps per i nodi di storage più piccoli.

Quando si rimuovono i nodi di storage, non si verifica alcun impatto sulla velocità di Sync-out dei blocchi, che consente di evitare l'impatto delle performance sull'i/o dei client



=== Miglioramento di Garbage Collection

Per i cluster con nodi storage più ampi, ad esempio un H610S-4, con 1PB TB di spazio utilizzato, eseguono carichi di lavoro molto elevati con sovrascritture, e hanno un'elevata deduplica e compressione, l'operazione Garbage Collection può ora restare al passo con l'aumento delle dimensioni predefinite del filtro del bloom per i nodi più grandi da 700GB GB o più di memoria a 1048576 bit. Questa modifica ha effetto automaticamente dopo l'upgrade dei nodi storage a Element 12,7 e non influisce sui nodi più piccoli.



=== Miglioramento della scalabilità

Con Element 12,7 non è più necessario seguire sequenziamento specifico quando si aggiungono più nodi storage di dischi a blocchi e metadati a un cluster esistente. Utilizzando l'interfaccia utente o l'API di Element, è possibile selezionare tutte le unità disponibili e aggiungerle contemporaneamente in blocco. L'elemento 12,7 gestisce automaticamente la sincronizzazione dei dati in modo che tutti i servizi di blocco vengano sincronizzati contemporaneamente. Quando i servizi di blocco per ogni nodo completano la sincronizzazione, l'unità di metadati su quel nodo diventa assegnabile ai volumi host. Questo miglioramento di scala riduce significativamente la latenza di risposta in lettura e impedisce il peggioramento delle performance, durante la sincronizzazione dei dati con i nodi storage appena aggiunti.



=== Aggiornamenti del firmware del nodo di storage

Element 12,7 include il bundle del firmware di storage versione 2.164.0, che include il supporto per i nuovi componenti del sistema. link:https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.164.0.html["Scopri di più"].


NOTE: Non sono disponibili nuovi aggiornamenti firmware in Element 12,7. Tuttavia, in base all'attuale bundle firmware in esecuzione sui nodi storage, gli aggiornamenti cumulativi vengono installati quando si esegue l'upgrade a Element 12,7.



=== Documentazione SolidFire Active IQ

Nell'interfaccia utente di SolidFire Active IQ, è possibile accedere alla pagina Gestione QoS per visualizzare consigli e informazioni sulla limitazione dei nodi per il cluster. Inoltre, ora la dashboard del cluster visualizza il numero totale di Snapshot. Altri recenti miglioramenti includono l'aggiunta di informazioni sui nodi primari e secondari per i volumi attivi e il throughput medio, gli IOPS e la latenza media per gli ultimi 30 minuti sui volumi primari su un nodo.

È ora possibile accedere alla documentazione SolidFire Active IQ dalla documentazione del software Element. link:https://docs.netapp.com/us-en/element-software/monitor-storage-active-iq.html["Scopri di più"].



=== NetApp Bugs Online contiene problemi risolti e noti

I problemi noti e risolti sono elencati nello strumento online bug di NetApp. È possibile esaminare questi problemi per il software Element e altri prodotti all'indirizzo https://mysupport.netapp.com/site/products/all/details/element-software/bugsonline-tab["NetApp Bugs Online"^].



== Elemento 12,5

Scopri le novità di Element 12.5.



=== Migliore accesso al nodo storage

Element 12.5 migliora l'accesso remoto ai singoli nodi utilizzando certificati SSH firmati. Per fornire un accesso remoto sicuro ai nodi di storage, un nuovo account utente locale con privilegi limitati chiamato `sfreadonly` Viene ora creato durante RTFI di un nodo di storage. Il `sfreadonly` account consente l'accesso al backend del nodo di storage per scopi di manutenzione di base o di risoluzione dei problemi. È ora possibile configurare `supportAdmin` Tipo di accesso per un utente amministratore del cluster per consentire al supporto NetApp di accedere al cluster in base alle esigenze.



=== Gestibilità avanzata dei domini di protezione personalizzati

Element 12.5 dispone di una nuova interfaccia utente che consente di visualizzare in modo rapido e semplice i domini di protezione personalizzati esistenti e di configurare nuovi domini di protezione personalizzati.



=== Guasti, eventi e avvisi del cluster nuovi e migliorati

L'elemento 12.5 migliora la risoluzione dei problemi del sistema con l'introduzione dei nuovi codici di guasto del cluster `BmcSelfTestFailed` e. `CpuThermalEventThreshold`. L'elemento 12.5 contiene inoltre miglioramenti di robustezza per gli eventi e gli avvisi del cluster esistenti, ad esempio `nodeOffline`, `volumeOffline`, `driveHealthFault`, `networkEvent`, e.	`cSumEvent`.



=== Abilitare la crittografia software a riposo dall'interfaccia utente di creazione cluster

Con l'aggiunta di una nuova casella di controllo nell'interfaccia utente di creazione cluster, Element 12.5 consente di attivare la crittografia software a livello di cluster a riposo per i cluster di storage all-flash SolidFire durante la creazione del cluster.



=== Aggiornamenti del firmware del nodo di storage

Element 12,5 include aggiornamenti del firmware per i nodi storage. link:../concepts/concept_rn_relatedrn_element.html#storage-firmware["Scopri di più"].



=== Maggiore sicurezza

L'elemento 12.5 contiene la mitigazione che chiude l'esposizione del software Element alla vulnerabilità di Apache Log4j. I cluster di storage NetApp SolidFire con la funzione volumi virtuali (VVol) attivata sono esposti alla vulnerabilità di Apache Log4j. Per informazioni sulla soluzione alternativa per la vulnerabilità di Apache Log4j nel software NetApp Element, vedere {url-peak}[articolo KB^].

Se si esegue Element 11.x, 12.0 o 12.2 o se il cluster di storage si trova già all'elemento 12.3 o 12.3.1 con la funzione VVols attivata, è necessario eseguire l'aggiornamento alla versione 12.5.

L'elemento 12.5 include inoltre oltre 120 correzioni per le vulnerabilità di sicurezza CVE.



== Trova ulteriori informazioni

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["Note sulla versione di NetApp Hybrid Cloud Control and Management Services"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]
* http://docs.netapp.com/sfe-122/index.jsp["Centro di documentazione software SolidFire ed Element per le versioni precedenti"^]
* https://docs.netapp.com/us-en/hci/index.html["Documentazione NetApp HCI"^]
* link:../hardware/fw_storage_nodes.html["Versioni del firmware dello storage supportate per i nodi di storage SolidFire"]

