---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: 'La gestione esterna delle chiavi (EKM) fornisce la gestione sicura delle chiavi di autenticazione (AK) insieme a un server esterno fuori cluster delle chiavi (EKS). Gli AKS vengono utilizzati per bloccare e sbloccare i dischi con crittografia automatica (SED) quando la crittografia a riposo è attivata sul cluster.' 
---
= Inizia a utilizzare la gestione esterna delle chiavi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EKM (External Key Management) offre una gestione sicura delle chiavi di autenticazione (AK) insieme a un server esterno delle chiavi (EKS) off-cluster. Gli AKS vengono utilizzati per bloccare e sbloccare i dischi con crittografia automatica (SED) quando link:../concepts/concept_solidfire_concepts_security.html["crittografia a riposo"] è attivato sul cluster. EKS fornisce generazione e storage sicuri di AKS. Il cluster utilizza il protocollo KMIP (Key Management Interoperability Protocol), un protocollo standard definito DA OASIS, per comunicare con EKS.

* link:task_system_manage_key_set_up_external_key_management.html["Configurare la gestione esterna"]
* link:task_system_manage_rekey_software_ear_master_key.html["Ridigita la chiave master di crittografia software a riposo"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["Ripristino di chiavi di autenticazione inaccessibili o non valide"]
* link:concept_system_manage_key_external_key_management_api_commands.html["Comandi API esterni per la gestione delle chiavi"]


[discrete]
== Trova ulteriori informazioni

* link:../api/reference_element_api_createcluster.html["API CreateCluster che può essere utilizzata per attivare la crittografia software a riposo"]
* https://www.netapp.com/data-storage/solidfire/documentation/["Pagina delle risorse NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti SolidFire ed Element di NetApp"^]

