---
permalink: storage/concept_data_manage_vol_access_group_work_with_volume_access_groups_and_initiators.html 
sidebar: sidebar 
keywords: volume access groups, initiators, working with, chap, fc, iscsi 
summary: 'È possibile utilizzare gli iniziatori iSCSI o gli iniziatori Fibre Channel per accedere ai volumi definiti all"interno dei gruppi di accesso ai volumi.' 
---
= Lavorare con gli iniziatori e i gruppi di accesso ai volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare gli iniziatori iSCSI o gli iniziatori Fibre Channel per accedere ai volumi definiti all'interno dei gruppi di accesso ai volumi.

È possibile creare gruppi di accesso mappando gli IQN degli iniziatori iSCSI o le WWPN Fibre Channel in un insieme di volumi. Ogni IQN aggiunto a un gruppo di accesso può accedere a ciascun volume del gruppo senza richiedere l'autenticazione CHAP.

Esistono due tipi di metodi di autenticazione CHAP:

* Autenticazione CHAP a livello di account: È possibile assegnare l'autenticazione CHAP per l'account.
* Autenticazione CHAP a livello di iniziatore: È possibile assegnare una destinazione CHAP univoca e segreti per iniziatori specifici senza essere associati a un singolo CHAP in un singolo account. Questa autenticazione CHAP a livello di iniziatore sostituisce le credenziali a livello di account.


Facoltativamente, con il CHAP per-initiator, è possibile applicare l'autorizzazione per initiator e l'autenticazione CHAP per-initiator. Queste opzioni possono essere definite in base all'iniziatore e un gruppo di accesso può contenere una combinazione di iniziatori con diverse opzioni.

Ogni WWPN aggiunto a un gruppo di accesso abilita l'accesso di rete Fibre Channel ai volumi del gruppo di accesso.


NOTE: I gruppi di accesso ai volumi hanno i seguenti limiti:

* In un gruppo di accesso è consentito un massimo di 64 IQN o WWPN.
* Un gruppo di accesso può essere costituito da un massimo di 2000 volumi.
* Un IQN o WWPN può appartenere a un solo gruppo di accesso.
* Un singolo volume può appartenere a un massimo di quattro gruppi di accesso.




== Trova ulteriori informazioni

* xref:task_data_manage_vol_access_group_create_a_volume_access_group.adoc[Creare un gruppo di accesso al volume]
* xref:task_data_manage_vol_access_group_add_volumes.adoc[Aggiungere volumi a un gruppo di accesso]
* xref:task_data_manage_vol_access_group_remove_volumes.adoc[Rimuovere i volumi da un gruppo di accesso]
* xref:task_data_manage_vol_access_group_create_an_initiator.adoc[Creare un iniziatore]
* xref:task_data_manage_vol_access_group_edit_an_initiator.adoc[Modificare un iniziatore]
* xref:task_data_manage_vol_access_group_add_a_single_initiator.adoc[Aggiungere un singolo iniziatore a un gruppo di accesso al volume]
* xref:task_data_manage_vol_access_group_add_multiple_initiators.adoc[Aggiungere più iniziatori a un gruppo di accesso al volume]
* xref:task_data_manage_vol_access_group_remove_initiators_from_an_access_group.adoc[Rimuovere gli iniziatori da un gruppo di accesso]
* xref:task_data_manage_vol_access_group_delete.adoc[Eliminare un gruppo di accesso]
* xref:task_data_manage_vol_access_group_delete_an_initiator.adoc[Eliminare un iniziatore]

