---
permalink: storage/concept_snapmirror_labels.html 
sidebar: sidebar 
keywords: labels, snapmirror, retention rules 
summary: 'Un"etichetta SnapMirror funge da indicatore per il trasferimento di uno snapshot specificato in base alle regole di conservazione della relazione.' 
---
= Etichette SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un'etichetta SnapMirror funge da indicatore per il trasferimento di uno snapshot specificato in base alle regole di conservazione della relazione.

L'applicazione di un'etichetta a uno snapshot lo contrassegna come destinazione per la replica di SnapMirror. Il ruolo della relazione è quello di applicare le regole al momento del trasferimento dei dati selezionando lo snapshot etichettato corrispondente, copiandolo nel volume di destinazione e garantendo che venga conservato il numero corretto di copie. Si riferisce alla policy per determinare il numero di conservazione e il periodo di conservazione. Il criterio può avere un numero qualsiasi di regole e ogni regola ha un'etichetta univoca. Questa etichetta funge da collegamento tra lo snapshot e la regola di conservazione.

È l'etichetta SnapMirror che indica quale regola applicare per lo snapshot, lo snapshot di gruppo o la pianificazione selezionati.
