---
permalink: storage/concept_system_manage_nodes_node_versioning_and_compatibility.html 
sidebar: sidebar 
keywords: compatibility, node version, clusters, software version, compatible versions, major, minor, micro 
summary: 'La compatibilità dei nodi si basa sulla versione software di Element installata su un nodo. I cluster di storage basati su software Element imbasano automaticamente un"immagine di un nodo alla versione software Element sul cluster se il nodo e il cluster non sono compatibili.' 
---
= Versione e compatibilità dei nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La compatibilità dei nodi si basa sulla versione software di Element installata su un nodo. I cluster di storage basati su software Element imbasano automaticamente un'immagine di un nodo alla versione software Element sul cluster se il nodo e il cluster non sono compatibili.

Il seguente elenco descrive i livelli di importanza delle release software che compongono il numero di versione del software Element:

* *Maggiore*
+
Il primo numero indica una versione software. Un nodo con un numero di componente principale non può essere aggiunto a un cluster contenente nodi con un numero di patch principale diverso, né può essere creato un cluster con nodi con versioni principali miste.

* *Minore*
+
Il secondo numero indica funzionalità software più piccole o miglioramenti alle funzionalità software esistenti che sono state aggiunte a una release principale. Questo componente viene incrementato all'interno di un componente di versione principale per indicare che questa release incrementale non è compatibile con altre release incrementali di software elemento con un componente minore diverso. Ad esempio, 11.0 non è compatibile con 11.1 e 11.1 non è compatibile con 11.2.

* *Micro*
+
Il terzo numero indica una patch compatibile (release incrementale) con la versione software dell'elemento rappresentata dai componenti major.minor. Ad esempio, 11.0.1 è compatibile con 11.0 e 11.0.2 con 11.0.3.



I numeri di versione principali e secondari devono corrispondere per la compatibilità. I micro numeri non devono corrispondere per la compatibilità.
