---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: 'Il networking virtuale nello storage SolidFire consente di connettere il traffico tra più client su reti logiche separate a un cluster. Le connessioni al cluster vengono separate nello stack di rete attraverso l"utilizzo del tagging VLAN.' 
---
= Gestire le reti virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il networking virtuale nello storage SolidFire consente di connettere il traffico tra più client su reti logiche separate a un cluster. Le connessioni al cluster vengono separate nello stack di rete attraverso l'utilizzo del tagging VLAN.



== Trova ulteriori informazioni

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Aggiungere una rete virtuale]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Abilitare il routing e l'inoltro virtuale]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Modificare una rete virtuale]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[Modificare le VLAN VRF]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Eliminare una rete virtuale]

