---
permalink: storage/concept-element-replication-create-custom-replication-policy.html 
sidebar: sidebar 
keywords: ontap, cli, create, custom, replication, policy, relationship, 
summary: È possibile creare un criterio di replica personalizzato se il criterio predefinito per una relazione non è adatto. 
---
= Creare un criterio di replica personalizzato
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare un criterio predefinito o personalizzato quando si crea una relazione di replica. Per un criterio di replica unificato personalizzato, è necessario definire una o più _regole_ che determinano quali copie snapshot vengono trasferite durante l'inizializzazione e l'aggiornamento.

È possibile creare un criterio di replica personalizzato se il criterio predefinito per una relazione non è adatto. Ad esempio, è possibile comprimere i dati in un trasferimento di rete o modificare il numero di tentativi eseguiti da SnapMirror per trasferire le copie snapshot.

.A proposito di questa attività
Il _tipo di policy_ del criterio di replica determina il tipo di relazione che supporta. La tabella seguente mostra i tipi di policy disponibili.

[cols="2*"]
|===


| Tipo di policy | Tipo di relazione 


 a| 
mirror asincrono
 a| 
Dr. SnapMirror



 a| 
vault mirror
 a| 
Replica unificata

|===
.Fase
. Creare un criterio di replica personalizzato:
+
`snapmirror policy create -vserver _SVM_ -policy policy -type async-mirror|mirror-vault -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
A partire da ONTAP 9.5, è possibile specificare la pianificazione per la creazione di una pianificazione di copie snapshot comune per le relazioni di sincronizzazione SnapMirror utilizzando il `-common-snapshot-schedule` parametro. Per impostazione predefinita, la pianificazione delle copie Snapshot comune per le relazioni sincrone SnapMirror è un'ora. Puoi specificare un valore compreso tra 30 minuti e due ore per la pianificazione della copia Snapshot per le relazioni di sincronizzazione di SnapMirror.

+
Nell'esempio seguente viene creato un criterio di replica personalizzato per il DR SnapMirror che consente la compressione di rete per i trasferimenti di dati:

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
Nell'esempio seguente viene creata una policy di replica personalizzata per la replica unificata:

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


.Al termine
Per i tipi di criteri "speculare-vault", è necessario definire regole che determinano quali copie di snapshot vengono trasferite durante l'inizializzazione e l'aggiornamento.

Utilizzare `snapmirror policy show` il comando per verificare che il criterio SnapMirror sia stato creato. Per la sintassi completa dei comandi, vedere la pagina man.
