---
permalink: storage/concept_system_manage_system_management.html 
sidebar: sidebar 
keywords: element, cluster, fips, cluster, multi-factor authentication, authentication 
summary: 'È possibile gestire il sistema nell"interfaccia utente di Element. Ciò include l"abilitazione dell"autenticazione a più fattori, la gestione delle impostazioni del cluster, il supporto degli standard FIPS (Federal Information Processing Standards) e l"utilizzo della gestione esterna delle chiavi.' 
---
= Gestire il sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire il sistema nell'interfaccia utente di Element. Ciò include l'abilitazione dell'autenticazione a più fattori, la gestione delle impostazioni del cluster, il supporto degli standard FIPS (Federal Information Processing Standards) e l'utilizzo della gestione esterna delle chiavi.

* link:task_system_manage_mfa_set_up_multi_factor_authentication.html["Abilitare l'autenticazione a più fattori"]
* link:task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["Configurare le impostazioni del cluster"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["Creare un cluster che supporti i dischi FIPS"]
* link:concept_system_manage_key_get_started_with_external_key_management.html["Inizia a utilizzare la gestione esterna delle chiavi"]




== Per ulteriori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]

