---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: Le crittografie SSL sono algoritmi di crittografia utilizzati dagli host per stabilire una comunicazione sicura. Esistono cifrari standard supportati dal software Element e non standard quando è attivata la modalità FIPS 140-2. 
---
= Crittografie SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le crittografie SSL sono algoritmi di crittografia utilizzati dagli host per stabilire una comunicazione sicura. Esistono cifrari standard supportati dal software Element e non standard quando è attivata la modalità FIPS 140-2.

I seguenti elenchi forniscono le crittografie standard SSL (Secure Socket Layer) supportate dal software Element e le crittografie SSL supportate quando la modalità FIPS 140-2 è attivata:

* *FIPS 140-2 disattivato*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A.

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C.

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A.

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_IDEA_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_RC4_128_MD5 (RSA 2048) - C

+
TLS_RSA_WITH_RC4_128_SHA (RSA 2048) - C.

+
TLS_RSA_WITH_SEED_CBC_SHA (RSA 2048) - A.

* *FIPS 140-2 abilitato*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (DH 2048) - A.

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (DH 2048) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECT571R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECP256R1) - A.

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (SECT571R1) - A.

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (RSA 2048) - C.

+
TLS_RSA_WITH_AES_128_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (RSA 2048) - A.

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (RSA 2048) - A.





== Trova ulteriori informazioni

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Abilitare FIPS 140-2 per HTTPS sul cluster]
