---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: 'La pagina Volume Pairs (coppie di volumi) della scheda Data Protection (protezione dati) fornisce questi messaggi dopo l"accoppiamento dei volumi. Questi messaggi possono essere visualizzati sulle estremità di origine e destinazione della coppia (se non diversamente indicato) nella vista elenco Replica volumi.' 
---
= Avvisi di associazione del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Thevolume Pairs della scheda Data Protection (protezione dati) fornisce questi messaggi dopo l'accoppiamento dei volumi. Questi messaggi possono essere visualizzati sia sull'estremità di origine che su quella di destinazione della coppia (se non diversamente indicato) nella vista elenco Replica volumi.

* *PausedClusterFull*
+
Poiché il cluster di destinazione è pieno, la replica di origine e il trasferimento di dati in blocco non possono procedere. Il messaggio viene visualizzato solo sul lato di origine della coppia.

* *PausedExceedMaxSnapshotCount*
+
Il volume di destinazione dispone già del numero massimo di snapshot e non può replicare snapshot aggiuntivi.

* *PausedManual*
+
Il volume locale è stato messo in pausa manualmente. Prima di riprendere la replica, è necessario che la replica sia sospesa.

* *PausedManualRemote*
+
Il volume remoto è in modalità di pausa manuale. È richiesto l'intervento manuale per riattivare il volume remoto prima che la replica venga ripresa.

* *PausedMisconfigured*
+
In attesa di un'origine e di una destinazione attive. È richiesto l'intervento manuale per riprendere la replica.

* *QoS Paused*
+
QoS di destinazione non è riuscito a sostenere i/o in entrata. La replica riprende automaticamente. Il messaggio viene visualizzato solo sul lato di origine della coppia.

* *PausedSlowLink*
+
Collegamento lento rilevato e replica interrotta. La replica riprende automaticamente. Il messaggio viene visualizzato solo sul lato di origine della coppia.

* *PausedVolumeSizeMismatch*
+
Il volume di destinazione non ha le stesse dimensioni del volume di origine.

* *PausedXCopy*
+
Viene inviato un comando SCSI XCOPY a un volume di origine. Il comando deve essere completato prima che la replica possa riprendere. Il messaggio viene visualizzato solo sul lato di origine della coppia.

* *StoppedMisconfigured*
+
È stato rilevato un errore di configurazione permanente. Il volume remoto è stato disaccoppiato o disaccoppiato. Non è possibile eseguire alcuna azione correttiva; è necessario stabilire una nuova associazione.


