---
permalink: storage/task_data_protection_edit_snapshot_retention.html 
sidebar: sidebar 
keywords: snapshot retention, edit, set a retention period, edit retention period 
summary: 'È possibile modificare il periodo di conservazione di uno snapshot per controllare quando o se il sistema elimina gli snapshot. Il periodo di conservazione specificato inizia quando si inserisce il nuovo intervallo. Quando si imposta un periodo di conservazione, è possibile selezionare un periodo che inizia all"ora corrente (la conservazione non viene calcolata dall"ora di creazione dello snapshot). È possibile specificare intervalli in minuti, ore e giorni.' 
---
= Modifica la conservazione delle snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare il periodo di conservazione di uno snapshot per controllare quando o se il sistema elimina gli snapshot. Il periodo di conservazione specificato inizia quando si inserisce il nuovo intervallo. Quando si imposta un periodo di conservazione, è possibile selezionare un periodo che inizia all'ora corrente (la conservazione non viene calcolata dall'ora di creazione dello snapshot). È possibile specificare intervalli in minuti, ore e giorni.

.Fasi
. Fare clic su *Data Protection* > *Snapshot*.
. Fare clic sull'icona *Actions* per l'istantanea che si desidera modificare.
. Nel menu visualizzato, fare clic su *Edit* (Modifica).
. *Opzionale:* selezionare la casella di controllo**Includi snapshot nella replica quando accoppiato** per assicurarsi che lo snapshot venga acquisito nella replica quando il volume padre viene associato.
. *Opzionale:* selezionare un'opzione di conservazione per lo snapshot:
+
** Fare clic su *Keep Forever* per conservare l'istantanea sul sistema a tempo indeterminato.
** Fare clic su *Set retention period* (Imposta periodo di conservazione) e utilizzare le caselle di selezione della data per selezionare il periodo di tempo in cui il sistema conserva lo snapshot.


. Fare clic su *Save Changes* (Salva modifiche).

