---
permalink: storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html 
sidebar: sidebar 
keywords: enable, disable, encryption at rest, cluster, sed, hardware-based, encryption settings, software-based 
summary: Con i cluster SolidFire, è possibile crittografare tutti i dati memorizzati nel cluster utilizzando la crittografia basata su software o hardware a riposo. 
---
= Attivare e disattivare la crittografia a riposo per un cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con i cluster SolidFire, è possibile crittografare tutti i dati inattivi memorizzati sui dischi del cluster. È possibile abilitare la protezione a livello di cluster dei dischi con crittografia automatica (SED) utilizzando entrambi link:../concepts/concept_solidfire_concepts_security.html["crittografia basata su hardware o software a riposo"].

È possibile attivare la crittografia hardware a riposo utilizzando l'interfaccia utente o l'API Element. L'attivazione della funzione di crittografia hardware a riposo non influisce sulle prestazioni o sull'efficienza del cluster. È possibile attivare la crittografia software a riposo utilizzando solo l'API Element.

La crittografia basata su hardware a riposo non è attivata per impostazione predefinita durante la creazione del cluster e può essere attivata e disattivata dall'interfaccia utente di Element.


WARNING: Per i cluster di storage all-flash SolidFire, la crittografia software a riposo deve essere attivata durante la creazione del cluster e non può essere disattivata dopo la creazione del cluster.

.Di cosa hai bisogno
* Si dispone dei privilegi di amministratore del cluster per attivare o modificare le impostazioni di crittografia.
* Per la crittografia basata su hardware a riposo, è stato garantito che il cluster sia in buono stato prima di modificare le impostazioni di crittografia.
* Se si disattiva la crittografia, due nodi devono partecipare a un cluster per accedere alla chiave e disattivare la crittografia su un disco.




== Controllare la crittografia nello stato di riposo

Per visualizzare lo stato corrente della crittografia a riposo e/o della crittografia software a riposo nel cluster, utilizzare link:../api/reference_element_api_getclusterinfo.html["GetClusterInfo"^] metodo. È possibile utilizzare link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["GetSoftwareEncryptionAtRestInfo"^] metodo per ottenere informazioni utilizzate dal cluster per crittografare i dati inattivi.


NOTE: La dashboard dell'interfaccia utente del software Element all'indirizzo `https://<MVIP>/` attualmente mostra solo la crittografia in stato di riposo per la crittografia basata su hardware.

.Opzioni
* <<Abilitare la crittografia basata su hardware a riposo>>
* <<Abilitare la crittografia basata su software a riposo>>
* <<Disattiva la crittografia basata su hardware a riposo>>




== Abilitare la crittografia basata su hardware a riposo


NOTE: Per attivare la crittografia a riposo utilizzando una configurazione di gestione delle chiavi esterna, è necessario attivare la crittografia a riposo tramite link:../api/reference_element_api_enableencryptionatrest.html["API"]. L'abilitazione mediante il pulsante Element UI esistente tornerà a utilizzare chiavi generate internamente.

. Dall'interfaccia utente di Element, selezionare *Cluster* > *Settings*.
. Selezionare *Enable Encryption at REST (attiva crittografia a riposo)*.




== Abilitare la crittografia basata su software a riposo


NOTE: La crittografia software a riposo non può essere disattivata dopo che è stata attivata sul cluster.

. Durante la creazione del cluster, eseguire link:../api/reference_element_api_createcluster.html["creare il metodo del cluster"] con `enableSoftwareEncryptionAtRest` impostare su `true`.




== Disattiva la crittografia basata su hardware a riposo

. Dall'interfaccia utente di Element, selezionare *Cluster* > *Settings*.
. Selezionare *Disattiva crittografia a riposo*.


[discrete]
== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti SolidFire ed Element di NetApp"^]

