---
permalink: storage/task_data_protection_restore_volume_from_backup_on_solidfire.html 
sidebar: sidebar 
keywords: volume restore, solidfire storage cluster 
summary: È possibile ripristinare un volume da un backup su un cluster di storage SolidFire. 
---
= Ripristinare un volume dal backup su un cluster di storage SolidFire
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare un volume da un backup su un cluster di storage SolidFire.

Quando si esegue il backup o il ripristino da un cluster all'altro, il sistema genera una chiave da utilizzare come autenticazione tra i cluster. Questa chiave di scrittura del volume in blocco consente al cluster di origine di autenticarsi con il cluster di destinazione, fornendo un livello di sicurezza durante la scrittura nel volume di destinazione. Nell'ambito del processo di backup o ripristino, è necessario generare una chiave di scrittura del volume in blocco dal volume di destinazione prima di avviare l'operazione.

. Nel cluster di destinazione, fare clic su *Management* > *Volumes*.
. Fare clic sull'icona Actions (azioni) per il volume che si desidera ripristinare.
. Nel menu visualizzato, fare clic su *Restore from* (Ripristina da).
. Nella finestra di dialogo *Ripristino integrato*, in *Ripristina da*, selezionare *SolidFire*.
. Selezionare l'opzione corrispondente al backup in *formato dati*:
+
** *Nativo*: Formato compresso leggibile solo dai sistemi storage SolidFire.
** *Non compresso*: Un formato non compresso compatibile con altri sistemi.


. Fare clic su *generate Key* (genera chiave).
. Copiare le informazioni *Volume Write Key* negli Appunti.
. Nel cluster di origine, fare clic su *Management* > *Volumes*.
. Fare clic sull'icona Actions (azioni) del volume che si desidera utilizzare per il ripristino.
. Nel menu visualizzato, fare clic su *Backup in*.
. Nella finestra di dialogo *Backup integrato*, selezionare *SolidFire* in *Backup su*.
. Selezionare l'opzione corrispondente al backup in *formato dati*.
. Inserire l'indirizzo IP virtuale di gestione del cluster del volume di destinazione nel campo *Remote Cluster MVIP*.
. Inserire il nome utente del cluster remoto nel campo *Remote Cluster Username* (Nome utente cluster remoto).
. Inserire la password del cluster remoto nel campo *Remote Cluster Password*.
. Incollare la chiave dagli appunti nel campo *Volume Write Key*.
. Fare clic su *Avvia lettura*.

