---
permalink: storage/task_data_protection_create_a_volume_snapshot.html 
sidebar: sidebar 
keywords: volume snapshot, create, active volume, preserve volume 
summary: 'È possibile creare uno snapshot di un volume attivo per conservare l"immagine del volume in qualsiasi momento. È possibile creare fino a 32 snapshot per un singolo volume.' 
---
= Creare un'istantanea del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare uno snapshot di un volume attivo per conservare l'immagine del volume in qualsiasi momento. È possibile creare fino a 32 snapshot per un singolo volume.

. Fare clic su *Management* > *Volumes*.
. Fare clic sull'icona *Actions* del volume che si desidera utilizzare per lo snapshot.
. Nel menu visualizzato, selezionare *Snapshot*.
. Nella finestra di dialogo *Create Snapshot of Volume* (Crea snapshot del volume), inserire il nuovo nome dello snapshot.
. *Opzionale:* selezionare la casella di controllo *Includi snapshot nella replica quando accoppiato* per assicurarsi che lo snapshot venga acquisito in replica quando il volume padre viene associato.
. Per impostare la conservazione dello snapshot, selezionare una delle seguenti opzioni:
+
** Fare clic su *Keep Forever* per conservare l'istantanea sul sistema a tempo indeterminato.
** Fare clic su *Set retention period* (Imposta periodo di conservazione) e utilizzare le caselle di selezione della data per scegliere il periodo di tempo in cui il sistema conserva lo snapshot.


. Per eseguire una singola istantanea, attenersi alla seguente procedura:
+
.. Fare clic su *scatta istantanea ora*.
.. Fare clic su**Create Snapshot** (Crea istantanea).


. Per pianificare l'esecuzione dello snapshot in un momento successivo, attenersi alla seguente procedura:
+
.. Fare clic su *Crea pianificazione snapshot*.
.. Immettere un *nuovo nome pianificazione*.
.. Scegliere un *tipo di pianificazione* dall'elenco.
.. *Opzionale:* selezionare la casella di controllo *Pianificazione ricorrente* per ripetere periodicamente lo snapshot pianificato.
.. Fare clic su *Crea pianificazione*.






== Trova ulteriori informazioni

xref:task_data_protection_schedule_a_snapshot_task.adoc[Pianifica un'istantanea]
