---
permalink: storage/task-element-replication-reactivate-original-source-volume.html 
sidebar: sidebar 
keywords: ontap,cli, reactivate, original, source, volume 
summary: È possibile ristabilire la relazione di protezione dei dati originale tra i volumi di origine e di destinazione quando non è più necessario fornire dati dalla destinazione. 
---
= Riattivare il volume di origine originale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ristabilire la relazione di protezione dei dati originale tra i volumi di origine e di destinazione quando non è più necessario fornire dati dalla destinazione.

.A proposito di questa attività
La procedura riportata di seguito presuppone che la linea di base nel volume di origine originale sia intatta. Se la linea di base non è intatta, è necessario creare e inizializzare la relazione tra il volume da cui si stanno fornendo i dati e il volume di origine originale prima di eseguire la procedura.

È necessario specificare il percorso di origine dell'elemento nel formato `<hostip:>/lun/<name>`, dove "`lun'" è la stringa effettiva "`lun'" ed `name` è il nome del volume dell'elemento.

A partire da ONTAP 9.4, le copie snapshot di un LUN creato durante l'erogazione di dati dalla destinazione ONTAP vengono replicate automaticamente quando l'origine dell'elemento viene riattivata.

Le regole di replica sono le seguenti:

* Sono supportati solo i LUN iSCSI.
* Non è possibile replicare più di un LUN da un volume ONTAP a un volume Element.
* Non è possibile replicare un LUN da un volume ONTAP a più volumi di elementi.


.Fasi
. Eliminare la relazione di protezione dei dati originale:
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene eliminata la relazione tra il volume di origine originale, `0005` all'indirizzo IP 10,0.0,11, e il volume da cui vengono distribuiti i dati, `volA_dst` il `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. Invertire la relazione di protezione dei dati originale:
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Sebbene la risincronizzazione non richieda un trasferimento di riferimento, può richiedere molto tempo. È possibile eseguire la risincronizzazione in ore non di punta.

+
Nell'esempio riportato di seguito viene invertita la relazione tra il volume di origine originale, `0005` all'indirizzo IP 10,0.0,11, e il volume da cui vengono forniti i dati, `volA_dst` il `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Aggiornare la relazione inversa:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Il comando non riesce se una copia snapshot comune non esiste nell'origine e nella destinazione. Utilizzare `snapmirror initialize` per reinizializzare la relazione.

====
+
Nell'esempio seguente viene aggiornata la relazione tra il volume da cui vengono distribuiti i dati, `volA_dst` il `svm_backup` e il volume di origine originale, `0005` all'indirizzo IP 10,0.0,11:

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrestare i trasferimenti pianificati per la relazione invertita:
+
`snapmirror quiesce -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente vengono interrotti i trasferimenti pianificati tra il volume da cui vengono distribuiti i dati, `volA_dst` il `svm_backup` e il volume di origine originale `0005` all'indirizzo IP 10,0.0,11:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Arrestare i trasferimenti in corso per la relazione invertita:
+
`snapmirror abort -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente vengono interrotti i trasferimenti in corso tra il volume da cui vengono distribuiti i dati, `volA_dst` il `svm_backup` e il volume di origine originale `0005` all'indirizzo IP 10,0.0,11:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Interrompere la relazione inversa:
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene interrotta la relazione tra il volume da cui vengono distribuiti i dati, `volA_dst` il `svm_backup` e il volume di origine originale `0005` all'indirizzo IP 10,0.0,11:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Eliminare la relazione di protezione dei dati invertita:
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene eliminata la relazione invertita tra il volume di origine, `0005` all'indirizzo IP 10,0.0,11, e il volume da cui vengono distribuiti i dati, `volA_dst` il `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Ristabilire la relazione di protezione dei dati originale:
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene ristabilita la relazione tra il volume di origine originale, `0005` all'indirizzo IP 10,0.0,11, e il volume di destinazione originale, `volA_dst` ON `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.Al termine
Utilizzare il `snapmirror show` comando per verificare che la relazione SnapMirror sia stata creata. Per la sintassi completa dei comandi, vedere la pagina man.
