---
permalink: storage/task_data_protection_clone_a_volume_from_a_snapshot.html 
sidebar: sidebar 
keywords: clone volume from snapshot, volume snapshots, clone 
summary: È possibile creare un nuovo volume da uno snapshot di un volume. In questo modo, il sistema utilizza le informazioni di snapshot per clonare un nuovo volume utilizzando i dati contenuti nel volume al momento della creazione dello snapshot. Questo processo memorizza le informazioni relative ad altri snapshot del volume nel volume appena creato. 
---
= Clonare un volume da uno snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un nuovo volume da uno snapshot di un volume. In questo modo, il sistema utilizza le informazioni di snapshot per clonare un nuovo volume utilizzando i dati contenuti nel volume al momento della creazione dello snapshot. Questo processo memorizza le informazioni relative ad altri snapshot del volume nel volume appena creato.

. Fare clic su *Data Protection* > *Snapshot*.
. Fare clic sull'icona *Actions* per lo snapshot che si desidera utilizzare per il clone del volume.
. Nel menu visualizzato, fare clic su *Clone Volume from Snapshot* (Clona volume da snapshot).
. Inserire un *Nome volume* nella finestra di dialogo *Clone Volume from Snapshot* (Copia volume da snapshot).
. Selezionare *Total Size* (dimensione totale) e le unità di misura per il nuovo volume.
. Selezionare un tipo *Access* per il volume.
. Selezionare un *account* dall'elenco da associare al nuovo volume.
. Fare clic su *Avvia clonazione*.

