---
permalink: storage/task_data_manage_volumes_work_with_volumes_task.html 
sidebar: sidebar 
keywords: volumes, work, storage, iscsi, fc, cluster data management, overview of functions 
summary: 'Il sistema SolidFire esegue il provisioning dello storage utilizzando i volumi. I volumi sono dispositivi a blocchi a cui si accede in rete dai client iSCSI o Fibre Channel. Dalla pagina Volumes (volumi) della scheda Management (Gestione), è possibile creare, modificare, clonare ed eliminare volumi su un nodo. È inoltre possibile visualizzare le statistiche relative alla larghezza di banda del volume e all"utilizzo di i/O.' 
---
= Lavorare con i volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema SolidFire esegue il provisioning dello storage utilizzando i volumi. I volumi sono dispositivi a blocchi a cui si accede in rete dai client iSCSI o Fibre Channel. Dalla pagina Volumes (volumi) della scheda Management (Gestione), è possibile creare, modificare, clonare ed eliminare volumi su un nodo. È inoltre possibile visualizzare le statistiche relative alla larghezza di banda del volume e all'utilizzo di i/O.



== Trova ulteriori informazioni

* link:concept_data_manage_volumes_quality_of_service_policies.html["Gestire le policy di qualità del servizio"]
* link:task_data_manage_volumes.html#create-a-volume["Creare un volume"]
* link:task_data_manage_volumes.html#view-volume-details["Visualizza i dettagli delle performance dei singoli volumi"]
* link:task_data_manage_volumes.html#edit-active-volumes["Modificare i volumi attivi"]
* link:task_data_manage_volumes.html#delete-a-volume["Eliminare un volume"]
* link:task_data_manage_volumes.html#restore-a-deleted-volume["Ripristinare un volume cancellato"]
* link:task_data_manage_volumes.html#purge-a-volume["Eliminare un volume"]
* link:task_data_manage_volumes.html#clone-a-volume["Clonare un volume"]
* link:task_data_manage_volumes_assign_luns_to_fibre_channel_volumes.html["Assegnare LUN a volumi Fibre Channel"]
* link:task_data_manage_volumes_apply_a_qos_policy.html["Applicare una policy di QoS ai volumi"]
* link:task_data_manage_volumes_remove_a_qos_policy_association_of_a_volume.html["Rimuovere l'associazione dei criteri QoS di un volume"]

