---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: 'È possibile aggiungere più iniziatori a un gruppo di accesso a un volume esistente per consentire l"accesso ai volumi nel gruppo di accesso a un volume con o senza richiedere l"autenticazione CHAP.' 
---
= Aggiungere più iniziatori a un gruppo di accesso al volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere più iniziatori a un gruppo di accesso a un volume esistente per consentire l'accesso ai volumi nel gruppo di accesso a un volume con o senza richiedere l'autenticazione CHAP.

Quando si aggiungono gli iniziatori a un gruppo di accesso al volume, gli iniziatori hanno accesso a tutti i volumi in quel gruppo di accesso al volume.


TIP: È possibile trovare l'iniziatore per ciascun volume facendo clic sull'icona Actions (azioni), quindi su *View Details* (Visualizza dettagli) per il volume nell'elenco Active Volumes (volumi attivi).

È possibile aggiungere più iniziatori a un gruppo di accesso a un volume esistente per consentire l'accesso ai volumi e assegnare credenziali CHAP univoche per ciascun iniziatore all'interno di tale gruppo di accesso a un volume. Questa opzione consente di applicare questa opzione ai gruppi di accesso ai volumi già esistenti.

È possibile assegnare attributi CHAP basati su initator utilizzando una chiamata API. Per aggiungere un nome account CHAP e le credenziali per ogni iniziatore, è necessario utilizzare la chiamata API ModifyInitator per rimuovere e aggiungere gli attributi e l'accesso CHAP.

Per ulteriori informazioni, vedere link:../api/index.html["Gestire lo storage con l'API Element"].

.Fasi
. Fare clic su *Gestione* > *iniziatori*.
. Selezionare gli iniziatori che si desidera aggiungere a un gruppo di accesso.
. Fare clic sul pulsante *azioni in blocco*.
. Fare clic su *Add to Volume Access Group* (Aggiungi a gruppo di accesso volume).
. Nella finestra di dialogo Add to Volume Access Group (Aggiungi a gruppo di accesso al volume), selezionare un gruppo di accesso dall'elenco *Volume Access Group* (Gruppo di accesso al volume).
. Fare clic su *Aggiungi*.

