---
permalink: storage/task_snapmirror_enable_on_the_cluster.html 
sidebar: sidebar 
keywords: element, snapmirror, enable, cluster, ui, manually enable 
summary: 'È necessario abilitare manualmente la funzionalità SnapMirror a livello del cluster tramite l"interfaccia utente di NetApp Element. Il sistema viene fornito con la funzionalità SnapMirror disattivata per impostazione predefinita e non viene attivata automaticamente durante una nuova installazione o un aggiornamento. L"attivazione della funzione SnapMirror è un"attività di configurazione unica.' 
---
= Attivare SnapMirror sul cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario abilitare manualmente la funzionalità SnapMirror a livello del cluster tramite l'interfaccia utente di NetApp Element. Il sistema viene fornito con la funzionalità SnapMirror disattivata per impostazione predefinita e non viene attivata automaticamente durante una nuova installazione o un aggiornamento. L'attivazione della funzione SnapMirror è un'attività di configurazione unica.

SnapMirror può essere abilitato solo per i cluster che eseguono il software Element utilizzato insieme ai volumi su un sistema NetApp ONTAP. È necessario attivare la funzionalità SnapMirror solo se il cluster è connesso per l'utilizzo con i volumi NetApp ONTAP.

.Di cosa hai bisogno
Il cluster di storage deve eseguire il software NetApp Element.

.Fasi
. Fare clic su *Clusters* > *Impostazioni*.
. Individuare le impostazioni specifiche del cluster per SnapMirror.
. Fare clic su *Enable SnapMirror* (attiva SnapMirror
+

NOTE: L'attivazione della funzionalità SnapMirror modifica in modo permanente la configurazione del software Element. È possibile disattivare la funzione SnapMirror e ripristinare le impostazioni predefinite solo ripristinando l'immagine predefinita del cluster.

. Fare clic su *Sì* per confermare la modifica della configurazione di SnapMirror.

