---
permalink: storage/task-element-replication-define-rule-policy.html 
sidebar: sidebar 
keywords: ontap, cli, define, rule, policy 
summary: 'Per i criteri personalizzati con il tipo di criterio "mirror-vault", è necessario definire almeno una regola che determina quali copie snapshot vengono trasferite durante l"inizializzazione e l"aggiornamento. È inoltre possibile definire le regole per i criteri di default con il tipo di policy "mirror-vault".' 
---
= Definire una regola per un criterio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per i criteri personalizzati con il tipo di criterio "mirror-vault", è necessario definire almeno una regola che determina quali copie di snapshot vengono trasferite durante l'inizializzazione e l'aggiornamento. È inoltre possibile definire le regole per i criteri di default con il tipo di policy "`mirror-vault`".

.A proposito di questa attività
Ogni criterio con il tipo di criterio "specing-vault" deve avere una regola che specifica quali copie di snapshot replicare. La regola "`bimestrale'', ad esempio, indica che devono essere replicate solo le copie snapshot assegnate all'etichetta SnapMirror "`bimestrale'". L'etichetta SnapMirror viene assegnata quando si configurano le copie delle istantanee degli elementi.

Ogni tipo di policy è associato a una o più regole definite dal sistema. Queste regole vengono assegnate automaticamente a un criterio quando si specifica il relativo tipo di criterio. La tabella seguente mostra le regole definite dal sistema.

|===


| Regola definita dal sistema | Utilizzato nei tipi di policy | Risultato 


 a| 
sm_created
 a| 
mirror asincrono, vault mirror
 a| 
Una copia snapshot creata da SnapMirror viene trasferita all'inizializzazione e all'aggiornamento.



 a| 
ogni giorno
 a| 
vault mirror
 a| 
Le nuove copie snapshot sulla sorgente con l'etichetta SnapMirror "daily" vengono trasferite all'inizializzazione e all'aggiornamento.



 a| 
settimanale
 a| 
vault mirror
 a| 
Le nuove copie snapshot sulla sorgente con l'etichetta SnapMirror "`settimanale'" vengono trasferite all'inizializzazione e all'aggiornamento.



 a| 
mensile
 a| 
vault mirror
 a| 
Le nuove copie snapshot sulla sorgente con l'etichetta SnapMirror "mensile" vengono trasferite all'inizializzazione e all'aggiornamento.

|===
È possibile specificare regole aggiuntive in base alle esigenze, per i criteri predefiniti o personalizzati. Ad esempio:

* Per il criterio predefinito `MirrorAndVault`, è possibile creare una regola denominata "`bimestrale'" per far corrispondere le copie dell'istantanea sull'origine con l'etichetta SnapMirror "`bimestrale'".
* Per un criterio personalizzato con il tipo di criterio "speculare-vault", è possibile creare una regola chiamata "`bi-settimanale'" per far corrispondere le copie snapshot sull'origine con l'etichetta SnapMirror "`bi-settimanale'".


.Fase
. Definire una regola per un criterio:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene aggiunta una regola con l'etichetta SnapMirror `bi-monthly` al criterio predefinito `MirrorAndVault`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
Nell'esempio seguente viene aggiunta una regola con l'etichetta SnapMirror `bi-weekly` al criterio personalizzato `my_snapvault`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
Nell'esempio seguente viene aggiunta una regola con l'etichetta SnapMirror `app_consistent` al criterio personalizzato `Sync`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
Potrai quindi replicare le copie Snapshot dal cluster di origine che corrispondono a questa etichetta SnapMirror:

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

