---
permalink: storage/task-element-replication-create-relationship-element-destination.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, replication, snapmirror 
summary: 'A partire da ONTAP 9.4, è possibile utilizzare SnapMirror per replicare le copie snapshot di un LUN creato su un"origine ONTAP di nuovo in una destinazione Element. È possibile che si stia utilizzando il LUN per migrare i dati da ONTAP a Element Software.' 
---
= Creare una relazione da un'origine ONTAP a una destinazione dell'elemento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.4, è possibile utilizzare SnapMirror per replicare le copie snapshot di un LUN creato su un'origine ONTAP di nuovo in una destinazione Element. È possibile che si stia utilizzando il LUN per migrare i dati da ONTAP a Element Software.

.Prima di iniziare
* Il nodo di destinazione dell'elemento deve essere stato reso accessibile a ONTAP.
* Il volume Element deve essere stato abilitato per la replica di SnapMirror.


.A proposito di questa attività
È necessario specificare il percorso di destinazione dell'elemento nel formato `<hostip:>/lun/<name>`, dove "`lun'" è la stringa fisica "`lun'" ed `name` è il nome del volume dell'elemento.

Le regole di replica sono le seguenti:

* La relazione di replica deve avere una policy di tipo "`async-mirror`".
+
È possibile utilizzare un criterio predefinito o personalizzato.

* Sono supportati solo i LUN iSCSI.
* Non è possibile replicare più di un LUN da un volume ONTAP a un volume Element.
* Non è possibile replicare un LUN da un volume ONTAP a più volumi di elementi.


.Fase
. Creare una relazione di replica da un'origine ONTAP a una destinazione dell'elemento:
+
`snapmirror create -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -type XDP -schedule schedule -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene creata una relazione DR SnapMirror utilizzando il criterio predefinito `MirrorLatest`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
Nell'esempio seguente viene creata una relazione DR SnapMirror utilizzando il criterio personalizzato `my_mirror`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


.Al termine
Utilizzare il `snapmirror show` comando per verificare che la relazione SnapMirror sia stata creata. Per la sintassi completa dei comandi, vedere la pagina man.
