---
permalink: storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html 
sidebar: sidebar 
keywords: fips, security, federal information processing standards, 140-2, cluster, create 
summary: 'La sicurezza sta diventando sempre più critica per l"implementazione di soluzioni in molti ambienti dei clienti. Gli standard FIPS (Federal Information Processing Standards) sono standard per la sicurezza e l"interoperabilità dei computer. La crittografia certificata FIPS 140-2 per i dati inattivi è un componente della soluzione di sicurezza globale.' 
---
= Prepara il cluster Element per la funzionalità delle unità FIPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sicurezza sta diventando sempre più critica per l'implementazione di soluzioni in molti ambienti dei clienti. Gli standard FIPS (Federal Information Processing Standards) sono standard per la sicurezza e l'interoperabilità dei computer. La crittografia certificata FIPS 140-2 per i dati inattivi è un componente della soluzione di sicurezza globale.

Per prepararsi all'attivazione della funzione dischi FIPS, evitare di combinare nodi in cui alcuni sono in grado di supportare dischi FIPS e altri no.

Un cluster è considerato conforme ai dischi FIPS in base alle seguenti condizioni:

* Tutti i dischi sono certificati come dischi FIPS.
* Tutti i nodi sono nodi di dischi FIPS.
* La crittografia a riposo (EAR) è attivata.
* La funzione dischi FIPS è attivata. Tutti i dischi e i nodi devono essere compatibili con FIPS e la crittografia a riposo deve essere attivata per abilitare la funzione disco FIPS.

