---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'È possibile modificare la password di amministratore predefinita di Intelligent Platform Management Interface (IPMI) non appena si dispone dell"accesso remoto IPMI al nodo. Questa operazione potrebbe essere utile se sono stati rilevati aggiornamenti per l"installazione.' 
---
= Modificare la password IPMI predefinita per i nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password di amministratore predefinita di Intelligent Platform Management Interface (IPMI) non appena si dispone dell'accesso remoto IPMI al nodo. Questa operazione potrebbe essere utile se sono stati rilevati aggiornamenti per l'installazione.

Per ulteriori informazioni sulla configurazione dell'accesso IPM per i nodi, vedere link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configurare IPMI per ciascun nodo"^].

È possibile modificare la password IPM per questi nodi:

* Nodi H410S
* H610S nodi




== Modificare la password IPMI predefinita per i nodi H410S

È necessario modificare la password predefinita per l'account amministratore IPMI su ciascun nodo di storage non appena si configura la porta di rete IPMI.

.Di cosa hai bisogno
L'indirizzo IP IPMI dovrebbe essere stato configurato per ciascun nodo di storage.

.Fasi
. Aprire un browser Web su un computer in grado di raggiungere la rete IPMI e individuare l'indirizzo IP IPMI del nodo.
. Immettere il nome utente `ADMIN` e password `ADMIN` al prompt di login.
. Una volta effettuato l'accesso, fare clic sulla scheda *Configuration* (Configurazione).
. Fare clic su *utenti*.
. Selezionare `ADMIN` E fare clic su *Modify User* (Modifica utente).
. Selezionare la casella di controllo *Change Password* (Modifica password).
. Immettere una nuova password nei campi *Password* e *Conferma password*.
. Fare clic su *Modify*, quindi su *OK*.
. Ripetere questa procedura per tutti gli altri nodi H410S con password IPMI predefinite.




== Modificare la password IPMI predefinita per H610S nodi

È necessario modificare la password predefinita per l'account amministratore IPMI su ciascun nodo di storage non appena si configura la porta di rete IPMI.

.Di cosa hai bisogno
L'indirizzo IP IPMI dovrebbe essere stato configurato per ciascun nodo di storage.

.Fasi
. Aprire un browser Web su un computer in grado di raggiungere la rete IPMI e individuare l'indirizzo IP IPMI del nodo.
. Immettere il nome utente `root` e password `calvin` al prompt di login.
. Una volta effettuato l'accesso, fare clic sull'icona di navigazione del menu in alto a sinistra della pagina per aprire il cassetto della barra laterale.
. Fare clic su *Impostazioni*.
. Fare clic su *Gestione utenti*.
. Selezionare l'utente *Administrator* dall'elenco.
. Attivare la casella di controllo *Change Password* (Modifica password).
. Immettere una nuova password complessa nei campi *Password* e *Conferma password*.
. Fare clic su *Save* (Salva) nella parte inferiore della pagina.
. Ripetere questa procedura per tutti gli altri nodi H610S con password IPMI predefinite.




== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]

