---
permalink: storage/task_data_manage_vvol_enable_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volumes, enable, functionality on the cluster, vvols 
summary: 'È necessario attivare manualmente la funzionalità vSphere Virtual Volumes (VVol) tramite il software NetApp Element. Il sistema software Element viene fornito con la funzionalità VVol disattivata per impostazione predefinita e non viene automaticamente attivata durante una nuova installazione o un aggiornamento. L"attivazione della funzione VVol è un"attività di configurazione unica.' 
---
= Abilitare i volumi virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario attivare manualmente la funzionalità vVol (vSphere Virtual Volumes) tramite il software NetApp Element. Il sistema software Element viene fornito con la funzionalità VVol disattivata per impostazione predefinita e non viene automaticamente attivata durante una nuova installazione o un aggiornamento. L'attivazione della funzione VVol è un'attività di configurazione unica.

.Di cosa hai bisogno
* Il cluster deve eseguire Element 9.0 o versione successiva.
* Il cluster deve essere connesso a un ambiente ESXi 6.0 o successivo compatibile con VVol.
* Se si utilizza Element 11.3 o versione successiva, il cluster deve essere connesso a un ambiente ESXi 6.0 update 3 o versione successiva.



IMPORTANT: L'attivazione della funzionalità vSphere Virtual Volumes modifica in modo permanente la configurazione del software Element. La funzionalità VVol deve essere attivata solo se il cluster è connesso a un ambiente compatibile con VMware ESXi VVols. È possibile disattivare la funzione VVol e ripristinare le impostazioni predefinite solo ripristinando l'immagine predefinita del cluster, che elimina tutti i dati presenti nel sistema.

.Fasi
. Selezionare *Clusters* > *Settings*.
. Individuare le impostazioni specifiche del cluster per i volumi virtuali.
. Fare clic su *Enable Virtual Volumes* (Abilita volumi virtuali
. Fare clic su *Sì* per confermare la modifica della configurazione dei volumi virtuali.
+
La scheda *VVol* viene visualizzata nell'interfaccia utente di Element.

+

NOTE: Quando la funzionalità VVol è attivata, il cluster SolidFire avvia il provider VASA, apre la porta 8444 per il traffico VASA e crea endpoint di protocollo che possono essere rilevati da vCenter e da tutti gli host ESXi.

. Copiare l'URL del provider VASA dalle impostazioni dei volumi virtuali (VVol) in *Clusters* > *Settings*. Questo URL verrà utilizzato per registrare il provider VASA in vCenter.
. Creare un contenitore di storage in *VVol* > *Storage Containers*.
+

NOTE: È necessario creare almeno un container di storage in modo che le VM possano essere fornite a un datastore Vol.

. Selezionare *VVol* > *Protocol Endpoint*.
. Verificare che sia stato creato un endpoint del protocollo per ciascun nodo del cluster.
+

NOTE: VSphere richiede ulteriori attività di configurazione. Consultare la _Guida alla configurazione dello storage VMware vSphere Virtual Volumes per SolidFire_ per registrare il provider VASA in vCenter, creare e gestire i datastore VVol e gestire lo storage in base alle policy.





== Trova ulteriori informazioni

https://www.netapp.com/us/media/tr-4642.pdf["Guida alla configurazione dello storage VMware vSphere Virtual Volumes per SolidFire"]
