---
permalink: storage/task_post_deploy_configure_system_options.html 
sidebar: sidebar 
keywords: deployment, post deployment options, credentials, components, FIPS security, passwords, MFA, multifactor authentication, mutli-factor authentication, security, EKM, key management, external key management, FIPS 
summary: 'Dopo aver configurato il sistema SolidFire, è possibile eseguire alcune attività facoltative. Inoltre, è possibile configurare le impostazioni per l"autenticazione a più fattori, la gestione delle chiavi esterne e la protezione FIPS (Federal Information Processing Standards).' 
---
= Configurare le opzioni del sistema SolidFire dopo l'implementazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver configurato il sistema SolidFire, è possibile eseguire alcune attività facoltative.

Se si modificano le credenziali nel sistema, potrebbe essere necessario conoscere l'impatto su altri componenti.

Inoltre, è possibile configurare le impostazioni per l'autenticazione a più fattori, la gestione delle chiavi esterne e la protezione FIPS (Federal Information Processing Standards).
Inoltre, è consigliabile aggiornare le password quando necessario.



== Trova ulteriori informazioni

* link:task_post_deploy_credentials.html["Modificare le credenziali in NetApp HCI e NetApp SolidFire"]
* link:reference_post_deploy_change_default_ssl_certificate.html["Modificare il certificato SSL predefinito del software Element"]
* link:task_post_deploy_credential_change_ipmi_password.html["Modificare la password IPMI per i nodi"]
* link:concept_system_manage_mfa_enable_multi_factor_authentication.html["Abilitare l'autenticazione a più fattori"]
* link:concept_system_manage_key_get_started_with_external_key_management.html["Inizia a utilizzare la gestione esterna delle chiavi"]
* link:task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["Creare un cluster che supporti i dischi FIPS"]

