---
permalink: storage/task_system_manage_virtual_edit_a_virtual_network.html 
sidebar: sidebar 
keywords: virtual network, edit, ip address block, vlan attributes 
summary: 'È possibile modificare gli attributi della VLAN, ad esempio il nome della VLAN, la netmask e la dimensione dei blocchi di indirizzi IP. Il tag VLAN e SVIP non possono essere modificati per una VLAN. L"attributo gateway non è un parametro valido per le VLAN non VRF.' 
---
= Modificare una rete virtuale
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_determine_which_VLAN_IP%27s_are_in_use_and_which_nodes_those_IP%27s_are_assigned_to_in_Element
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare gli attributi della VLAN, ad esempio il nome della VLAN, la netmask e la dimensione dei blocchi di indirizzi IP. Il tag VLAN e SVIP non possono essere modificati per una VLAN. L'attributo gateway non è un parametro valido per le VLAN non VRF.

Se sono presenti iSCSI, replica remota o altre sessioni di rete, la modifica potrebbe non riuscire.

Quando si gestiscono le dimensioni degli intervalli di indirizzi IP della VLAN, tenere presenti le seguenti limitazioni:

* È possibile rimuovere gli indirizzi IP solo dall'intervallo di indirizzi IP iniziale assegnato al momento della creazione della VLAN.
* È possibile rimuovere un blocco di indirizzi IP aggiunto dopo l'intervallo di indirizzi IP iniziale, ma non è possibile ridimensionare un blocco IP rimuovendo gli indirizzi IP.
* Quando si tenta di rimuovere gli indirizzi IP, dall'intervallo di indirizzi IP iniziale o in un blocco IP, utilizzati dai nodi nel cluster, l'operazione potrebbe non riuscire.
* Non è possibile riassegnare indirizzi IP in uso specifici ad altri nodi nel cluster.


È possibile aggiungere un blocco di indirizzi IP seguendo la procedura riportata di seguito:

. Selezionare *Cluster* > *Network*.
. Selezionare l'icona Actions (azioni) per la VLAN che si desidera modificare.
. Selezionare *Modifica*.
. Nella finestra di dialogo *Edit VLAN* (Modifica VLAN), immettere i nuovi attributi per la VLAN.
. Selezionare *Aggiungi un blocco* per aggiungere un blocco non continuo di indirizzi IP per la rete virtuale.
. Selezionare *Save Changes* (Salva modifiche).


.Collegamento agli articoli della Knowledge base per la risoluzione dei problemi
Collegamento agli articoli della Knowledge base per assistenza nella risoluzione dei problemi relativi alla gestione degli intervalli di indirizzi IP della VLAN.

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Duplicate_IP_warning_after_adding_a_storage_node_in_VLAN_on_Element_cluster["Avviso IP duplicato dopo l'aggiunta di un nodo di storage nella VLAN sul cluster di elementi"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_determine_which_VLAN_IP%27s_are_in_use_and_which_nodes_those_IP%27s_are_assigned_to_in_Element["Come determinare quali IP VLAN sono in uso e a quali nodi sono assegnati in Element"^]

