---
permalink: storage/task-element-replication-create-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, element, source, destination 
summary: SnapMirror può essere utilizzato per replicare le copie Snapshot di un volume Element in un sistema di destinazione ONTAP. In caso di disastro nel sito Element, è possibile inviare i dati ai client dal sistema ONTAP, quindi riattivare il volume di origine Element al ripristino del servizio. 
---
= Creare una relazione da un'origine elemento a una destinazione ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La relazione tra il volume di origine nello storage primario e il volume di destinazione nello storage secondario viene definita _relazione di protezione dei dati_. È possibile utilizzare `snapmirror create` il comando per creare una relazione di data Protection da un'origine dell'elemento a una destinazione ONTAP o da un'origine ONTAP a una destinazione dell'elemento.

SnapMirror può essere utilizzato per replicare le copie Snapshot di un volume Element in un sistema di destinazione ONTAP. In caso di disastro nel sito Element, è possibile inviare i dati ai client dal sistema ONTAP, quindi riattivare il volume di origine Element al ripristino del servizio.

.Prima di iniziare
* Il nodo Element contenente il volume da replicare deve essere stato reso accessibile a ONTAP.
* Il volume Element deve essere stato abilitato per la replica di SnapMirror.
* Se si utilizza il tipo di criterio "speculare-vault", è necessario configurare un'etichetta SnapMirror per la replica delle copie snapshot dell'elemento.
+
[NOTE]
====
È possibile eseguire questa attività solo in link:concept_snapmirror_labels.html["UI web del software Element"]o utilizzando link:../api/concept_element_api_snapshots_overview.html["Metodi API"].

====


.A proposito di questa attività
È necessario specificare il percorso di origine dell'elemento nel formato `<hostip:>/lun/<name>`, dove "`lun'" è la stringa effettiva "`lun'" ed `name` è il nome del volume dell'elemento.

Un volume Element equivale approssimativamente a un LUN ONTAP. SnapMirror crea un LUN con il nome del volume Element quando viene inizializzata una relazione di protezione dei dati tra il software Element e ONTAP. SnapMirror replica i dati su un LUN esistente se il LUN soddisfa i requisiti per la replica dal software Element a ONTAP.

Le regole di replica sono le seguenti:

* Un volume ONTAP può contenere dati provenienti da un solo volume elemento.
* Non è possibile replicare i dati da un volume ONTAP a più volumi di elementi.


In ONTAP 9.3 e versioni precedenti, un volume di destinazione può contenere fino a 251 copie snapshot. In ONTAP 9.4 e versioni successive, un volume di destinazione può contenere fino a 1019 copie snapshot.

.Fase
. Dal cluster di destinazione, creare una relazione di replica da un'origine elemento a una destinazione ONTAP:
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Nell'esempio seguente viene creata una relazione DR SnapMirror utilizzando il criterio predefinito `MirrorLatest`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
Nell'esempio seguente viene creata una relazione di replica unificata utilizzando il criterio predefinito `MirrorAndVault`:

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
Nell'esempio seguente viene creata una relazione di replica unificata utilizzando il `Unified7year` criterio:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
Nell'esempio seguente viene creata una relazione di replica unificata utilizzando il criterio personalizzato `my_unified`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.Al termine
Utilizzare il `snapmirror show` comando per verificare che la relazione SnapMirror sia stata creata. Per la sintassi completa dei comandi, vedere la pagina man.
