---
permalink: storage/task_replication_pair_volumes_using_a_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, replication 
summary: Se non si dispone delle credenziali di amministratore del cluster per un cluster remoto, è possibile associare un volume a un altro volume di un cluster remoto utilizzando una chiave di accoppiamento. 
---
= Associare i volumi utilizzando una chiave di accoppiamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se non si dispone delle credenziali di amministratore del cluster per un cluster remoto, è possibile associare un volume a un altro volume di un cluster remoto utilizzando una chiave di accoppiamento.

.Di cosa hai bisogno
* Assicurarsi che i cluster contenenti i volumi siano associati.
* Assicurarsi che sul cluster remoto sia presente un volume da utilizzare per l'associazione.
+

NOTE: È possibile assegnare un'origine e una destinazione di replica dopo il processo di associazione. Un'origine o una destinazione di replica può essere un volume in una coppia di volumi. È necessario creare un volume di destinazione che non contenga dati e che abbia le caratteristiche esatte del volume di origine, ad esempio dimensioni, impostazione delle dimensioni del blocco per i volumi (512e o 4k) e configurazione QoS. Se si assegna un volume esistente come destinazione della replica, i dati su quel volume verranno sovrascritti. Il volume di destinazione può avere dimensioni maggiori o uguali a quelle del volume di origine, ma non può essere più piccolo.



.Fasi
. Selezionare *Management* > *Volumes*.
. Fare clic sull'icona *azioni* del volume che si desidera associare.
. Fare clic su *Pair* (abbina).
. Nella finestra di dialogo *Pair Volume* (Volume coppia), selezionare *Start Pairing* (Avvia associazione).
. Selezionare *i do not* per indicare che non si dispone dell'accesso al cluster remoto.
. Selezionare una *Replication Mode* dall'elenco:
+
** *Real-time (asincrono)*: Le scritture vengono riconosciute al client dopo il commit sul cluster di origine.
** *Real-time (Synchronous)*: Le scritture vengono riconosciute al client dopo il commit sia sul cluster di origine che su quello di destinazione.
** *Solo istantanee*: Vengono replicate solo le istantanee create nel cluster di origine. Le scritture attive dal volume di origine non vengono replicate.


. Fare clic su *generate Key* (genera chiave).
+

NOTE: Questa azione genera una chiave di testo per l'associazione e crea una coppia di volumi non configurata sul cluster locale. Se la procedura non viene completata, è necessario eliminare manualmente la coppia di volumi.

. Copiare la chiave di accoppiamento nella clipboard del computer.
. Rendere la chiave di accoppiamento accessibile all'amministratore del cluster nel sito del cluster remoto.
+

NOTE: La chiave di accoppiamento del volume deve essere trattata in modo sicuro e non deve essere utilizzata in modo da consentire un accesso accidentale o non protetto.

+

IMPORTANT: Non modificare i caratteri della chiave di accoppiamento. La chiave diventa non valida se viene modificata.

. Nell'interfaccia utente degli elementi del cluster remoto, selezionare *Management* > *Volumes*.
. Fare clic sull'icona Actions (azioni) per il volume che si desidera associare.
. Fare clic su *Pair* (abbina).
. Nella finestra di dialogo *Pair Volume* (Volume coppia), selezionare *complete Pairing* (completa associazione).
. Incollare la chiave di accoppiamento dall'altro cluster nella casella *Pairing Key* (chiave di associazione).
. Fare clic su *completa associazione*.
+
Dopo aver confermato l'associazione, i due cluster iniziano il processo di connessione dei volumi per l'associazione. Durante il processo di associazione, è possibile visualizzare i messaggi nella colonna *Volume Status* (Stato volume) della finestra *Volume Pairs* (coppie di volumi). Viene visualizzata la coppia di volumi `PausedMisconfigured` fino a quando non vengono assegnate l'origine e la destinazione della coppia di volumi.

+
Dopo aver completato correttamente l'associazione, si consiglia di aggiornare la tabella dei volumi per rimuovere l'opzione *abbina* dall'elenco *azioni* per il volume associato. Se non si aggiorna la tabella, l'opzione *Pair* rimane disponibile per la selezione. Se si seleziona di nuovo l'opzione *Pair*, viene visualizzata una nuova scheda e, poiché il volume è già associato, il sistema riporta un `StartVolumePairing Failed: xVolumeAlreadyPaired` Messaggio di errore nella finestra *Pair Volume* della pagina dell'interfaccia utente dell'elemento.





== Trova ulteriori informazioni

* xref:reference_replication_volume_pairing_messages.adoc[Messaggi di associazione del volume]
* xref:reference_replication_volume_pairing_warnings.adoc[Avvisi di associazione del volume]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[Assegnare un'origine e una destinazione di replica ai volumi accoppiati]

