---
permalink: setup/concept_setup_fc_configure_a_fibre_channel_node.html 
sidebar: sidebar 
keywords:  
summary: 'I nodi Fibre Channel consentono di collegare il cluster a un fabric di rete Fibre Channel. I nodi Fibre Channel vengono aggiunti a coppie e funzionano in modalità Active-Active (tutti i nodi elaborano attivamente il traffico per il cluster). I cluster che eseguono Element Software versione 9.0 e successive supportano fino a quattro nodi; i cluster che eseguono versioni precedenti supportano un massimo di due nodi.' 
---
= Configurare un nodo Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nodi Fibre Channel consentono di collegare il cluster a un fabric di rete Fibre Channel. I nodi Fibre Channel vengono aggiunti a coppie e funzionano in modalità Active-Active (tutti i nodi elaborano attivamente il traffico per il cluster). I cluster che eseguono Element Software versione 9.0 e successive supportano fino a quattro nodi; i cluster che eseguono versioni precedenti supportano un massimo di due nodi.

Prima di configurare un nodo Fibre Channel, assicurarsi che siano soddisfatte le seguenti condizioni:

* Almeno due nodi Fibre Channel sono collegati agli switch Fibre Channel.
* Tutte le porte Fibre Channel SolidFire devono essere collegate al fabric Fibre Channel. Le quattro connessioni di rete SolidFire Bond10G devono essere collegate in un unico gruppo di bond LACP a livello di switch. In questo modo si otterranno le migliori prestazioni complessive dei sistemi Fibre Channel.
* Esaminare e convalidare tutte le Best practice per i cluster Fibre Channel incluse in questo articolo della Knowledge base di NetApp.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/SolidFire_FC_cluster_best_practice["Best practice per il cluster SolidFire FC"]



Le fasi di configurazione della rete e del cluster sono le stesse per i nodi Fibre Channel e i nodi di storage.

Quando si crea un nuovo cluster con nodi Fibre Channel e nodi di storage SolidFire, gli indirizzi WWPN (Worldwide Port Name) per i nodi sono disponibili nell'interfaccia utente di Element. È possibile utilizzare gli indirizzi WWPN per mettere in zona lo switch Fibre Channel.

Le WWPN vengono registrate nel sistema quando si crea un nuovo cluster con nodi. Nell'interfaccia utente Element, è possibile trovare gli indirizzi WWPN dalla colonna WWPN della scheda FC Ports (Porte FC), a cui si accede dalla scheda Cluster.



== Trova ulteriori informazioni

xref:task_setup_fc_add_fibre_channel_nodes_to_a_cluster.adoc[Aggiunta di nodi Fibre Channel a un cluster]

xref:task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.adoc[Creare un nuovo cluster con nodi Fibre Channel]
