---
permalink: setup/task_post_deploy_access_the_element_software_user_interface.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile accedere all"interfaccia utente Element utilizzando l"indirizzo IP virtuale di gestione del nodo principale del cluster.' 
---
= Accedere all'interfaccia utente del software Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile accedere all'interfaccia utente Element utilizzando l'indirizzo IP virtuale di gestione (MVIP) del nodo principale del cluster.

Assicurarsi che i blocchi dei popup e le impostazioni NoScript siano disattivati nel browser.

È possibile accedere all'interfaccia utente utilizzando l'indirizzamento IPv4 o IPv6, a seconda della configurazione durante la creazione del cluster.

.Fasi
. Scegliere una delle seguenti opzioni:
+
** IPv6: Invio `https://[IPv6_MVIP_address]`. Ad esempio:
+
[listing]
----
https://[fd20:8b1e:b256:45a::1234]/
----
** IPv4: Immettere `https://[IPv4 MVIP address]`. Ad esempio:
+
[listing]
----
https://10.123.456.789/
----


. Per DNS, immettere il nome host.
. Fare clic sui messaggi dei certificati di autenticazione.




== Per ulteriori informazioni

* https://www.netapp.com/data-storage/solidfire/documentation["Pagina SolidFire and Element Resources"^]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per server vCenter"^]

