---
permalink: api/concept_element_api_vvols_api_methods.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,API,method 
summary: 'I metodi API dei volumi virtuali del software Element consentono di gestire i volumi virtuali (VVol). È possibile visualizzare i VVol esistenti con questi metodi API, nonché creare, modificare ed eliminare i container di storage dei volumi virtuali. Sebbene non sia possibile utilizzare questi metodi per operare su volumi normali, è possibile utilizzare i normali metodi API del volume per elencare le informazioni su VVol.' 
---
= Metodi API dei volumi virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I metodi API dei volumi virtuali del software Element consentono di gestire i volumi virtuali (VVol). È possibile visualizzare i VVol esistenti con questi metodi API, nonché creare, modificare ed eliminare i container di storage dei volumi virtuali. Sebbene non sia possibile utilizzare questi metodi per operare su volumi normali, è possibile utilizzare i normali metodi API del volume per elencare le informazioni su VVol.

* xref:reference_element_api_createstoragecontainer.adoc[CreateStorageContainer]
* xref:reference_element_api_deletestoragecontainers.adoc[DeleteStorageContainers]
* xref:reference_element_api_getstoragecontainerefficiency.adoc[GetStorageContainerEfficiency]
* xref:reference_element_api_getvirtualvolumecount.adoc[GetVirtualVolumeCount]
* xref:reference_element_api_listprotocolendpoints.adoc[ListProtocolEndpoint]
* xref:reference_element_api_liststoragecontainers.adoc[ListStorageContainers]
* xref:reference_element_api_listvirtualvolumebindings.adoc[ListVirtualVolumeBindings]
* xref:reference_element_api_listvirtualvolumehosts.adoc[ListVirtualVolumeHost]
* xref:reference_element_api_listvirtualvolumes.adoc[ListVirtualVolumes]
* xref:reference_element_api_listvirtualvolumetasks.adoc[ListVirtualVolumeTasks]
* xref:reference_element_api_modifystoragecontainer.adoc[ModifyStorageContainer]




== Trova ulteriori informazioni

* https://www.netapp.com/data-storage/solidfire/documentation/["Pagina delle risorse NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti SolidFire ed Element di NetApp"^]

