---
permalink: api/concept_element_api_administrator_api_methods.html 
sidebar: sidebar 
keywords: API,administration,method,administrator 
summary: 'È possibile utilizzare i metodi API dell"amministratore per creare, modificare, visualizzare e rimuovere gli amministratori del cluster di storage e assegnare livelli di accesso e privilegi a coloro che hanno accesso a un cluster di storage.' 
---
= Metodi API dell'amministratore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i metodi API dell'amministratore per creare, modificare, visualizzare e rimuovere gli amministratori del cluster di storage e assegnare livelli di accesso e privilegi a coloro che hanno accesso a un cluster di storage.

* xref:reference_element_api_addclusteradmin.adoc[AddClusterAdmin]
* xref:reference_element_api_getcurrentclusteradmin.adoc[GetCurrentClusterAdmin]
* xref:reference_element_api_getloginbanner.adoc[GetLoginBanner]
* xref:reference_element_api_listclusteradmins.adoc[ListClusterAdmins]
* xref:reference_element_api_modifyclusteradmin.adoc[ModifyClusterAdmin]
* xref:reference_element_api_removeclusteradmin.adoc[RemoveClusterAdmin]
* xref:reference_element_api_setloginbanner.adoc[SetLoginBanner]




== Trova ulteriori informazioni

* https://www.netapp.com/data-storage/solidfire/documentation/["Pagina delle risorse NetApp SolidFire"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti SolidFire ed Element di NetApp"^]

