---
permalink: api/concept_element_api_request_endpoints.html 
sidebar: sidebar 
keywords: request,endpoints 
summary: 'Esistono tre tipi di endpoint di richiesta utilizzati nell"API (cluster di storage, creazione di cluster di storage e per nodo). Si consiglia di utilizzare sempre l"endpoint più recente supportato dalla versione del software Element.' 
---
= Endpoint della richiesta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'API utilizza tre tipi di endpoint di richiesta (cluster di storage, creazione di cluster di storage e per nodo). Si consiglia di utilizzare sempre l'endpoint più recente supportato dalla versione del software Element.

I tre endpoint della richiesta nell'API sono designati nei seguenti modi:



== Metodi API del cluster

L'endpoint HTTPS per le richieste API a livello di cluster di storage è `+https://<mvip>/json-rpc/<api-version>+`, dove:

* `<mvip>` È l'indirizzo IP virtuale di gestione per il cluster di storage.
* `<api-version>` È la versione dell'API in uso.




== Creazione di cluster e metodi API di bootstrap

L'endpoint HTTPS per la creazione di un cluster di storage e l'accesso alle richieste API di bootstrap è `+https://<nodeIP>/json-rpc/<api-version>+`, dove:

* `<nodeIP>` È l'indirizzo IP del nodo che si sta aggiungendo al cluster.
* `<api-version>` È la versione dell'API in uso.




== Metodi API per nodo

L'endpoint HTTPS per le richieste API dei singoli nodi di storage è `+https://<nodeIP>:442/json-rpc/<api-version>+`, dove:

* `<nodeIP>` È l'indirizzo IP di gestione del nodo di storage; 442 è la porta su cui viene eseguito il server HTTPS.
* `<api-version>` È la versione dell'API in uso.




== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione software SolidFire ed Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti SolidFire ed Element di NetApp"^]

