---
permalink: api/reference_element_api_listvolumestatsbyvirtualvolume.html 
sidebar: sidebar 
keywords: volumes,volume,virtual,stats,list,listing,listvolumestatsbyvirtualvolume,activity 
summary: È possibile utilizzare il metodo ListVolumeStatsByVirtualVolume per elencare le statistiche dei volumi del sistema associati al volume virtuale. Le statistiche sono cumulative a partire dalla creazione del volume. 
---
= ListVolumeStatsByVirtualVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListVolumeStatsByVirtualVolume` metodo per elencare le statistiche dei volumi per tutti i volumi del sistema associati al volume virtuale. Le statistiche sono cumulative a partire dalla creazione del volume.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
VirtualVolumeID
 a| 
Elenco di uno o più ID di volumi virtuali per i quali recuperare le informazioni. Se si specifica questo parametro, il metodo restituisce informazioni solo su questi volumi virtuali.
 a| 
Array di stringhe UUID
 a| 
No
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
VolumeStats
 a| 
Un elenco di oggetti contenente informazioni sulle attività per ciascun volume virtuale nel sistema.
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStats] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "ListVolumeStatsByVirtualVolume",
  "params": {},
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 17,
        "actualIOPS": 0,
        "asyncDelay": null,
        "averageIOPSize": 1074265444,
        "burstIOPSCredit": 0,
        "clientQueueDepth": 0,
        "desiredMetadataHosts": null,
        "latencyUSec": 0,
        "metadataHosts": {
          "deadSecondaries": [],
          "liveSecondaries": [
            26
          ],
          "primary": 56
        },
        "nonZeroBlocks": 36,
        "readBytes": 18366464,
        "readBytesLastSample": 0,
        "readLatencyUSec": 0,
        "readOps": 156,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "throttle": 0,
        "timestamp": "2016-10-10T17:46:35.914642Z",
        "unalignedReads": 156,
        "unalignedWrites": 185,
        "virtualVolumeID": "070ac0ba-f344-4f4c-b79c-142efa3642e8",
        "volumeAccessGroups": [],
        "volumeID": 12518,
        "volumeSize": 91271200768,
        "volumeUtilization": 0,
        "writeBytes": 23652213248,
        "writeBytesLastSample": 0,
        "writeLatencyUSec": 0,
        "writeOps": 185,
        "writeOpsLastSample": 0,
        "zeroBlocks": 22282972
      }
    ]
  }
}
----


== Novità dalla versione

9,6
