---
permalink: api/reference_element_api_setsnmpacl.html 
sidebar: sidebar 
keywords: setsnmpACL,set,setting,snmp,acl,permissions,access,control,list 
summary: È possibile utilizzare il metodo SetSnmpACL per configurare le autorizzazioni di accesso SNMP sui nodi del cluster. I valori impostati con questa interfaccia si applicano a tutti i nodi del cluster e i valori passati sostituiscono tutti i valori impostati in qualsiasi chiamata precedente a SetSnmpACL. Si noti inoltre che i valori impostati con questa interfaccia sostituiscono tutti i valori di rete o usmUsers impostati con SetSnmpInfo. 
---
= SetSnmpACL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `SetSnmpACL` Metodo per configurare le autorizzazioni di accesso SNMP sui nodi del cluster. I valori impostati con questa interfaccia si applicano a tutti i nodi del cluster e i valori passati sostituiscono tutti i valori impostati in qualsiasi chiamata precedente a. `SetSnmpACL`. Si noti inoltre che i valori impostati con questa interfaccia sostituiscono tutti i valori di rete o usmUsers impostati con `SetSnmpInfo` metodo.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
reti
 a| 
Elenco delle reti e tipo di accesso ai server SNMP in esecuzione sui nodi del cluster. Vedere oggetto di rete SNMP per i possibili valori di rete. Questo parametro è obbligatorio se SNMP v3 è disattivato.
 a| 
xref:reference_element_api_network_snmp.adoc[rete]
 a| 
Nessuno
 a| 
No



 a| 
UsmUsers
 a| 
Elenco di utenti e tipo di accesso ai server SNMP in esecuzione sui nodi del cluster. Questo parametro è obbligatorio se SNMP v3 è attivato.
 a| 
xref:reference_element_api_usmuser.adoc[UsmUser]
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo non ha valori restituiti.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "SetSnmpACL",
  "params": {
    "usmUsers"  : [
      {
         "name": "jdoe",
         "access": "rouser",
         "secLevel": "priv",
         "password": "mypassword",
         "passphrase": "mypassphrase",
      }
    ]
  },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_setsnmpinfo.adoc[SetSnmpInfo]
