---
permalink: api/reference_element_api_listsnapmirroraggregates.html 
sidebar: sidebar 
keywords: snapmirror,aggregate,aggregates,list,listing,listsnapmirroraggregates 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo ListSnapMirrorAggregates per elencare tutti gli aggregati SnapMirror disponibili nel sistema ONTAP remoto. Un aggregato descrive un insieme di risorse di storage fisiche.' 
---
= ListSnapMirrorAggregates
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `ListSnapMirrorAggregates` Metodo per elencare tutti gli aggregati SnapMirror disponibili nel sistema ONTAP remoto. Un aggregato descrive un insieme di risorse di storage fisiche.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SnapMirrorEndpointID
 a| 
Restituisce solo gli aggregati associati all'ID endpoint specificato. Se non viene fornito alcun ID endpoint, il sistema elenca gli aggregati di tutti gli endpoint SnapMirror noti.
 a| 
intero
 a| 
Nessuno
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
SnapMirrorAggregate
 a| 
Un elenco degli aggregati disponibili nel sistema storage ONTAP.
 a| 
xref:reference_element_api_snapmirroraggregate.adoc[SnapMirrorAggregate] array

|===


== Novità dalla versione

10,1
