---
permalink: api/reference_element_api_liststoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,containers,list,listing,liststoragecontainers 
summary: È possibile utilizzare il metodo ListStorageContainers per recuperare informazioni su tutti i container di storage dei volumi virtuali noti al sistema. 
---
= ListStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListStorageContainers` metodo per recuperare informazioni su tutti i container di storage dei volumi virtuali noti al sistema.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
StorageContainerID
 a| 
Un elenco di ID container di storage per i quali recuperare le informazioni. Se si omette questo parametro, il metodo restituisce informazioni su tutti i contenitori di storage nel sistema.
 a| 
Array UUID
 a| 
Nessuno
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
StorageContainers
 a| 
Elenco di oggetti contenenti informazioni su tutti i contenitori di storage nel sistema.
 a| 
xref:reference_element_api_storagecontainer.adoc[StorageContainer] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "ListStorageContainers",
   "params": {
      "storageContainerIDs": ["efda8307-b916-4424-979e-658a3f16894d"]
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 6395,
  "result": {
    "storageContainers": [
      {
        "accountID": 64,
        "initiatorSecret": "EJ:08An1MyNQmL!7",
        "name": "VvolContainer",
        "protocolEndpointType": "SCSI",
        "status": "active",
        "storageContainerID": "efda8307-b916-4424-979e-658a3f16894d",
        "targetSecret": "g38}zWBK%206jQr~",
        "virtualVolumes": []
      }
    ]
  }
}
----


== Novità dalla versione

9,6
