---
permalink: api/reference_element_api_listsnapmirrorschedules.html 
sidebar: sidebar 
keywords: snapmirror,schedule,schedules,list,listing,listsnapmirrorschedules,ontap 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo ListSnapMirrorSchedules per ottenere un elenco di pianificazioni disponibili in un cluster ONTAP remoto.' 
---
= ListSnapMirrorSchedules
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `ListSnapMirrorSchedules` Metodo per ottenere un elenco di pianificazioni disponibili in un cluster ONTAP remoto.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SnapMirrorEndpointID
 a| 
Se fornito, il sistema elenca le pianificazioni dell'endpoint con l'ID endpoint SnapMirror specificato. Se non viene fornito, il sistema elenca le pianificazioni di tutti gli endpoint SnapMirror noti.
 a| 
intero
 a| 
Nessuno
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
SnapMirrorSchedules
 a| 
Un elenco delle pianificazioni di SnapMirror sul cluster ONTAP remoto.
 a| 
xref:reference_element_api_snapmirrorjobschedulecroninfo.adoc[SnapMirrorJobScheduleCronInfo] array

|===


== Novità dalla versione

10,1
