---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: È possibile utilizzare il metodo AddClusterAdmin per aggiungere un nuovo account amministratore del cluster. Un amministratore del cluster può gestire il cluster tramite API e strumenti di gestione. Gli amministratori dei cluster sono completamente separati e non correlati agli account dei tenant standard. 
---
= AddClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `AddClusterAdmin` metodo per aggiungere un nuovo account amministratore del cluster. Un amministratore del cluster può gestire il cluster tramite API e strumenti di gestione. Gli amministratori dei cluster sono completamente separati e non correlati agli account dei tenant standard.

Ogni amministratore del cluster può essere limitato a un sottoinsieme dell'API. È necessario utilizzare più account di amministrazione del cluster per utenti e applicazioni diversi. Come Best practice, assegnare a ciascun amministratore del cluster le autorizzazioni minime necessarie; in questo modo si riduce il potenziale impatto della compromissione delle credenziali.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
accesso
 a| 
Controlla i metodi che l'amministratore del cluster può utilizzare.
 a| 
array di stringhe
 a| 
Nessuno
 a| 
Sì



 a| 
AccetteEula
 a| 
Accettare il Contratto di licenza con l'utente finale. Impostare su true per aggiungere un account amministratore del cluster al sistema. Se omesso o impostato su false, la chiamata al metodo non riesce.
 a| 
booleano
 a| 
Nessuno
 a| 
Sì



 a| 
attributi
 a| 
Elenco delle coppie nome/valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
No



 a| 
password
 a| 
Password utilizzata per autenticare questo amministratore del cluster.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì



 a| 
nome utente
 a| 
Nome utente univoco per questo amministratore del cluster. La lunghezza deve essere compresa tra 1 e 1024 caratteri.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
ID clusterAdminID
 a| 
ClusterAdminID per l'amministratore del cluster appena creato.
 a| 
intero

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_app_b_access_control.adoc[Controllo degli accessi]
