---
permalink: api/reference_element_api_testkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,testing,test 
summary: 'È possibile utilizzare il metodo TestKeyProviderKmip per verificare se il provider di chiavi KMIP (Key Management Interoperability Protocol) specificato è raggiungibile e funziona normalmente.' 
---
= TestKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `TestKeyProviderKmip` Metodo per verificare se il provider di chiavi KMIP (Key Management Interoperability Protocol) specificato è raggiungibile e funziona normalmente.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
KeyProviderID
 a| 
L'ID del provider di chiavi da testare.
 a| 
intero
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo non ha valori restituiti. Il test viene considerato riuscito finché non viene restituito alcun errore.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "TestKeyProviderKmip",
  "params": {
    "keyProviderID": 15
  },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Novità dalla versione

11,7
