---
permalink: api/reference_element_api_listprotocolendpoints.html 
sidebar: sidebar 
keywords: protocol,endpoints,endpoint,list,listing,listprotocolendpoints 
summary: 'È possibile utilizzare il metodo ListProtocolEndpoints per recuperare informazioni su tutti gli endpoint del protocollo nel cluster. Gli endpoint del protocollo regolano l"accesso ai contenitori di storage dei volumi virtuali associati.' 
---
= ListProtocolEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListProtocolEndpoints` metodo per recuperare informazioni su tutti gli endpoint del protocollo nel cluster. Gli endpoint del protocollo regolano l'accesso ai contenitori di storage dei volumi virtuali associati.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
ProtocolEndpointID
 a| 
Un elenco di ID endpoint del protocollo per i quali recuperare le informazioni. Se si omette questo parametro, il metodo restituisce informazioni su tutti gli endpoint del protocollo.
 a| 
Array UUID ProtocolEndpointID
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
ProtocolEndpoint
 a| 
Elenco di oggetti contenenti informazioni su ciascun endpoint del protocollo nel sistema.
 a| 
xref:reference_element_api_protocolendpoint.adoc[ProtocolEndpoint] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "id": 1,
  "method": "ListProtocolEndpoints",
  "params": {}
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "protocolEndpoints": [
      {
        "primaryProviderID": 1,
        "protocolEndpointID": "1387e257-d2e3-4446-be6d-39db71583e7b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000016970687200000000",
        "secondaryProviderID": 2
      },
      {
        "primaryProviderID": 2,
        "protocolEndpointID": "1f16ed86-3f31-4c76-b004-a1251187700b",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000026970687200000000",
        "secondaryProviderID": 3
      },
      {
        "primaryProviderID": 4,
        "protocolEndpointID": "c6458dfe-9803-4350-bb4e-68a3feb7e830",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000046970687200000000",
        "secondaryProviderID": 1
      },
      {
        "primaryProviderID": 3,
        "protocolEndpointID": "f3e7911d-0e86-4776-97db-7468c272213f",
        "protocolEndpointState": "Active",
        "providerType": "Primary",
        "scsiNAADeviceID": "6f47acc2000000036970687200000000",
        "secondaryProviderID": 4
      }
    ]
  }
}
----


== Novità dalla versione

9,6
