---
permalink: api/reference_element_api_removeaccount.html 
sidebar: sidebar 
keywords: account,accounts,remove,removing,deleting,delete,purge,volume,volumes,removeaccount 
summary: 'È possibile utilizzare il metodo RemoveAccount per rimuovere un account esistente. Prima di rimuovere l"account, è necessario eliminare e rimuovere tutti i volumi associati all"account utilizzando DeleteVolume. Se l"eliminazione dei volumi dell"account è ancora in sospeso, non è possibile utilizzare RemoveAccount per rimuovere l"account.' 
---
= RemoveAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `RemoveAccount` metodo per rimuovere un account esistente. È necessario eliminare ed eliminare tutti i volumi associati all'account utilizzando `DeleteVolume` prima di rimuovere l'account. Se i volumi dell'account sono ancora in attesa di eliminazione, non è possibile utilizzare `RemoveAccount` per rimuovere l'account.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
ID account
 a| 
L'ID dell'account da rimuovere.
 a| 
intero
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo non ha alcun valore restituito.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente.

[listing]
----
{
   "method": "RemoveAccount",
   "params": {
     "accountID"  : 25
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----

{
 "id" : 1,
 "result" : { }
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_deletevolume.adoc[DeleteVolume]
