---
permalink: api/reference_element_api_abortsnapmirrorrelationship.html 
sidebar: sidebar 
keywords:  
summary: 'L"interfaccia utente Web del software Element utilizza il metodo AbortSnapMirrorRelationship per arrestare i trasferimenti SnapMirror avviati ma non ancora completati.' 
---
= AbortSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `AbortSnapMirrorRelationship` Metodo per arrestare i trasferimenti SnapMirror avviati ma non ancora completati.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SnapMirrorEndpointID
 a| 
L'ID endpoint del sistema storage ONTAP remoto che comunica con il cluster storage Element.
 a| 
intero
 a| 
Nessuno
 a| 
Sì



 a| 
DestinationVolume
 a| 
Il volume di destinazione nella relazione SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Nessuno
 a| 
Sì



 a| 
Clear Checkpoint
 a| 
Determina se cancellare o meno il checkpoint di riavvio. Valori possibili:

* vero
* falso

 a| 
booleano
 a| 
falso
 a| 
No

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===
| Nome | Descrizione | Tipo 


 a| 
SnapMirrorRelationship
 a| 
Oggetto contenente informazioni sulla relazione SnapMirror interrotta.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Novità dalla versione

10,1
