---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: 'È possibile utilizzare il metodo DisableClusterSsh per disattivare il servizio SSH per l"intero cluster di storage. Quando si aggiungono nodi al cluster di storage, i nuovi nodi erediteranno questa impostazione a livello di cluster.' 
---
= DisableClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `DisableClusterSsh` Metodo per disattivare il servizio SSH per l'intero cluster di storage. Quando si aggiungono nodi al cluster di storage, i nuovi nodi erediteranno questa impostazione a livello di cluster.



== Parametro

Questo metodo non ha alcun parametro di input.



== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
risultato
 a| 
Oggetto JSON contenente lo stato del servizio SSH per il cluster di storage, il tempo rimanente prima della disattivazione di SSH e lo stato del servizio SSH per ciascun nodo.
 a| 
Oggetto JSON

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Novità dalla versione

10,3
