---
permalink: api/reference_element_api_listauthsessionbyusername.html 
sidebar: sidebar 
keywords: username,sessions,authentication sessions,list 
summary: 'È possibile utilizzare il metodo ListAuthSessionsByUsername per elencare tutte le sessioni auth per l"utente specificato. Un chiamante non in AccessGroup ClusterAdmins / privilegi di amministratore può elencare solo le proprie sessioni. Un chiamante con privilegi ClusterAdmins/Administrator può elencare le sessioni appartenenti a qualsiasi utente.' 
---
= ListAuthSessionsByNomeUtente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListAuthSessionsByUsername` metodo per elencare tutte le sessioni auth per l'utente specificato. Un chiamante non in AccessGroup ClusterAdmins / privilegi di amministratore può elencare solo le proprie sessioni. Un chiamante con privilegi ClusterAdmins/Administrator può elencare le sessioni appartenenti a qualsiasi utente.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
AuthMethod
 a| 
Metodo di autenticazione delle sessioni utente da elencare. Solo un chiamante in ClusterAdmins/Administrator AccessGroup può fornire questo parametro. I valori possibili sono:

* *AuthMethod=Cluster* specifica il nome utente di ClusterAdmin.
* *AuthMethod=LDAP* specifica il DN LDAP dell'utente.
* *AuthMethod=IDP* specifica l'ID utente IdP UUID o NameID. Se IdP non è configurato per restituire nessuna opzione, viene specificato un UUID casuale emesso al momento della creazione della sessione.

 a| 
AuthMethod
 a| 
Nessuno
 a| 
Sì



 a| 
nome utente
 a| 
Identificatore univoco dell'utente.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
sessioni
 a| 
Elenco delle informazioni sulla sessione per le sessioni auth.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
    "method": "ListAuthSessionsByUsername",
    "authMethod": "Cluster",
    "username": "admin"
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Novità dalla versione

12,0
