---
permalink: api/reference_element_api_volumestats.html 
sidebar: sidebar 
keywords: object,objects,volumeStats 
summary: 'L"oggetto volumeStats contiene dati statistici per un singolo volume.' 
---
= VolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto volumeStats contiene dati statistici per un singolo volume.



== Membri dell'oggetto

È possibile utilizzare i seguenti metodi per ottenere oggetti volumeStats per alcuni o tutti i volumi:

* xref:reference_element_api_getvolumestats.adoc[GetVolumeStats]
* xref:reference_element_api_listvolumestatsbyaccount.adoc[ListVolumeStatsByAccount]
* xref:reference_element_api_listvolumestatsbyvolume.adoc[ListVolumeStatsByVolume]
* xref:reference_element_api_listvolumestatsbyvolumeaccessgroup.adoc[ListVolumeStatsByVolumeAccessGroup]


Questo oggetto contiene i seguenti membri:

[cols="20,50,15,15"]
|===
| Nome | Descrizione | Calcolo | Tipo 


 a| 
ID account
 a| 
L'ID dell'account del proprietario del volume.
 a| 
N/A.
 a| 
intero



 a| 
AttualIOPS
 a| 
Gli IOPS effettivi correnti nel volume negli ultimi 500 millisecondi.
 a| 
Point-in-time
 a| 
intero



 a| 
AsyncDelay
 a| 
Il periodo di tempo trascorso dall'ultima sincronizzazione del volume con il cluster remoto. Se il volume non è associato, il valore è nullo. *Nota:* Un volume di destinazione in uno stato di replica attiva ha sempre un AsyncDelay pari a 0 (zero). I volumi di destinazione sono consapevoli del sistema durante la replica e presumono che asyncDelay sia sempre preciso.
 a| 
N/A.
 a| 
Stringa di durata ISO 8601 o nulla



 a| 
AverageIOPSize
 a| 
Dimensione media in byte di i/o recente nel volume negli ultimi 500 millisecondi.
 a| 
Point-in-time
 a| 
intero



 a| 
BurstIOPSSCredit
 a| 
Il numero totale di crediti IOP disponibili per l'utente. Quando i volumi non utilizzano un massimo di maxIOPS configurati, vengono accumulati crediti.
 a| 
N/A.
 a| 
intero



 a| 
ClientQueueDepth
 a| 
Il numero di operazioni di lettura e scrittura in sospeso nel volume.
 a| 
N/A.
 a| 
intero



 a| 
ClusterUtilization
 a| 
La quantità di capacità del cluster utilizzata.
 a| 
N/A.
 a| 
fluttuare



 a| 
DesiredMetadataHost
 a| 
I servizi di metadati (slice) in cui viene eseguita la migrazione dei metadati del volume tra i servizi di metadati. Un valore "nullo" indica che il volume non sta migrando.
 a| 
N/A.
 a| 
Oggetto JSON



 a| 
LatencyUSec
 a| 
Il tempo medio, in microsecondi, per completare le operazioni sul volume negli ultimi 500 millisecondi. Un valore "0" (zero) indica che non vi è alcun i/o nel volume.
 a| 
Point-in-time
 a| 
intero



 a| 
MetadataHost
 a| 
Servizi di metadati (slice) su cui risiedono i metadati del volume. Valori possibili:

* Primario: I servizi di metadati primari che ospitano il volume.
* LiveSecondaries: Servizi di metadati secondari che sono attualmente in stato "live".
* DeadSecondaries: Servizi di metadati secondari che si trovano in uno stato morto.

 a| 
N/A.
 a| 
Oggetto JSON



 a| 
Non ZeroBllocks
 a| 
Il numero totale di blocchi 4KiB che contengono dati dopo il completamento dell'ultima operazione di garbage collection.
 a| 
N/A.
 a| 
intero



 a| 
ReadByte
 a| 
I byte cumulativi totali letti dal volume dalla creazione del volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
ReadBytesLastSample
 a| 
Il numero totale di byte letti dal volume durante l'ultimo periodo di campionamento.
 a| 
Point-in-time
 a| 
intero



 a| 
ReadLatencyUSec
 a| 
Il tempo medio, in microsecondi, per completare le operazioni di lettura sul volume negli ultimi 500 millisecondi.
 a| 
Point-in-time
 a| 
intero



 a| 
ReadLatencyUSecTotal
 a| 
Il tempo totale impiegato per le operazioni di lettura dal volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
ReadOps
 a| 
Operazioni di lettura totali nel volume dalla creazione del volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
ReadOpsLastSample
 a| 
Il numero totale di operazioni di lettura durante l'ultimo periodo di campionamento.
 a| 
Point-in-time
 a| 
intero



 a| 
SamplePeriodMsec
 a| 
La durata del periodo di campionamento, in millisecondi.
 a| 
N/A.
 a| 
intero



 a| 
SliceIopsStats
 a| 
Statistiche di utilizzo di i/o per un volume. Disponibile a partire da Element 12,8. Valori possibili per le sliceIopsStats:

* LargeStatistics (Statistiche LargeStatistica): Le statistiche i/o del volume misurate su un periodo di tempo più lungo, di solito le ultime 24 ore.
* SmallStatistics (Statistiche piccole): Statistiche i/o del volume misurate in un periodo di tempo più breve, di solito l'ultima ora.


Valori possibili per largeStatistics e smallStatistics:

* AverageReadIops: Gli IOPS medi in lettura per il volume.
* AverageTotalIops: Gli IOPS totali medi (lettura + scrittura) per il volume.
* AverageWriteIops: Gli IOPS medi in scrittura per il volume.
* NSamples: Il numero di campioni inclusi nel calcolo statistico.
* PeakReadIops: Il numero massimo di IOPS in lettura osservati in un intervallo statistico.
* PeakTotalIops (IOPS totali peak): Il numero massimo di IOPS osservati in un intervallo statistico.
* PeakWriteIops: Il numero massimo di IOPS in scrittura osservati in un intervallo statistico.
* SliceID: ID volume o ID sezione

 a| 
Point-in-time
 a| 
Oggetto JSON



 a| 
acceleratore
 a| 
Un valore fluttuante compreso tra 0 e 1 che rappresenta quanto il sistema sta rallentando i client al di sotto dei massimi IOPS a causa della replica dei dati, degli errori transitori e degli snapshot acquisiti.
 a| 
N/A.
 a| 
fluttuare



 a| 
data e ora
 a| 
L'ora corrente nel formato UTC+0.
 a| 
N/A.
 a| 
Stringa di dati ISO 8601



 a| 
UnalignedReads
 a| 
Operazioni di lettura cumulative non allineate per un volume dalla creazione del volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
UnalignedWrites
 a| 
Operazioni di scrittura cumulative non allineate su un volume dopo la creazione del volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
VolumeAccessGroups
 a| 
L'elenco degli ID dei gruppi di accesso ai volumi a cui appartiene un volume.
 a| 
N/A.
 a| 
array intero



 a| 
ID volume
 a| 
L'ID del volume.
 a| 
N/A.
 a| 
intero



 a| 
VolumeDimensioni
 a| 
Capacità totale fornita in byte.
 a| 
N/A.
 a| 
intero



 a| 
VolumeUtilization
 a| 
Un valore in virgola mobile che descrive il modo in cui il client utilizza appieno le funzionalità di input/output del volume rispetto all'impostazione di maxIOPS QoS per quel volume. Valori possibili:

* 0: Il client non sta utilizzando il volume.
* Da 0.01 a 0.99: Il client non utilizza completamente le funzionalità IOPS del volume.
* 1.00: Il client sta utilizzando completamente il volume fino al limite IOPS impostato dall'impostazione maxIOPS.
* > 1.00: Il client sta utilizzando più del limite impostato da maxIOPS. Ciò è possibile quando l'impostazione burstIOPS QoS è superiore a maxIOPS. Ad esempio, se maxIOPS è impostato su 1000 e burstIOPS è impostato su 2000, il `volumeUtilization` il valore sarebbe 2.00 se il client utilizza completamente il volume.

 a| 
N/A.
 a| 
fluttuare



 a| 
WriteByte
 a| 
I byte cumulativi totali scritti nel volume dalla creazione del volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
WriteBytesLastSample
 a| 
Il numero totale di byte scritti nel volume durante l'ultimo periodo di esempio.
 a| 
In aumento monotono
 a| 
intero



 a| 
ScriveLatencyUSec
 a| 
Il tempo medio, in microsecondi, per completare le operazioni di scrittura su un volume negli ultimi 500 millisecondi.
 a| 
Point-in-time
 a| 
intero



 a| 
SwriteLatencyUSecTotal
 a| 
Il tempo totale impiegato per eseguire operazioni di scrittura sul volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
SwriteOps
 a| 
Operazioni di scrittura cumulative totali nel volume dalla creazione del volume.
 a| 
In aumento monotono
 a| 
intero



 a| 
SwriteOpsLastSample
 a| 
Il numero totale di operazioni di scrittura durante l'ultimo periodo di esempio.
 a| 
Point-in-time
 a| 
intero



 a| 
Zero-blocks
 a| 
Il numero totale di blocchi 4KiB vuoti senza dati dopo il completamento dell'ultimo round dell'operazione di garbage collection.
 a| 
Point-in-time
 a| 
intero

|===