---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: 'È possibile utilizzare il metodo SetNodeSupplementalTlsCiphers per specificare l"elenco di crittografia TLS supplementari. È possibile utilizzare questo comando sui nodi di gestione.' 
---
= SetNodeSupplementalTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `SetNodeSupplementalTlsCiphers` Metodo per specificare l'elenco di crittografia TLS supplementari. È possibile utilizzare questo comando sui nodi di gestione.



== Parametro


NOTE: È necessario chiamare questo metodo per il nodo di gestione. Ad esempio:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SuppementalCipher
 a| 
I nomi della suite di crittografia supplementare che utilizzano lo schema di denominazione OpenSSL. L'utilizzo dei nomi delle suite di crittografia non fa distinzione tra maiuscole e minuscole.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===
| Nome | Descrizione | Tipo 


 a| 
MandatoryCipher
 a| 
Elenco delle suite di crittografia TLS obbligatorie per il nodo. Si tratta di cifrari che sono sempre attivi sul nodo.
 a| 
stringa



 a| 
SuppementalCipher
 a| 
Elenco delle suite di crittografia TLS supplementari per il nodo.
 a| 
stringa

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----