---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo ResyncSnapMirrorRelationship per stabilire o ristabilire una relazione mirror tra un endpoint di origine e quello di destinazione. Quando si esegue nuovamente la sincronizzazione di una relazione, il sistema rimuove gli snapshot sul volume di destinazione più recenti della copia snapshot comune, quindi monta il volume di destinazione come volume di protezione dati con la copia snapshot comune come copia snapshot esportata.' 
---
= ResyncSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `ResyncSnapMirrorRelationship` metodo per stabilire o ristabilire una relazione mirror tra un endpoint di origine e di destinazione. Quando si esegue nuovamente la sincronizzazione di una relazione, il sistema rimuove gli snapshot sul volume di destinazione più recenti della copia snapshot comune, quindi monta il volume di destinazione come volume di protezione dati con la copia snapshot comune come copia snapshot esportata.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SnapMirrorEndpointID
 a| 
L'ID endpoint del sistema storage ONTAP remoto che comunica con il cluster storage Element.
 a| 
intero
 a| 
Nessuno
 a| 
Sì



 a| 
DestinationVolume
 a| 
Il volume di destinazione nella relazione SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeinfo]
 a| 
Nessuno
 a| 
Sì



 a| 
MaxTransferRate
 a| 
Specifica la velocità massima di trasferimento dei dati tra i volumi in kilobyte al secondo. Il valore predefinito, 0, è illimitato e consente alla relazione SnapMirror di utilizzare completamente la larghezza di banda di rete disponibile.
 a| 
intero
 a| 
Nessuno
 a| 
No



 a| 
SourceVolume
 a| 
Il volume di origine nella relazione SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeinfo]
 a| 
Nessuno
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
SnapMirrorRelationship
 a| 
Oggetto contenente informazioni sulla relazione SnapMirror resynced.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Novità dalla versione

10,1
