---
permalink: api/reference_element_api_pendingactivenode.html 
sidebar: sidebar 
keywords: object,objects,pendingActiveNode 
summary: 'L"oggetto pendingActiveNode contiene informazioni su un nodo che si trova attualmente nello stato pendingActive, tra lo stato in sospeso e quello attivo. Si tratta di nodi che vengono attualmente restituiti all"immagine software di fabbrica. Utilizzare il metodo API ListPendingActiveNodes per restituire un elenco di queste informazioni per tutti i nodi pendingActive.' 
---
= PendingActiveNode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto pendingActiveNode contiene informazioni su un nodo che si trova attualmente nello stato pendingActive, tra lo stato in sospeso e quello attivo. Si tratta di nodi che vengono attualmente restituiti all'immagine software di fabbrica. Utilizzare `ListPendingActiveNodes` Metodo API per restituire un elenco di queste informazioni per tutti i nodi pendingActive.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
ActiveNodeKey
 a| 
Chiave univoca che consente al nodo di unirsi automaticamente al cluster dopo una corretta installazione del software.
 a| 
stringa



 a| 
AssignedNodeID
 a| 
L'ID nodo assegnato per il nodo.
 a| 
stringa



 a| 
AsyncHandle
 a| 
L'handle del metodo asincrono che è possibile utilizzare per eseguire query sullo stato dell'operazione.
 a| 
intero



 a| 
cip
 a| 
L'indirizzo IP del cluster assegnato al nodo.
 a| 
stringa



 a| 
mip
 a| 
L'indirizzo IP di gestione assegnato al nodo.
 a| 
stringa



 a| 
NodeSlot
 a| 
Per le piattaforme HCI, la lettera corrispondente allo slot dello chassis in cui si trova questo nodo ("A", "B", "C" o "D"). Per le piattaforme storage, questo valore è nullo.
 a| 
stringa



 a| 
PendingActiveNodeID
 a| 
L'ID del nodo in sospeso.
 a| 
intero



 a| 
Informazioni platform
 a| 
Informazioni hardware per il nodo. Membri:

* ChassisType: La piattaforma hardware del nodo.
* CpuModel: Il modello di CPU della piattaforma hardware.
* NodeMemoryGB: La quantità di memoria installata nella piattaforma fisica in GB.
* NodeType: Il nome del modello del nodo.
* PlatformConfigVersion: Versione del software configurato per questo nodo hardware.

 a| 
Oggetto JSON



 a| 
ruolo
 a| 
Ruolo del nodo nel cluster. Valori possibili:

* Gestione
* Storage
* Calcolo
* Testimone

 a| 



 a| 
sip
 a| 
L'indirizzo IP dello storage (iSCSI) assegnato al nodo.
 a| 
stringa



 a| 
Versione software
 a| 
La versione corrente del software Element in esecuzione sul nodo.
 a| 
stringa

|===


== Trova ulteriori informazioni

xref:reference_element_api_listpendingactivenodes.adoc[ListPendingActiveNode]
