---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: 'È possibile utilizzare il metodo ListDriveStats per elencare le misurazioni delle attività di alto livello per più dischi nel cluster. Per impostazione predefinita, questo metodo restituisce statistiche per tutti i dischi nel cluster e queste misurazioni sono cumulative dall"aggiunta del disco al cluster. Alcuni valori restituiti da questo metodo sono specifici per i dischi a blocchi, mentre altri sono specifici per i dischi metadati.' 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListDriveStats` metodo per elencare le misurazioni delle attività di alto livello per più dischi nel cluster. Per impostazione predefinita, questo metodo restituisce statistiche per tutti i dischi nel cluster e queste misurazioni sono cumulative dall'aggiunta del disco al cluster. Alcuni valori restituiti da questo metodo sono specifici per i dischi a blocchi, mentre altri sono specifici per i dischi metadati.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
dischi
 a| 
Elenco degli ID del disco (ID disco) per i quali restituire le statistiche del disco. Se si omette questo parametro, vengono restituite le misurazioni per tutti i dischi.
 a| 
array intero
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===


| Nome | Descrizione | Tipo 


 a| 
DriveStats
 a| 
Elenco delle informazioni sull'attività del disco per ciascun disco.
 a| 
xref:reference_element_api_drivestats.adoc[DriveStats] array



 a| 
errori
 a| 
Questo elenco contiene l'ID del driver e il relativo messaggio di errore. È sempre presente e vuoto se non ci sono errori.
 a| 
Array di oggetti JSON

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_getdrivestats.adoc[GetDriveStats]
