---
permalink: api/reference_element_api_listsyncjobs.html 
sidebar: sidebar 
keywords: sync,synchronization,job,jobs,list,get,listing,getting,listsyncjobs 
summary: È possibile utilizzare il metodo ListSyncJobs per ottenere informazioni sui processi di sincronizzazione in esecuzione in un cluster di storage Element. Questo metodo restituisce informazioni su sezioni, cloni, blocchi e processi di sincronizzazione remota. 
---
= ListSyncJobs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListSyncJobs` Metodo per ottenere informazioni sui processi di sincronizzazione in esecuzione in un cluster di storage Element. Questo metodo restituisce informazioni su sezioni, cloni, blocchi e processi di sincronizzazione remota.



== Parametri

Questo metodo non ha parametri di input.



== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
SyncJobs
 a| 
Elenco degli oggetti che descrivono i processi di sincronizzazione attualmente in esecuzione nel sistema.
 a| 
xref:reference_element_api_syncjob.adoc[SyncJob] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "ListSyncJobs",
   "params": { },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
    "id":1,
    "result":{
      "syncJobs":[
        {
           "bytesPerSecond":275314.8834458956,
           "currentBytes":178257920,
           "dstServiceID":36,
           "elapsedTime":289.4568382049871,
           "percentComplete":8.900523560209423,
           "remainingTime":2962.675921065957,
           "sliceID":5,
           "srcServiceID":16,
           "stage":"whole",
           "totalBytes":200278016remote0,
           "type":"slice"
       },
       {
           "bytesPerSecond":305461.3198607744,
           "cloneID":1,
           "currentBytes":81788928,
           "dstServiceID":16,
           "dstVolumeID":6,
           "elapsedTime":291.7847648200743,
           "nodeID":1,
           "percentComplete":8.167539267015707,
           "remainingTime":3280.708270981153,
           "sliceID":6,
           "srcServiceID":16,
           "srcVolumeID":5,
           "stage":"whole",
           "totalBytes":1001390080,
           "type":"clone"
        },
        {
           "blocksPerSecond":0,
           "branchType": "snapshot",
           "dstServiceID":8,
           "dstVolumeID":2,
           "elapsedTime":0,
           "percentComplete":0,
           "remainingTime":0,
           "sliceID":2,
           "stage":"metadata",
           "type":"remote"
       }
     ]
   }
}
----


== Novità dalla versione

9,6
