---
permalink: api/reference_element_api_node.html 
sidebar: sidebar 
keywords: object,objects,node 
summary: 'L"oggetto node contiene informazioni su ciascun nodo del cluster. È possibile recuperare queste informazioni utilizzando i metodi ListActiveNodes e ListAllNodes.' 
---
= nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto node contiene informazioni su ciascun nodo del cluster. È possibile recuperare queste informazioni utilizzando `ListActiveNodes` e. `ListAllNodes` metodi.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
AssociatedFServiceID
 a| 
L'ID del servizio Fibre Channel per il nodo. "0" se il nodo non è un nodo Fibre Channel.
 a| 
intero



 a| 
AssociatedMasterServiceID
 a| 
ID servizio principale per il nodo.
 a| 
intero



 a| 
attributi
 a| 
Elenco delle coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON



 a| 
ChassisName
 a| 
Identifica in modo univoco uno chassis; identico per tutti i nodi in un unico chassis.
 a| 
stringa



 a| 
cip
 a| 
L'indirizzo IP del cluster assegnato al nodo.
 a| 
stringa



 a| 
cipi
 a| 
Interfaccia di rete utilizzata per la comunicazione del cluster.
 a| 
stringa



 a| 
CustomProtectionDomainName
 a| 
Identifica in modo univoco un dominio di protezione personalizzato. Questo nome è identico per tutti i nodi di storage all'interno di tutti gli chassis in un determinato dominio di protezione personalizzato.
 a| 
stringa



 a| 
FiberChannelTargetPortGroup
 a| 
Il gruppo di destinazione associato a questo nodo. "Null" se il nodo non è un nodo Fibre Channel.
 a| 
intero



 a| 
MaintenanceMode
 a| 
Indica la modalità in cui si trova un nodo per la manutenzione.
 a| 
n/a.



 a| 
mip
 a| 
L'indirizzo IP utilizzato per la gestione dei nodi.
 a| 
stringa



 a| 
mipi
 a| 
Interfaccia di rete utilizzata per la gestione dei nodi.
 a| 
stringa



 a| 
nome
 a| 
Nome host del nodo.
 a| 
stringa



 a| 
ID NodeID
 a| 
NodeID per questo nodo.
 a| 
intero



 a| 
NodeSlot
 a| 
Per le piattaforme HCI, la lettera corrispondente allo slot dello chassis in cui si trova questo nodo ("A", "B", "C" o "D"). Per le piattaforme storage, questo valore è nullo.
 a| 
stringa



 a| 
Informazioni platform
 a| 
Informazioni hardware per il nodo. Membri:

* ChassisType: La piattaforma hardware del nodo.
* CpuModel: Il modello di CPU della piattaforma hardware.
* NodeMemoryGB: La quantità di memoria installata nella piattaforma fisica in GB.
* NodeType: Il nome del modello del nodo.
* PlatformConfigVersion: Versione del software configurato per questo nodo hardware.

 a| 
Oggetto JSON



 a| 
ruolo
 a| 
Ruolo del nodo nel cluster. Valori possibili:

* Gestione
* Storage
* Calcolo
* Testimone

 a| 



 a| 
sip
 a| 
L'indirizzo IP dello storage assegnato al nodo.
 a| 
stringa



 a| 
sipi
 a| 
Interfaccia di rete utilizzata per il traffico di storage.
 a| 
stringa



 a| 
Versione software
 a| 
Restituisce la versione corrente del software Element in esecuzione sul nodo.
 a| 
stringa



 a| 
uuid
 a| 
Identificatore universalmente univoco associato a questo nodo.
 a| 
stringa



 a| 
VirtualNetworks
 a| 
Oggetto contenente gli ID e gli indirizzi IP della rete virtuale.
 a| 
xref:reference_element_api_virtualnetwork.adoc[VirtualNetwork] array

|===


== Trova ulteriori informazioni

* xref:reference_element_api_listactivenodes.adoc[ListActiveNode]
* xref:reference_element_api_listallnodes.adoc[ListAllNode]

