---
permalink: api/reference_element_api_resetdrives.html 
sidebar: sidebar 
keywords: drive,drives,remove,removing,data,reset,resetting,resetdrives,erase 
summary: 'È possibile utilizzare il metodo ResetDrives per inizializzare in maniera proattiva i dischi e rimuovere tutti i dati attualmente presenti su un disco. L"unità può quindi essere riutilizzata in un nodo esistente o in un nodo aggiornato.' 
---
= ResetDrive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ResetDrives` metodo per inizializzare in maniera proattiva i dischi e rimuovere tutti i dati attualmente presenti su un disco. L'unità può quindi essere riutilizzata in un nodo esistente o in un nodo aggiornato.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
dischi
 a| 
Elenco dei nomi dei dispositivi (non degli ID unità) da ripristinare.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì



 a| 
forza
 a| 
Impostare su true per ripristinare l'unità.
 a| 
booleano
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
dettagli
 a| 
Dettagli dei dischi che si stanno ripristinando.
 a| 
Array di oggetti JSON

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "ResetDrives",
   "params": {
      "drives" : "slot3",
      "force" : true
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
   "details": {
    "drives": [
    {
      "drive": "slot3",
      "returnCode": 0,
      "stderr": " * Unlocking /dev/slot9 .[ ok ]\ * Setting master password /dev/slot9 .[ ok ]\ * Secure erasing /dev/slot9 (hdparm) [tries=0/1] ...........................[ ok ]",
      "stdout": ""
    }
   ]
  },
  "duration": "00:00:28.501269",
  "result": "Passed"
  }
}
----


== Novità dalla versione

9,6
