---
permalink: api/reference_element_api_node_getnodefipsdrivesreport.html 
sidebar: sidebar 
keywords: individual,fips,feature,support,info,report,get,getting,getnodefipsdrivesreport,drive 
summary: È possibile utilizzare il metodo GetNodeFipsDrivesReport per controllare lo stato della funzionalità di crittografia del disco FIPS 140-2 di un singolo nodo nel cluster di storage. È necessario eseguire questo metodo su un singolo nodo di storage. 
---
= GetNodeFipsDrivesReport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `GetNodeFipsDrivesReport` Metodo per controllare lo stato della funzionalità di crittografia del disco FIPS 140-2 di un singolo nodo nel cluster di storage. È necessario eseguire questo metodo su un singolo nodo di storage.



== Parametro

Questo metodo non ha alcun parametro di input.



== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===
| Nome | Descrizione | Tipo 


 a| 
FipsDrive
 a| 
Oggetto JSON contenente lo stato del supporto della funzionalità FIPS 140-2 per questo nodo. Valori possibili:

* None (Nessuno): Il nodo non supporta FIPS.
* Parziale: Il nodo supporta FIPS, ma non tutti i dischi nel nodo sono dischi FIPS.
* Pronto: Il nodo è compatibile con FIPS e tutti i dischi nel nodo sono dischi FIPS (o non sono presenti dischi).

 a| 
stringa

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "GetNodeFipsDrivesReport",
  "params": {},
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
    "id": 1,
    "result": {
        "fipsDrives": "None"
    }
}
----


== Novità dalla versione

11,5
