---
permalink: api/reference_element_api_updateidpconfiguration.html 
sidebar: sidebar 
keywords: IdP,idp,configuration,update 
summary: È possibile utilizzare il metodo UpdateIdpConfiguration per aggiornare una configurazione esistente con un IdP di terze parti per il cluster. 
---
= UpdateIdpConfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `UpdateIdpConfiguration` Metodo per aggiornare una configurazione esistente con un IdP di terze parti per il cluster.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
GenerateNewCertificate
 a| 
Quando viene specificato true, viene generata una nuova chiave SAML e un nuovo certificato che sostituisce la coppia esistente. Nota: La sostituzione del certificato esistente interrompe l'attendibilità stabilita tra il cluster e l'IdP fino a quando i metadati del service provider del cluster non vengono ricaricati nell'IdP. Se non viene fornito o impostato su false, il certificato SAML e la chiave rimangono invariati.
 a| 
booleano
 a| 
Nessuno
 a| 
No



 a| 
ID configurazione idpID
 a| 
UUID per la configurazione IdP di terze parti.
 a| 
UUID
 a| 
Nessuno
 a| 
No



 a| 
IdpMetadata
 a| 
Metadati IDP per dettagli di configurazione e integrazione per SAML 2.0 Single Sign-on.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
Nome ID
 a| 
Nome utilizzato per identificare e recuperare un provider IdP per SAML 2.0 Single Sign-on.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
NewIdpName
 a| 
Se specificato, questo nome sostituisce il vecchio nome IdP.
 a| 
stringa
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
IdpConfigInfo
 a| 
Informazioni sulla configurazione IdP di terze parti.
 a| 
link:reference_element_api_idpconfiginfo.html["IdpConfigInfo"]

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
"method": "UpdateIdpConfiguration",
"params": {
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "generateNewCertificate": true
    }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
    "result": {
        "idpConfigInfo": {
        "enabled": true,
        "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
        "idpMetadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n
        <EntityDescriptor xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"\r\n
        xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"\r\n
        xmlns:shibmd=\"urn:mace:shibboleth:metadata:1.0\"\r\n
        xmlns:xml=\"http://www.w3.org/XML/1998/namespace\"\r\n
        ...</Organization>\r\n
        </EntityDescriptor>",
        "idpName": "https://privider.name.url.com",
        "serviceProviderCertificate": "-----BEGIN CERTIFICATE-----\n
        MI...BHi\n
        -----END CERTIFICATE-----\n",
        "spMetadataUrl": "https://10.193.100.100/auth/ui/saml2"
        }
    }
}
----


== Novità dalla versione

12,0
