---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: È possibile utilizzare il metodo GetNodeActiveTlsCiphers su un singolo nodo per ottenere un elenco delle crittografia TLS attualmente accettate su questo nodo. È possibile utilizzare questo metodo sui nodi di gestione e storage. 
---
= GetNodeActiveTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `GetNodeActiveTlsCiphers` Metodo su un singolo nodo per ottenere un elenco dei cifrari TLS attualmente accettati su questo nodo. È possibile utilizzare questo metodo sui nodi di gestione e storage.



== Parametro

Questo metodo non ha parametri di input.



== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===
| Nome | Descrizione | Tipo 


 a| 
MandatoryCipher
 a| 
Elenco delle suite di crittografia TLS obbligatorie per il nodo. Si tratta di cifrari che sono sempre attivi sul nodo.
 a| 
stringa



 a| 
SuppementalCipher
 a| 
Elenco delle suite di crittografia TLS supplementari per il nodo.
 a| 
stringa

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----