---
permalink: api/reference_element_api_gethardwareconfig.html 
sidebar: sidebar 
keywords: node,hardware,config,configuration,get,getting,gethardwareconfig 
summary: È possibile utilizzare il metodo GetHardwareConfig per ottenere le informazioni di configurazione hardware per un nodo. 
---
= GetHardwareConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `GetHardwareConfig` metodo per ottenere le informazioni di configurazione hardware per un nodo. Questi dati di configurazione sono destinati all'uso interno. Per ottenere un inventario dei componenti hardware del sistema più utile, utilizzare `GetHardwareInfo` metodo invece.



== Parametri

Questo metodo non ha parametri di input.



== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


| HardwareConfig | Elenco delle informazioni hardware e delle impostazioni correnti. | Oggetto JSON 
|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "GetHardwareConfig",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Le risposte per questo metodo sono simili all'esempio seguente.

[listing]
----
{
    "id": 1,
    "result": {
        "hardwareConfig": {
            "biosRevision": "1.0",
            "biosVendor": [
                "NetApp",
                "SolidFire"
            ],
            "biosVersion": "1.1.2",
            "blockDriveSizeBytes": 300069052416,
            "blockDrives": [
                "/dev/slot0",
                "/dev/slot1",
                "/dev/slot2",
                "/dev/slot3",
                "/dev/slot4",
                "/dev/slot5",
                "/dev/slot6",
                "/dev/slot7",
                "/dev/slot8",
                "/dev/slot9"
            ],
            "blockServiceFormat": "Standard",
            "bmcFirmwareRevision": "1.6",
            "bmcIpmiVersion": "2.0",
            "chassisType": "R620",
            "cpuCores": 6,
            "cpuCoresEnabled": 6,
            "cpuModel": "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
            "cpuThreads": 12,
            "driveSizeBytesInternal": 400088457216,
            "fibreChannelFirmwareRevision": "",
            "fibreChannelModel": "",
            "fibreChannelPorts": {},
            "idracVersion": "1.06.06",
            "ignoreFirmware": [],
            "memoryGB": 72,
            "memoryMhz": 1333,
            "networkDriver": [
                "bnx2x"
            ],
            "nicPortMap": {
                "PortA": "eth2",
                "PortB": "eth3",
                "PortC": "eth0",
                "PortD": "eth1"
            },
            "nodeType": "SF3010",
            "numCpu": 2,
            "numDrives": 10,
            "numDrivesInternal": 1,
            "nvramTempMonitorEnable": false,
            "rootDrive": "/dev/sdimm0",
            "scsiBusExternalDriver": "mpt3sas",
            "scsiBusInternalDriver": "ahci",
            "sliceDriveSizeBytes": 299988156416,
            "sliceDrives": [
                "/dev/sdimm0p4"
            ],
            "slotOffset": 0,
            "solidfireDefaults": {
                "bufferCacheGB": 12,
                "configuredIops": 50000,
                "cpuDmaLatency": -1,
                "driveWriteThroughputMBPerSleep": 10,
                "maxDriveWriteThroughputMBPerSec": 175,
                "maxIncomingSliceSyncs": 10,
                "postCallbackThreadCount": 8,
                "sCacheFileCapacity": 100000000,
                "sliceFileLogFileCapacity": 5000000000
            }
        }
    }
}
----


== Novità dalla versione

9,6
