---
permalink: api/reference_element_api_restartnetworking.html 
sidebar: sidebar 
keywords: node,restarting,restart,networking,network,service,services,restartnetworking 
summary: È possibile utilizzare il metodo RestartNetworking per riavviare i servizi di rete su un nodo. 
---
= Restart Networking (Ripristino rete)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `RestartNetworking` metodo per riavviare i servizi di rete su un nodo.

ATTENZIONE:

Questo metodo riavvia tutti i servizi di rete su un nodo, causando la perdita temporanea della connettività di rete.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
forza
 a| 
Impostare su true per riavviare i servizi di rete su un nodo.
 a| 
booleano
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo non ha valori restituiti.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "RestartNetworking",
   "params": {
              "force" : true
             },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{ "id" : 1,
  "result" : {}
}
----


== Novità dalla versione

9,6
