---
permalink: api/reference_element_api_listnetworkinterfaces.html 
sidebar: sidebar 
keywords: network,interface,interfaces,list,listing,listnetworkinterfaces 
summary: 'È possibile utilizzare il metodo ListNetworkInterfaces per elencare le informazioni relative a ciascuna interfaccia di rete di un nodo. Questo metodo API è destinato all"utilizzo su singoli nodi; per l"accesso ai singoli nodi è richiesta l"autenticazione di ID utente e password. Tuttavia, è possibile utilizzare questo metodo nel cluster se al parametro force viene assegnato il valore true nella chiamata al metodo. Quando il parametro viene utilizzato nel cluster, vengono elencate tutte le interfacce.' 
---
= ListNetworkInterfaces
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListNetworkInterfaces` metodo per elencare le informazioni relative a ciascuna interfaccia di rete su un nodo. Questo metodo API è destinato all'utilizzo su singoli nodi; per l'accesso ai singoli nodi è richiesta l'autenticazione di ID utente e password. Tuttavia, è possibile utilizzare questo metodo nel cluster se al parametro force viene assegnato il valore true nella chiamata al metodo. Quando il parametro viene utilizzato nel cluster, vengono elencate tutte le interfacce.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
forza
 a| 
Valori possibili:

* True: Vengono restituite informazioni su tutte le interfacce di rete nel cluster.
* Falso: Non viene restituita alcuna informazione.

 a| 
booleano
 a| 
Nessuno
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
interfacce
 a| 
Un elenco di informazioni di configurazione per ciascuna interfaccia di rete del nodo di storage (o dell'intero cluster di storage, se force = `true`).
 a| 
xref:reference_element_api_networkinterface.adoc[NetworkInterface] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
"method": "ListNetworkInterfaces",
"params": {},
"id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
	"id": 1,
	"result": {
		"nodes": [
			{
				"nodeID": 1,
				"result": {
					"interfaces": [
						{
							"address": "10.117.80.32",
							"addressV6": "::",
							"broadcast": "10.117.95.255",
							"macAddress": "90:b1:1c:42:e0:1a",
							"mtu": 9000,
							"name": "Bond10G",
							"namespace": false,
							"netmask": "255.255.240.0",
							"status": "UpAndRunning",
							"type": "BondMaster",
							"virtualNetworkTag": 0
						},
						{
							"address": "10.117.64.32",
							"addressV6": "::",
							"broadcast": "10.117.79.255",
							"macAddress": "90:b1:1c:42:e0:1e",
							"mtu": 1500,
							"name": "Bond1G",
							"namespace": false,
							"netmask": "255.255.240.0",
							"status": "UpAndRunning",
							"type": "BondMaster",
							"virtualNetworkTag": 0
						},
						{
							"address": "0.0.0.0",
							"addressV6": "::",
							"broadcast": "0.0.0.0",
							"macAddress": "90:b1:1c:42:e0:1a",
							"mtu": 9000,
							"name": "eth0",
							"namespace": false,
							"netmask": "0.0.0.0",
							"status": "UpAndRunning",
							"type": "BondSlave",
							"virtualNetworkTag": 0
						},
						{
							"address": "127.0.0.1",
							"addressV6": "::",
							"broadcast": "0.0.0.0",
							"macAddress": "00:00:00:00:00:00",
							"mtu": 0,
							"name": "lo",
							"namespace": false,
							"netmask": "0.0.0.0",
							"status": "UpAndRunning",
							"type": "Loopback",
							"virtualNetworkTag": 0
						}
					]
				}
			}
		]
	}
}
----


== Novità dalla versione

9,6
