---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: 'È possibile utilizzare il metodo GetRemoteLoggingHost per ottenere l"elenco corrente dei server di log.' 
---
= GetRemoteLoggingHost
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `GetRemoteLoggingHosts` metodo per ottenere l'elenco corrente dei server di log.



== Parametri

Non ci sono parametri di input per `GetRemoteLoggingHosts` .



== Valore restituito

IL `GetRemoteLoggingHosts` il metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
Remote
 a| 
Elenca l'indirizzo IP, il nome di dominio completo e le informazioni sulla porta degli host configurati per ricevere le informazioni di registrazione inoltrate
 a| 
xref:reference_element_api_loggingserver.adoc[Server di loggingServer] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         },
         {
            "host": "syslogs.lab.company.net",
            "port": 514
         }
      ]
   }
}
----


== Novità dalla versione

Disponibile a partire da ONTAP 9.6.



== Trova ulteriori informazioni

xref:reference_element_api_setremotelogginghosts.adoc[SetRemoteLoggingHost]
