---
permalink: api/reference_element_api_deleteauthsessionsbyclusteradmin.html 
sidebar: sidebar 
keywords: auth sessions,cluster,admin,delete,authentication sessions 
summary: È possibile utilizzare il metodo DeleteAuthSessionsByClusterAdmin per eliminare tutte le sessioni di autenticazione associate al ClusterAdminID specificato. Se ClusterAdminID specificato viene mappato a un gruppo di utenti, tutte le sessioni di autenticazione per tutti i membri del gruppo verranno eliminate. Per visualizzare un elenco di sessioni da eliminare, utilizzare il metodo ListAuthSessionsByClusterAdmin con il parametro ClusterAdminID. 
---
= DeleteAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `DeleteAuthSessionsByClusterAdmin` metodo per eliminare tutte le sessioni di autenticazione associate al specificato `ClusterAdminID`. Se ClusterAdminID specificato viene mappato a un gruppo di utenti, tutte le sessioni di autenticazione per tutti i membri del gruppo verranno eliminate. Per visualizzare un elenco di sessioni per la possibile eliminazione, utilizzare il metodo ListAuthSessionsByClusterAdmin con `ClusterAdminID` parametro.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
ID clusterAdminID
 a| 
Identificatore univoco dell'amministratore del cluster.
 a| 
intero
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
sessioni
 a| 
Informazioni sulla sessione per le sessioni di autenticazione eliminate.
 a| 
link:reference_element_api_authsessioninfo.html["AuthSessionInfo"]

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "DeleteAuthSessionsByClusterAdmin",
  "params": {
    "clusterAdminID": 1
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Novità dalla versione

12,0
