---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: 'È possibile utilizzare il metodo StartVolumePairing per creare una chiave codificata da un volume utilizzato per l"associazione con un altro volume. La chiave creata da questo metodo viene utilizzata nel metodo CompleteVolumePairing per stabilire un"associazione di volumi.' 
---
= StartVolumePairing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `StartVolumePairing` metodo per creare una chiave codificata da un volume utilizzato per l'associazione con un altro volume. La chiave creata da questo metodo viene utilizzata in `CompleteVolumePairing` metodo per stabilire un'associazione di volumi.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
modalità
 a| 
La modalità del volume su cui avviare il processo di associazione. La modalità può essere impostata solo se il volume è il volume di origine. Valori possibili:

* `Async`: Le scritture vengono riconosciute quando vengono completate localmente. Il cluster non attende la replica delle scritture nel cluster di destinazione. (Impostazione predefinita se non è stato specificato alcun parametro di modalità).
* `Sync`: L'origine riconosce la scrittura quando i dati vengono memorizzati localmente e nel cluster remoto.
* `SnapshotsOnly`: Vengono replicati solo gli snapshot creati nel cluster di origine. Le scritture attive dal volume di origine non vengono replicate.

 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
ID volume
 a| 
L'ID del volume su cui avviare il processo di associazione.
 a| 
intero
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
VolumePairingKey
 a| 
Stringa di caratteri utilizzata da xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] Metodo API.
 a| 
stringa

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
