---
permalink: api/reference_element_api_loggingserver.html 
sidebar: sidebar 
keywords: object,objects,loggingServer 
summary: 'L"oggetto loggingServer contiene informazioni sugli host di registrazione configurati per il cluster di storage. È possibile utilizzare GetRemoteLoggingHosts per determinare quali sono gli host di registrazione correnti e quindi utilizzare SetRemoteLoggingHosts per impostare l"elenco desiderato di host di registrazione correnti e nuovi.' 
---
= Server di loggingServer
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto loggingServer memorizza informazioni sugli host di registrazione configurati per il cluster di archiviazione.  Utilizzo `GetRemoteLoggingHosts` per visualizzare gli host di registrazione correnti e quindi utilizzare `SetRemoteLoggingHosts` per impostare l'elenco desiderato di host di registrazione attuali e nuovi.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
host
 a| 
FQDN o indirizzo IP del server di registro
 a| 
stringa



 a| 
porta
 a| 
Numero di porta utilizzato per comunicare con il server di registro
 a| 
intero

|===
.Informazioni correlate
* link:reference_element_api_getremotelogginghosts.html["GetRemoteLoggingHost"]
* link:reference_element_api_setremotelogginghosts.html["SetRemoteLoggingHost"]

