---
permalink: api/reference_element_api_createsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,relationships,create,creating,CreateSnapMirrorRelationship 
summary: 'L"interfaccia utente Web Element utilizza il metodo CreateSnapMirrorRelationship per creare una relazione di protezione dei dati estesa SnapMirror tra un endpoint di origine e di destinazione.' 
---
= CreateSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web Element utilizza `CreateSnapMirrorRelationship` Metodo per creare una relazione di protezione dei dati estesa di SnapMirror tra un endpoint di origine e di destinazione.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SnapMirrorEndpointID
 a| 
L'ID endpoint del sistema storage ONTAP remoto che comunica con il cluster storage Element.
 a| 
intero
 a| 
Nessuno
 a| 
Sì



 a| 
SourceVolume
 a| 
Il volume di origine nella relazione.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Nessuno
 a| 
Sì



 a| 
DestinationVolume
 a| 
Il volume di destinazione nella relazione.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Nessuno
 a| 
Sì



 a| 
RelazionshipType
 a| 
Il tipo di relazione. Nei sistemi storage che eseguono il software Element, questo valore è sempre "`Extended_data_Protection`".
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
Nome criterio
 a| 
Specifica il nome del criterio SnapMirror di ONTAP per la relazione. Se non specificato, il nome predefinito del criterio è MirrorLatest.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
Nome scheduleName
 a| 
Il nome della pianificazione cron preesistente sul sistema ONTAP utilizzata per aggiornare la relazione SnapMirror. Se non viene specificata alcuna pianificazione, gli aggiornamenti di SnapMirror non vengono pianificati e devono essere aggiornati manualmente.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
MaxTransferRate
 a| 
Specifica la velocità massima di trasferimento dei dati tra i volumi in kilobyte al secondo. Il valore predefinito, 0, è illimitato e consente alla relazione SnapMirror di utilizzare completamente la larghezza di banda di rete disponibile.
 a| 
intero
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===


| Nome | Descrizione | Tipo 


 a| 
SnapMirrorRelationship
 a| 
Informazioni sulla relazione SnapMirror appena creata.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Novità dalla versione

10,1
