---
permalink: api/reference_element_api_getclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,preference,get,getting,getclusterinterfacepreference 
summary: 'Il metodo GetClusterInterfacePreference consente ai sistemi integrati con cluster di storage che eseguono software Element di ottenere informazioni sulle preferenze di un"interfaccia cluster esistente. Questo metodo è per uso interno.' 
---
= GetClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `GetClusterInterfacePreference` Il metodo consente ai sistemi integrati con cluster di storage che eseguono il software Element di ottenere informazioni sulle preferenze di un'interfaccia cluster esistente. Questo metodo è per uso interno.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
nome
 a| 
Il nome della preferenza dell'interfaccia del cluster.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
preferenza
 a| 
Il nome e il valore della preferenza di interfaccia del cluster richiesta.
 a| 
Oggetto JSON

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
	"method": "GetClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
	"id": 1,
	"result": {
		"preference": {
			"name": "prefname",
			"value": "testvalue"
		}
	}
}
----


== Novità dalla versione

11,0
