---
permalink: api/reference_element_api_getipmiconfig.html 
sidebar: sidebar 
keywords: hardware,sensor,config,configuration,get,getting,getipmiconfig 
summary: È possibile utilizzare il metodo GetIpmiConfig per recuperare le informazioni sui sensori hardware dai sensori presenti nel nodo. 
---
= GetIpmiConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `GetIpmiConfig` metodo per recuperare le informazioni sui sensori hardware dai sensori presenti nel nodo.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo 


 a| 
ChassisType
 a| 
Utilizzato per visualizzare le informazioni relative a ciascun tipo di chassis del nodo. Valori possibili:

* all (tutti): restituisce le informazioni del sensore per ciascun tipo di chassis.
* {chassis type} (tipo di telaio): restituisce le informazioni del sensore per un tipo di telaio specifico.

 a| 
stringa

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===
| Nome | Descrizione | Tipo 


 a| 
Nome sensore
 a| 
Nome del sensore trovato.
 a| 
stringa



 a| 
UniqueSensorID
 a| 
Identificatore univoco del sensore.
 a| 
stringa

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "GetIpmiConfig",
  "params": {
     "chassisType"; "all"
     },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
 "id": 1,
   "result": {
     "nodes": [
         {
           "nodeID": 1,
           "result": {
             "ipmiConfig": {
                "C220M4": [
                    {
                     "sensorName": "Fan1A RPM",
                     "uniqueSensorID": "29.1:0xf"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "29.1:0x10"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "29.2:0x11"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "29.2:0x12"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "29.3:0x13"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "29.3:0x14"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "29.4:0x15"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "29.4:0x16"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "29.5:0x17"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "29.5:0x18"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "29.6:0x19"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "29.6:0x1a"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x26"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x2c"
                    }
                ],
                "R620": [
                    {
                      "sensorName": "Fan1A RPM",
                      "uniqueSensorID": "7.1:0x30"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "7.1:0x31"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "7.1:0x32"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "7.1:0x33"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "7.1:0x34"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "7.1:0x35"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "7.1:0x36"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "7.1:0x37"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "7.1:0x38"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "7.1:0x39"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "7.1:0x3a"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "7.1:0x3b"
                    },
                    {
                      "sensorName": "Fan7A RPM",
                      "uniqueSensorID": "7.1:0x3c"
                    },
                    {
                      "sensorName": "Fan7B RPM",
                      "uniqueSensorID": "7.1:0x3d"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x62"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x63"
                    }
               ],
          }
----


== Novità dalla versione

9,6
