---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: È possibile utilizzare il metodo ListVirtualVolumes per elencare i volumi virtuali attualmente presenti nel sistema. È possibile utilizzare questo metodo per elencare tutti i volumi virtuali o solo un sottoinsieme. 
---
= ListVirtualVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListVirtualVolumes` metodo per elencare i volumi virtuali attualmente presenti nel sistema. È possibile utilizzare questo metodo per elencare tutti i volumi virtuali o solo un sottoinsieme.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
dettagli
 a| 
Il livello di dettaglio nella risposta. Valori possibili:

* Vero: Includi ulteriori dettagli su ciascun volume nella risposta.
* Falso: Includere nella risposta il livello standard di dettaglio relativo a ciascun volume.

 a| 
booleano
 a| 
Falso
 a| 
No



 a| 
limite
 a| 
Il numero massimo di volumi virtuali da elencare.
 a| 
intero
 a| 
10000
 a| 
No



 a| 
ricorrente
 a| 
Specifica se includere o meno informazioni sui figli di ogni Vol nella risposta. Valori possibili:

* Vero: Includere nella risposta le informazioni relative ai figli di ciascun volume.
* Falso: Non includere nella risposta le informazioni relative ai figli di ciascun volume.

 a| 
booleano
 a| 
Falso
 a| 
No



 a| 
StartVirtualVolumeID
 a| 
L'ID del volume virtuale in cui iniziare l'elenco nella risposta.
 a| 
UUIDType
 a| 
Nessuno
 a| 
No



 a| 
VirtualVolumeID
 a| 
Un elenco di ID dei volumi virtuali per i quali recuperare le informazioni. Se si omette questo parametro, il metodo restituisce informazioni solo su questi volumi virtuali.
 a| 
Array UUUID virtualVolumeID
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===


| Nome | Descrizione | Tipo 


 a| 
NextVirtualVolumeID
 a| 
L'ID del volume virtuale successivo nell'elenco.
 a| 
UUID



 a| 
VirtualVolumes
 a| 
Un elenco di oggetti che descrivono i volumi virtuali attualmente presenti nel sistema.
 a| 
xref:reference_element_api_virtualvolume.adoc[VirtualVolume] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== Novità dalla versione

9,6
