---
permalink: api/reference_element_api_modifyvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,modifying,modify,change,changing,edit,editing,modifyvolumes 
summary: È possibile utilizzare il metodo ModifyVolumes per configurare fino a 500 volumi esistenti contemporaneamente. Le modifiche vengono eseguite immediatamente. Se ModifyVolumes non riesce a modificare uno dei volumi specificati, nessuno dei volumi specificati viene modificato. 
---
= ModifyVolumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ModifyVolumes` metodo per configurare fino a 500 volumi esistenti contemporaneamente. Le modifiche vengono eseguite immediatamente. Se `ModifyVolumes` impossibile modificare uno dei volumi specificati, nessuno dei volumi specificati viene modificato.

Se non si specificano i valori QoS quando si modificano i volumi, i valori QoS per ciascun volume rimangono invariati. È possibile recuperare i valori QoS predefiniti per un volume appena creato eseguendo `GetDefaultQoS` metodo.

Per evitare errori di replica, è necessario aumentare le dimensioni dei volumi che vengono replicati nel seguente ordine:

. Aumentare le dimensioni del volume con l'accesso ReplicationTarget.
. Aumentare le dimensioni dell'origine o del volume con l'accesso in lettura/scrittura.


Assicurarsi che i volumi di destinazione e di origine abbiano le stesse dimensioni.


NOTE: Se si imposta lo stato di accesso su Locked o ReplicationTarget, tutte le connessioni iSCSI esistenti vengono interrotte.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
accesso
 a| 
Accesso consentito per i volumi. Valori possibili:

* `readOnly`: Sono consentite solo operazioni di lettura.
* `readWrite`: Sono consentite le letture e le scritture.
* `locked`: Non sono consentite letture o scritture. Se non specificato, il valore di accesso non cambia.
* `replicationTarget`: Identifica un volume come volume di destinazione per un set di volumi accoppiati. Se il volume non è associato, lo stato di accesso è bloccato. Se non viene specificato alcun valore, il valore di accesso non cambia.

 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
ID account
 a| 
L'ID account a cui vengono riassegnati i volumi. Se non viene specificato alcun valore, viene utilizzato il nome dell'account precedente.
 a| 
intero
 a| 
Nessuno
 a| 
No



 a| 
AssociateWithQoSPolicy
 a| 
Associare il volume al criterio QoS specificato. Valori possibili:

* `true`: Associare il volume al criterio QoS specificato nel parametro QoSPolicyID.
* `false`: Non associare il volume al criterio QoS specificato nel parametro QoSPolicyID. Se false, qualsiasi associazione di policy esistente viene rimossa, indipendentemente dal fatto che si specifichi o meno un policy QoS nel parametro QoSPolicy.

 a| 
booleano
 a| 
Nessuno
 a| 
No



 a| 
attributi
 a| 
Elenco delle coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
No



 a| 
CreateTime
 a| 
Stringa di dati ISO 8601 da impostare come data di creazione del nuovo volume. Obbligatorio se setCreateTime è impostato su true.
 a| 
Stringa ISO 8601
 a| 
Nessuno
 a| 
No



 a| 
DontMoveforIopsRebalance
 a| 
Impedisce lo spostamento di un volume durante il bilanciamento del carico con IOPS effettivi. Questa impostazione è disponibile a partire dall'elemento 12,8 ed è valida solo quando link:reference_element_api_enablefeature.html["VolumeLoadBalanceOnActualIOPS"] è attivato. Valori possibili:

* `true`: Il volume non esegue il bilanciamento del carico sulla base degli IOPS effettivi.
* `false`: Il bilanciamento del carico viene eseguito in base agli IOPS effettivi.


*Nota*: Il bilanciamento per l'alta disponibilità (guasto del nodo) ha la precedenza su `VolumeLoadBalanceOnActualIOPS` e `dontMoveforIopsRebalance`.
| booleano | falso | No 


 a| 
EnableSnapMirrorReplication
 a| 
Determina se il volume può essere utilizzato per la replica con gli endpoint SnapMirror. Valori possibili:

* `true`
* `false`

 a| 
booleano
 a| 
falso
 a| 
No



| FifoSize | Specifica il numero massimo di snapshot first-in-first-out (FIFO) supportati dal volume. Si noti che gli snapshot FIFO e non FIFO utilizzano entrambi lo stesso pool di slot di snapshot disponibili su un volume. Utilizzare questa opzione per limitare il consumo di snapshot FIFO degli slot snapshot disponibili. Si noti che non è possibile modificare questo valore in modo che sia inferiore al numero corrente di snapshot FIFO. | intero | Nessuno | No 


| MinFifoSize | Specifica il numero di slot di snapshot riservati solo per le istantanee FIFO (first-in-first-out). Poiché le snapshot FIFO e non FIFO condividono lo stesso pool, il parametro minFifuoSize riduce il numero totale di possibili snapshot non FIFO della stessa quantità. Si noti che non è possibile modificare questo valore in modo che sia in conflitto con il numero corrente di snapshot non FIFO. | intero | Nessuno | No 


 a| 
modalità
 a| 
Modalità di replica del volume. Valori possibili:

* `asynch`: Attende che il sistema riconosca che i dati sono memorizzati sull'origine prima di scrivere sulla destinazione.
* `sync`: Non attende che la conferma della trasmissione dei dati dall'origine inizi a scrivere i dati sulla destinazione.

 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
qos
 a| 
Le nuove impostazioni della qualità del servizio per i volumi. Se non specificato, le impostazioni QoS non vengono modificate. Valori possibili:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[QoS]
 a| 
Nessuno
 a| 
No



 a| 
QosPolicyID
 a| 
ID del criterio le cui impostazioni QoS devono essere applicate ai volumi specificati. Questo parametro si esclude a vicenda con il parametro qos.
 a| 
intero
 a| 
Nessuno
 a| 
No



 a| 
SetCreateTime
 a| 
Impostare su vero per modificare la data di creazione del volume registrata.
 a| 
booleano
 a| 
Nessuno
 a| 
No



 a| 
TotalSize (dimensioni totale)
 a| 
La nuova dimensione dei volumi in byte. 1000000000 equivale a 1 GB. Le dimensioni vengono arrotondate al megabyte più vicino. Questo parametro può essere utilizzato solo per aumentare le dimensioni di un volume.
 a| 
intero
 a| 
Nessuno
 a| 
No



 a| 
ID volume
 a| 
Un elenco di volumeID per i volumi da modificare.
 a| 
array intero
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
volume
 a| 
Matrice di oggetti contenente informazioni su ciascun volume appena modificato.
 a| 
xref:reference_element_api_volume.adoc[volume] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "ModifyVolumes",
  "params": {
    "volumeIDs": [319,22],
    "access": "readWrite",
    "dontMoveForIopsRebalance": false
  },
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "volumes":
      {
        "access":  "readWrite,
        "accountID": 22,
        "attributes": {},
        "blockSize": 4096,
        "createTime": "2024-04-01T19:39:40Z",
        "currentProtectionScheme": "doubleHelix",
        "deleteTime": "",
        "dontMoveForIopsRebalance": false,
        "enable512e": false,
        "enableSnapMirrorReplication": false,
        "fifoSize": 24,
        "iqn": "iqn.2010-01.com.solidfire:3eeu.suite40.319",
        "lastAccessTime": "2024-04-02T12:41:34Z",
        "lastAccessTimeIO": "2024-04-01T20:41:19Z",
        "minFifoSize": 0,
        "name": "suite40",
        "previousProtectionScheme": null,
        "purgeTime": "",
        "qos": {
          "burstIOPS": 27000,
          "burstTime": 60,
          "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
          },
          "maxIOPS": 27000,
          "minIOPS": 500
        },
        "qosPolicyID": null,
        "scsiEUIDeviceID": "336565750000013ff47acc0100000000",
        "scsiNAADeviceID": "6f47acc100000000336565750000013f",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000000716800,
        "virtualVolumeID": null,
        "volumeAccessGroups": [
        22
        ],
        "volumeConsistencyGroupUUID": "3003109e-6e75-444c-8cee-470d641a09c3",
        "volumeID": 319,
        "volumePairs": [],
        "
      }
  }
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
