---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'È possibile utilizzare il metodo DeleteStorageContainers per rimuovere dal sistema fino a 2000 container di storage di volume virtuale (Vol) alla volta. I contenitori di storage rimossi non devono contenere VVol.' 
---
= DeleteStorageContainers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `DeleteStorageContainers` Metodo per rimuovere fino a 2000 container di storage Virtual Volume (Vol) dal sistema contemporaneamente. I contenitori di storage rimossi non devono contenere VVol.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
StorageContainerID
 a| 
Un elenco di ID dei contenitori di storage da eliminare. È possibile specificare fino a 2000 ID nell'elenco.
 a| 
Array UUID
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo non ha valori restituiti.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Novità dalla versione

9,6
