---
permalink: api/reference_element_api_resetnode.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile utilizzare il metodo ResetNode per ripristinare le impostazioni predefinite di un nodo. Tutti i dati, i pacchetti (aggiornamenti software, ecc.), le configurazioni e i file di log vengono cancellati dal nodo quando si chiama questo metodo. Tuttavia, le impostazioni di rete per il nodo vengono mantenute durante questa operazione. I nodi che partecipano a un cluster non possono essere ripristinati alle impostazioni predefinite.' 
---
= ResetNode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ResetNode` metodo per ripristinare le impostazioni predefinite di un nodo. Tutti i dati, i pacchetti (aggiornamenti software, ecc.), le configurazioni e i file di log vengono cancellati dal nodo quando si chiama questo metodo. Tuttavia, le impostazioni di rete per il nodo vengono mantenute durante questa operazione. I nodi che partecipano a un cluster non possono essere ripristinati alle impostazioni predefinite.



== Parametri

L'API ResetNode può essere utilizzata solo su nodi che si trovano in uno stato "disponibile". Non può essere utilizzato su nodi "attivi" in un cluster o in uno stato "in sospeso".

ATTENZIONE:

Questo metodo consente di eliminare tutti i dati del cliente presenti nel nodo.

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
costruire
 a| 
Consente di specificare l'URL di un'immagine software dell'elemento remoto in cui il nodo verrà reimpostato.
 a| 
URL
 a| 
Nessuno
 a| 
No



 a| 
forza
 a| 
Impostare su true per ripristinare il nodo.
 a| 
booleano
 a| 
Nessuno
 a| 
Sì



 a| 
opzioni
 a| 
Consente di immettere le specifiche per l'esecuzione delle operazioni di ripristino. I dettagli sono forniti dal supporto NetApp, se necessario.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo non ha valori restituiti.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "ResetNode",
   "params": {
      "build" : "file:///sf/rtfi/image/filesystem.squashfs",
      "force" : true
              },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": null,
  "result": {
    "rtfiInfo": {
      "build": "file:///sf/rtfi/image/filesystem.squashfs",
      "generation": "9",
      "options": {
        "edebug": "",
        "sf_auto": "0",
        "sf_bond_mode": "ActivePassive",
        "sf_check_hardware": "0",
        "sf_disable_otpw": "0",
        "sf_fa_host": "",
        "sf_hostname": "SF-FA18",
        "sf_inplace": "1",
        "sf_inplace_die_action": "kexec",
        "sf_inplace_safe": "0",
        "sf_keep_cluster_config": "0",
        "sf_keep_data": "0",
        "sf_keep_hostname": "0",
        "sf_keep_network_config": "0",
        "sf_keep_paths": "\"/var/log/hardware.xml\"",
        "sf_max_archives": "5",
        "sf_nvram_size": "",
        "sf_oldroot": "",
        "sf_postinst_erase_root_drive": "0",
        "sf_root_drive": "",
        "sf_rtfi_cleanup_state": "",
        "sf_secure_erase": "1",
        "sf_secure_erase_retries": "5",
        "sf_slice_size": "",
        "sf_ssh_key": "1",
        "sf_ssh_root": "1",
        "sf_start_rtfi": "1",
        "sf_status_httpserver": "1",
        "sf_status_httpserver_stop_delay": "5m",
        "sf_status_inject_failure": "",
        "sf_status_json": "0",
        "sf_support_host": "sfsupport.solidfire.com",
        "sf_test_hardware": "0",
        "sf_upgrade": "0",
        "sf_upgrade_firmware": "0",
        "sf_upload_logs_url": ""
     },
      "statusUrlAll": "http://192.168.130.20/status/all.json",
      "statusUrlCurrent": "http://192.168.130.20/status/current.json"
    }
  }
}
----


== Novità dalla versione

9,6
