---
permalink: api/reference_element_api_listvirtualvolumehosts.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,host,hosts,list,listing,known,listvirtualvolumehosts 
summary: È possibile utilizzare il metodo ListVirtualVolumeHosts per ottenere un elenco di tutti gli host dei volumi virtuali noti al cluster. Un host di volume virtuale è un host VMware ESX che ha avviato una sessione con il provider API VASA. 
---
= ListVirtualVolumeHost
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListVirtualVolumeHosts` metodo per ottenere un elenco di tutti gli host di volumi virtuali noti al cluster. Un host di volume virtuale è un host VMware ESX che ha avviato una sessione con il provider API VASA.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
VirtualVolumeHostID
 a| 
Un elenco di ID host del volume virtuale per i quali recuperare le informazioni. Se si omette questo parametro, il metodo restituisce informazioni su tutti gli host di volumi virtuali.
 a| 
Array UUID virtualVolumeHostID
 a| 
Nessuno
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


 a| 
host
 a| 
Un elenco di oggetti che descrivono gli host dei volumi virtuali nel cluster.
 a| 
xref:reference_element_api_host.adoc[host] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "ListVirtualVolumeHosts",
    "params": {
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "hosts": [
      {
        "bindings": [],
        "clusterID": "5ebdb4ad-9617-4647-adfd-c1013578483b",
        "hostAddress": "172.30.89.117",
        "initiatorNames": [
          "iqn.1998-01.com.vmware:zdc-dhcp-0-c-29-d6-4b-f1-1a0cd614",
          "iqn.1998-01.com.vmware:zdc-dhcp-0-c-29-d6-4b-f1-5bcf9254"
        ],
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "visibleProtocolEndpointIDs": [
          "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b"
        ]
      }
    ]
  }
}
----


== Novità dalla versione

9,6
