---
permalink: api/reference_element_api_virtualnetwork.html 
sidebar: sidebar 
keywords: object,objects,virtualNetwork 
summary: 'L"oggetto virtualNetwork contiene informazioni su una specifica rete virtuale. È possibile utilizzare il metodo API ListVirtualNetworks per recuperare un elenco di queste informazioni per tutte le reti virtuali del sistema.' 
---
= VirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto virtualNetwork contiene informazioni su una specifica rete virtuale. È possibile utilizzare `ListVirtualNetworks` Metodo API per recuperare un elenco di queste informazioni per tutte le reti virtuali nel sistema.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
AddressBllocks
 a| 
L'intervallo di blocchi di indirizzi attualmente assegnati alla rete virtuale. Membri:

* Disponibile: Stringa binaria in "1" e "0" "1" indica che l'indirizzo IP è disponibile e "0" indica che l'indirizzo IP non è disponibile. La stringa viene letta da destra a sinistra con la cifra all'estrema destra che rappresenta il primo indirizzo IP nell'elenco dei blocchi di indirizzi.
* Size (dimensione): La dimensione di questo blocco di indirizzi.
* Start (inizio): Il primo indirizzo IP del blocco.

 a| 
Array di oggetti JSON



 a| 
attributi
 a| 
Elenco delle coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON



 a| 
nome
 a| 
Il nome assegnato alla rete virtuale.
 a| 
stringa



 a| 
netmask
 a| 
L'indirizzo IP della netmask per la rete virtuale.
 a| 
stringa



 a| 
svip
 a| 
L'indirizzo IP dello storage per la rete virtuale.
 a| 
stringa



 a| 
gateway
 a| 
Gateway utilizzato per la rete virtuale.
 a| 
stringa



 a| 
VirtualNetworkID
 a| 
Identificatore univoco di una rete virtuale.
 a| 
intero



 a| 
VirtualNetworkTag
 a| 
L'identificatore del tag VLAN.
 a| 
intero

|===


== Trova ulteriori informazioni

xref:reference_element_api_listvirtualnetworks.adoc[ListVirtualNetworks]
