---
permalink: api/reference_element_api_getvolumestats.html 
sidebar: sidebar 
keywords: volume,volumes,get,getting,stats,measurements,activity,getvolumestats 
summary: È possibile utilizzare il metodo GetVolumeStats per ottenere misurazioni di alto livello delle attività per un singolo volume. I valori sono cumulativi dalla creazione del volume. 
---
= GetVolumeStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `GetVolumeStats` metodo per ottenere misurazioni di attività di alto livello per un singolo volume. I valori sono cumulativi dalla creazione del volume.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
ID volume
 a| 
Specifica il volume per il quale vengono raccolte le statistiche.
 a| 
intero
 a| 
Nessuno
 a| 
Sì

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
VolumeStats
 a| 
Informazioni sull'attività del volume.
 a| 
xref:reference_element_api_volumestats.adoc[VolumeStats]

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "GetVolumeStats",
   "params": {
      "volumeID": 32
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": {
      "accountID": 1,
      "actualIOPS": 0,
      "asyncDelay": null,
      "averageIOPSize": 0,
      "burstIOPSCredit": 0,
      "clientQueueDepth": 0,
      "desiredMetadataHosts": null,
      "latencyUSec": 0,
      "metadataHosts": {
        "deadSecondaries": [],
        "liveSecondaries": [
          32
        ],
        "primary": 60
      },
      "nonZeroBlocks": 0,
      "readBytes": 0,
      "readBytesLastSample": 0,
      "readLatencyUSec": 0,
      "readOps": 0,
      "readOpsLastSample": 0,
      "samplePeriodMSec": 0,
      "throttle": 0,
      "timestamp": "2016-04-01T21:01:39.130840Z",
      "unalignedReads": 0,
      "unalignedWrites": 0,
      "volumeAccessGroups": [],
      "volumeID": 1,
      "volumeSize": 5000658944,
      "volumeUtilization": 0,
      "writeBytes": 0,
      "writeBytesLastSample": 0,
      "writeLatencyUSec": 0,
      "writeOps": 0,
      "writeOpsLastSample": 0,
      "zeroBlocks": 1220864
    }
  }
}
----


== Novità dalla versione

9,6
