---
permalink: api/reference_element_api_createsnapmirrorendpoint_unmanaged.html 
sidebar: sidebar 
keywords: SnapMirror,endpoint,unmanaged,create,creating,CreateSnapMirrorEndpointUnmanaged 
summary: Il sistema di storage software Element utilizza il metodo CreateSnapMirrorEndpointUnmanaged per consentire agli endpoint SnapMirror remoti e non gestiti di comunicare con un cluster di storage Element. Gli endpoint non gestiti non possono essere amministrati utilizzando le API di Element SnapMirror. Devono essere gestiti con il software di gestione ONTAP o le API. 
---
= CreateSnapMirrorEndpointUnmanaged
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema di storage software Element utilizza `CreateSnapMirrorEndpointUnmanaged` Metodo per consentire agli endpoint SnapMirror remoti e non gestiti di comunicare con un cluster di storage Element. Gli endpoint non gestiti non possono essere amministrati utilizzando le API di Element SnapMirror. Devono essere gestiti con il software di gestione ONTAP o le API.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
Nome cluster
 a| 
Il nome dell'endpoint.
 a| 
stringa
 a| 
Nessuno
 a| 
Sì



 a| 
Indirizzi ipAddresses
 a| 
L'elenco degli indirizzi IP di un cluster di sistemi storage ONTAP che devono comunicare con questo cluster di storage Element.
 a| 
array di stringhe
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===


| Nome | Descrizione | Tipo 


 a| 
SnapMirrorEndpoint
 a| 
Endpoint SnapMirror appena creato.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[SnapMirrorEndpoint]

|===


== Novità dalla versione

10,3
