---
permalink: api/reference_element_api_testconnectmvip.html 
sidebar: sidebar 
keywords: management,connection,test,testing,mvip,testconnectmvip 
summary: È possibile utilizzare il metodo TestConnectMvip per verificare la connessione di gestione al cluster di storage. Il test esegue il ping di MVIP ed esegue un semplice metodo API per verificare la connettività. 
---
= TestConnectMvip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `TestConnectMvip` metodo per verificare la connessione di gestione al cluster di storage. Il test esegue il ping di MVIP ed esegue un semplice metodo API per verificare la connettività.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


| mvip | È possibile superare questo valore per verificare la connessione di gestione di un diverso MVIP. Non è necessario utilizzare questo valore durante il test della connessione al cluster di destinazione. | stringa | Nessuno | No 
|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===
| Nome | Descrizione | Tipo 


| dettagli  a| 
Informazioni sull'operazione di test (oggetto JSON):

* `connected`: Indica se il test potrebbe connettersi a MVIP (booleano)
* `mvip`: L'MVIP testato rispetto a (stringa)
* `pingBytes`: Dettagli dei test ping con 56 byte e 1500 byte (oggetto)
+
** `56`: Risultati del test ping a 56 byte (oggetto JSON):
+
*** `individualResponseTimes`: Elenco dei tempi di risposta da ciascun nodo dell'ensemble (array di stringhe)
*** `individualStatus`: Elenco dello stato del ping da ciascun nodo dell'ensemble (array booleano)
*** `responseTime`: Tempo medio di risposta ping (stringa)
*** `successful`: Indica se il test ping ha avuto esito positivo (booleano)


** `1500`: Risultati del test ping a 1500 byte (oggetto JSON):
+
*** `individualResponseTimes`: Elenco dei tempi di risposta da ciascun nodo dell'ensemble (array di stringhe)
*** `individualStatus`: Elenco dello stato del ping da ciascun nodo dell'ensemble (array booleano)
*** `responseTime`: Tempo medio di risposta ping (stringa)
*** `successful`: Se il test ping ha avuto esito positivo (booleano)


** `duration`: Durata del tempo necessario per eseguire il test (stringa)
** `result`: Risultato del test nel suo complesso (stringa)



| Oggetto JSON 
|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "TestConnectMvip",
   "params": {
       "mvip" : "172.27.62.50"
       },
    "id":1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "mvip": "172.27.62.50",
      "pingBytes": {
        "1500": {
          "individualResponseTimes": [
            "00:00:00.000250",
            "00:00:00.000206",
            "00:00:00.000200",
            "00:00:00.000199",
            "00:00:00.000199"
         ],
          "individualStatus": [
             true,
             true,
             true,
             true,
             true
         ],
         "responseTime": "00:00:00.000211",
         "successful": true
       },
       "56": {
          "individualResponseTimes": [
            "00:00:00.000217",
            "00:00:00.000122",
            "00:00:00.000117",
            "00:00:00.000119",
            "00:00:00.000121"
         ],
         "individualStatus": [
            true,
            true,
            true,
            true,
            true
         ],
         "responseTime": "00:00:00.000139",
         "successful": true
        }
      }
    },
    "duration": "00:00:00.271244",
    "result": "Passed"
  }
}
----


== Novità dalla versione

9,6
