---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: È possibile utilizzare il metodo ListEvents per elencare gli eventi rilevati nel cluster, ordinati da meno recenti a più recenti. 
---
= ListEvents
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ListEvents` metodo per elencare gli eventi rilevati nel cluster, ordinati da meno recente a più recente.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
ID del driver
 a| 
Specifica che verranno restituiti solo gli eventi con questo ID disco.
 a| 
intero
 a| 
0
 a| 
No



 a| 
EndEventID
 a| 
Identifica la fine di un intervallo di ID evento da restituire.
 a| 
intero
 a| 
(senza limiti)
 a| 
No



 a| 
EndPublishTime
 a| 
Specifica che verranno restituiti solo gli eventi pubblicati prima di questo orario.
 a| 
stringa
 a| 
0
 a| 
No



 a| 
EndReportTime
 a| 
Specifica che verranno restituiti solo gli eventi riportati prima di questo orario.
 a| 
stringa
 a| 
0
 a| 
No



 a| 
EventType
 a| 
Specifica il tipo di eventi da restituire. Vedere xref:reference_element_api_event.adoc[evento] per i possibili tipi di evento.
 a| 
stringa
 a| 
0
 a| 
No



 a| 
MaxEvents
 a| 
Specifica il numero massimo di eventi da restituire.
 a| 
intero
 a| 
(senza limiti)
 a| 
No



 a| 
ID NodeID
 a| 
Specifica che verranno restituiti solo gli eventi con questo ID nodo.
 a| 
intero
 a| 
 a| 



 a| 
ID servizio
 a| 
Specifica che verranno restituiti solo gli eventi con questo ID servizio.
 a| 
 a| 
 a| 



 a| 
StartEventID
 a| 
Identifica l'inizio di un intervallo di eventi da restituire.
 a| 
intero
 a| 
0
 a| 
No



 a| 
StartPublishTime
 a| 
Specifica che verranno restituiti solo gli eventi pubblicati dopo questo intervallo di tempo.
 a| 
stringa
 a| 
0
 a| 
No



 a| 
StartReportTime
 a| 
Specifica che verranno restituiti solo gli eventi riportati dopo questo intervallo di tempo.
 a| 
stringa
 a| 
0
 a| 
No

|===


== Valore restituito

Questo metodo ha il seguente valore restituito:

|===


| Nome | Descrizione | Tipo 


 a| 
eventi
 a| 
Elenco degli eventi.
 a| 
xref:reference_element_api_event.adoc[evento] array

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Novità dalla versione

9,6
