---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: È possibile utilizzare il metodo SetSnmpInfo per configurare SNMP versione 2 e versione 3 sui nodi del cluster. I valori impostati con questa interfaccia si applicano a tutti i nodi del cluster e i valori passati sostituiscono tutti i valori impostati in qualsiasi chiamata precedente a SetSnmpInfo. 
---
= SetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `SetSnmpInfo` Metodo per configurare SNMP versione 2 e versione 3 sui nodi del cluster. I valori impostati con questa interfaccia si applicano a tutti i nodi del cluster e i valori passati sostituiscono tutti i valori impostati in qualsiasi chiamata precedente a. `SetSnmpInfo`.



== Parametri


NOTE: SetSnmpInfo è obsoleto per Element versione 6.0 e successive. Utilizzare xref:reference_element_api_enablesnmp.adoc[EnableSnmp] e. xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] invece.

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
reti
 a| 
Elenco delle reti e tipo di accesso ai server SNMP in esecuzione sui nodi del cluster. Consultare la sezione SNMP xref:reference_element_api_network_snmp.adoc[rete] oggetto per i valori possibili. Questo parametro è obbligatorio solo per SNMP v2.
 a| 
xref:reference_element_api_network_snmp.adoc[rete] array
 a| 
Nessuno
 a| 
No



 a| 
attivato
 a| 
Se impostato su true, SNMP viene attivato su ciascun nodo del cluster.
 a| 
booleano
 a| 
falso
 a| 
No



 a| 
SnmpV3Enabled (snmpV3Enabled)
 a| 
Se impostato su true, SNMP v3 viene attivato su ciascun nodo del cluster.
 a| 
booleano
 a| 
falso
 a| 
No



 a| 
UsmUsers
 a| 
Se SNMP v3 è attivato, questo valore deve essere passato al posto del parametro networks. Questo parametro è necessario solo per SNMP v3.
 a| 
xref:reference_element_api_usmuser.adoc[UsmUser]
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo non ha valori restituiti.



== Esempio di richiesta con SNMP v3 attivato

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== Esempio di richiesta con SNMP v2 attivato

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== Novità dalla versione

9,6
