---
permalink: api/reference_element_api_breaksnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,volume,volumes,break,breaking,relationship,ONTAP 
summary: 'L"interfaccia utente Web Element utilizza il metodo BreakSnapMirrorRelationship per interrompere una relazione SnapMirror. Quando una relazione SnapMirror viene interrotta, il volume di destinazione viene reso indipendente e di lettura/scrittura e può quindi divergere dall"origine. È possibile ristabilire la relazione con il metodo ResyncSnapMirrorRelationship API. Questo metodo richiede la disponibilità del cluster ONTAP.' 
---
= BreakSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web Element utilizza `BreakSnapMirrorRelationship` Metodo per interrompere una relazione SnapMirror. Quando una relazione SnapMirror viene interrotta, il volume di destinazione viene reso indipendente e di lettura/scrittura e può quindi divergere dall'origine. È possibile ristabilire la relazione con `ResyncSnapMirrorRelationship` Metodo API. Questo metodo richiede la disponibilità del cluster ONTAP.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
SnapMirrorEndpointID
 a| 
L'ID endpoint del sistema storage ONTAP remoto che comunica con il cluster storage Element.
 a| 
intero
 a| 
Nessuno
 a| 
Sì



 a| 
DestinationVolume
 a| 
Il volume di destinazione nella relazione SnapMirror.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[SnapMirrorVolumeInfo]
 a| 
Nessuno
 a| 
Sì

|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===


| Nome | Descrizione | Tipo 


 a| 
SnapMirrorRelationship
 a| 
Oggetto contenente informazioni sulla relazione SnapMirror interrotta.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[SnapMirrorRelationship]

|===


== Novità dalla versione

10,1



== Trova ulteriori informazioni

xref:reference_element_api_breaksnapmirrorvolume.adoc[BreakSnapMirrorVolume]
