---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: È possibile utilizzare il metodo ModifyVirtualNetwork per modificare gli attributi di una rete virtuale esistente. 
---
= ModifyVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `ModifyVirtualNetwork` metodo per modificare gli attributi di una rete virtuale esistente.

Questo metodo consente di aggiungere o rimuovere blocchi di indirizzi, modificare la netmask o modificare il nome o la descrizione della rete virtuale. È inoltre possibile utilizzarlo per attivare o disattivare gli spazi dei nomi, nonché per aggiungere o rimuovere un gateway se gli spazi dei nomi sono attivati sulla rete virtuale.


NOTE: Questo metodo richiede virtualNetworkID o virtualNetworkTag come parametro, ma non entrambi.

ATTENZIONE:

L'attivazione o la disattivazione della funzionalità delle VLAN di storage instradabili per una rete virtuale esistente modificando il parametro namespace interrompe qualsiasi traffico gestito dalla rete virtuale. Si consiglia di modificare il parametro namespace durante una finestra di manutenzione pianificata.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


 a| 
VirtualNetworkID
 a| 
Identificatore univoco della rete virtuale da modificare. Si tratta dell'ID della rete virtuale assegnato dal cluster.
 a| 
intero
 a| 
Nessuno
 a| 
No



 a| 
VirtualNetworkTag
 a| 
Tag di rete che identifica la rete virtuale da modificare.
 a| 
intero
 a| 
Nessuno
 a| 
No



 a| 
AddressBllocks
 a| 
Il nuovo blocco di indirizzi da impostare per questa rete virtuale. Ciò potrebbe includere nuovi blocchi di indirizzi da aggiungere all'oggetto esistente o omettere blocchi di indirizzi inutilizzati che devono essere rimossi. In alternativa, è possibile estendere o ridurre le dimensioni dei blocchi di indirizzi esistenti. È possibile solo aumentare la dimensione degli indirizzi iniziali per un oggetto di rete virtuale; non è possibile ridurla. Membri obbligatori per questo oggetto:

* Start (inizio): Inizio dell'intervallo di indirizzi IP. (stringa)
* Size (dimensione): Il numero di indirizzi IP da includere nel blocco. (intero)

 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
No



 a| 
gateway
 a| 
L'indirizzo IP di un gateway della rete virtuale. Questo parametro è valido solo se il parametro namespace è impostato su true.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
attributi
 a| 
Elenco delle coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
No



 a| 
nome
 a| 
Il nuovo nome della rete virtuale.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
namespace
 a| 
Se impostata su true, attiva la funzionalità delle VLAN di storage instradabili ricreando la rete virtuale e configurando uno spazio dei nomi in modo da contenerla. Se impostata su false, disattiva la funzionalità VRF per la rete virtuale. La modifica di questo valore interrompe il traffico in esecuzione su questa rete virtuale.
 a| 
booleano
 a| 
Nessuno
 a| 
No



 a| 
netmask
 a| 
Nuova maschera di rete per questa rete virtuale.
 a| 
stringa
 a| 
Nessuno
 a| 
No



 a| 
svip
 a| 
L'indirizzo IP virtuale dello storage per questa rete virtuale. Non è possibile modificare l'SVIP di una rete virtuale. È necessario creare una nuova rete virtuale per utilizzare un indirizzo SVIP diverso.
 a| 
stringa
 a| 
Nessuno
 a| 
No

|===


== Valori restituiti

Questo metodo non ha valori restituiti.



== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== Novità dalla versione

9,6
