---
permalink: api/reference_element_api_createvolume.html 
sidebar: sidebar 
keywords: create,volume,volumes,creating,CreateVolume 
summary: È possibile utilizzare il metodo CreateVolume per creare un nuovo volume vuoto nel cluster. Al termine della creazione del volume, il volume è disponibile per la connessione tramite iSCSI. 
---
= CreateVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare `CreateVolume` metodo per creare un nuovo volume vuoto nel cluster. Non appena il volume viene creato, il volume è disponibile per la connessione tramite iSCSI.

I volumi creati senza valori QoS specificati utilizzano i valori predefiniti. È possibile visualizzare i valori predefiniti di un volume utilizzando `GetDefaultQoS` metodo.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Obbligatorio 


| `access` | La modalità di accesso per il volume. Se questo parametro è incluso, l'unico valore supportato è `snapMirrorTarget`. | stringa | Nessuno | No 


| `accountID` | L'ID dell'account proprietario di questo volume. | intero | Nessuno | Sì 


| `associateWithQoSPolicy`  a| 
Associare il volume al criterio QoS specificato. Valori possibili:

* `true`: Associare il volume al criterio QoS specificato nel parametro QoSPolicyID.
* `false`: Non associare il volume al criterio QoS specificato nel parametro QoSPolicyID. Se false, qualsiasi associazione di policy esistente viene rimossa, indipendentemente dal fatto che si specifichi o meno un policy QoS nel parametro QoSPolicy.

| booleano | vero | No 


| `attributes` | Elenco delle coppie nome-valore nel formato oggetto JSON. La dimensione totale dell'attributo deve essere inferiore a 1000B o 1KB, inclusi i caratteri di formattazione JSON. | Oggetto JSON | Nessuno | No 


| `enable512e`  a| 
Abilitare l'emulazione di settore a 512 byte. Valori possibili:

* `true`: Il volume fornisce l'emulazione di settore a 512 byte.
* `false`: l'emulazione 512e non è abilitata.

| booleano | Nessuno | Sì 


| `enableSnapMirrorReplication`  a| 
Determina se il volume può essere utilizzato per la replica con gli endpoint SnapMirror. Valori possibili:

* `true`
* `false`

| booleano | falso | No 


| `fifoSize` | Specifica il numero massimo di snapshot first-in-first-out (FIFO) supportati dal volume. Si noti che gli snapshot FIFO e non FIFO utilizzano entrambi lo stesso pool di slot di snapshot disponibili su un volume. Utilizzare questa opzione per limitare il consumo di snapshot FIFO degli slot snapshot disponibili. Se omesso, il valore predefinito è 24. | intero | 24 | No 


| `minFifoSize` | Specifica il numero minimo di slot di snapshot FIFO (first-in-first-out) riservati dal volume. In questo modo, se si utilizzano snapshot FIFO e snapshot non FIFO su un volume, gli snapshot non FIFO non consumano involontariamente troppi slot FIFO. Inoltre, garantisce che almeno questo numero di snapshot FIFO sia sempre disponibile. Poiché le snapshot FIFO e non FIFO condividono lo stesso pool, il `minFifoSize` Riduce il numero totale di possibili snapshot non FIFO della stessa quantità. Se omesso, il valore predefinito è 0. | intero | 0 | No 


| `name` | Nome del gruppo di accesso al volume (può essere specificato dall'utente). Non è necessario essere unici, ma consigliato. La lunghezza deve essere compresa tra 1 e 64 caratteri. | stringa | Nessuno | Sì 


| `qos`  a| 
Le impostazioni iniziali della qualità del servizio per questo volume. I valori predefiniti vengono utilizzati se non sono specificati. Valori possibili:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

| Oggetto QoS | Nessuno | No 


| `qosPolicyID` | ID del criterio le cui impostazioni QoS devono essere applicate ai volumi specificati. Questo parametro si esclude reciprocamente con `qos` parametro. | intero | Nessuno | No 


| `totalSize` | Dimensione totale del volume, in byte. Le dimensioni vengono arrotondate al megabyte più vicino. | intero | Nessuno | Sì 
|===


== Valori restituiti

Questo metodo ha i seguenti valori restituiti:

|===


| Nome | Descrizione | Tipo 


 a| 
volume
 a| 
Oggetto contenente informazioni sul volume appena creato.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
ID volume
 a| 
ID volume per il volume appena creato.
 a| 
intero



 a| 
curva
 a| 
La curva è un insieme di coppie chiave-valore. Le chiavi sono le dimensioni i/o in byte. I valori rappresentano il costo dell'esecuzione di un IOP a una dimensione i/o specifica. La curva viene calcolata in relazione a un'operazione di 4096 byte impostata su 100 IOPS.
 a| 
Oggetto JSON

|===


== Esempio di richiesta

Le richieste per questo metodo sono simili all'esempio seguente:

[listing]
----
{
   "method": "CreateVolume",
   "params": {
      "name": "mysqldata",
      "accountID": 1,
      "totalSize": 107374182400,
      "enable512e": false,
      "attributes": {
         "name1": "value1",
         "name2": "value2",
         "name3": "value3"
      },
      "qos": {
         "minIOPS": 50,
         "maxIOPS": 500,
         "burstIOPS": 1500,
         "burstTime": 60
      }
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile all'esempio seguente:

[listing]
----
{
    "id": 1,
    "result": {
        "curve": {
            "4096": 100,
            "8192": 160,
            "16384": 270,
            "32768": 500,
            "65536": 1000,
            "131072": 1950,
            "262144": 3900,
            "524288": 7600,
            "1048576": 15000
        },
        "volume": {
            "access": "readWrite",
            "accountID": 1,
            "attributes": {
                "name1": "value1",
                "name2": "value2",
                "name3": "value3"
            },
            "blockSize": 4096,
            "createTime": "2016-03-31T22:20:22Z",
            "deleteTime": "",
            "enable512e": false,
            "iqn": "iqn.2010-01.com.solidfire:mysqldata.677",
            "name": "mysqldata",
            "purgeTime": "",
            "qos": {
                "burstIOPS": 1500,
                "burstTime": 60,
                "curve": {
                    "4096": 100,
                    "8192": 160,
                    "16384": 270,
                    "32768": 500,
                    "65536": 1000,
                    "131072": 1950,
                    "262144": 3900,
                    "524288": 7600,
                    "1048576": 15000
                },
                "maxIOPS": 500,
                "minIOPS": 50
            },
            "scsiEUIDeviceID": "6a796179000002a5f47acc0100000000",
            "scsiNAADeviceID": "6f47acc1000000006a796179000002a5",
            "sliceCount": 0,
            "status": "active",
            "totalSize": 107374182400,
            "virtualVolumeID": null,
            "volumeAccessGroups": [],
            "volumeID": 677,
            "volumePairs": []
        },
        "volumeID": 677
    }
}
----


== Novità dalla versione

9,6



== Trova ulteriori informazioni

xref:reference_element_api_getdefaultqos.adoc[GetDefaultQoS]
